import {
  COMMERCIAL_DOCUMENT_CONTEXT_RELATIONS,
  COMMERCIAL_DOCUMENT_ENTITY_HINT_KINDS,
  COMMERCIAL_DOCUMENT_MAP_DOCUMENT_KINDS,
  COMMERCIAL_DOCUMENT_MAP_LIMITS,
  COMMERCIAL_DOCUMENT_MAP_SCHEMA_VERSION,
  COMMERCIAL_DOCUMENT_NOTE_KINDS,
  COMMERCIAL_DOCUMENT_PAGE_ROLES,
  COMMERCIAL_DOCUMENT_SECTION_ROLES,
  COMMERCIAL_EXTRACTION_UNIT_LIMITS,
  COMMERCIAL_EXTRACTION_UNIT_PLAN_SCHEMA_VERSION,
  COMMERCIAL_EXTRACTION_UNIT_TYPES,
} from './commercial-document-map';

const id = (prefix: string) =>
  ({ type: 'string', pattern: `^${prefix}-[a-z0-9][a-z0-9._-]{0,79}$` }) as const;
const idList = (prefix: string, maxItems = 10_000, minItems = 0) =>
  ({ type: 'array', minItems, maxItems, uniqueItems: true, items: id(prefix) }) as const;
const text = {
  type: 'string',
  minLength: 1,
  maxLength: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxTextLength,
} as const;
const textList = (maxItems = 200) =>
  ({ type: 'array', maxItems, uniqueItems: true, items: text }) as const;

export const commercialDocumentMapSchemaV1 = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://compra-car.local/schemas/CommercialDocumentMap-1.json',
  title: 'CommercialDocumentMap/1',
  type: 'object',
  additionalProperties: false,
  required: [
    'schemaVersion',
    'documentCount',
    'pageCount',
    'documents',
    'pages',
    'contentBlocks',
    'sections',
    'tables',
    'notes',
    'entityHints',
    'contextEdges',
  ],
  properties: {
    schemaVersion: { const: COMMERCIAL_DOCUMENT_MAP_SCHEMA_VERSION },
    documentCount: { type: 'integer', minimum: 1, maximum: 20 },
    pageCount: { type: 'integer', minimum: 1, maximum: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxPages },
    documents: {
      type: 'array',
      minItems: 1,
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxDocuments,
      items: { $ref: '#/$defs/document' },
    },
    pages: {
      type: 'array',
      minItems: 1,
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxPages,
      items: { $ref: '#/$defs/page' },
    },
    contentBlocks: {
      type: 'array',
      minItems: 1,
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxContentBlocks,
      items: { $ref: '#/$defs/contentBlock' },
    },
    sections: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxSections,
      items: { $ref: '#/$defs/section' },
    },
    tables: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxTables,
      items: { $ref: '#/$defs/table' },
    },
    notes: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxNotes,
      items: { $ref: '#/$defs/note' },
    },
    entityHints: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxEntityHints,
      items: { $ref: '#/$defs/entityHint' },
    },
    contextEdges: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_MAP_LIMITS.maxContextEdges,
      items: { $ref: '#/$defs/contextEdge' },
    },
  },
  $defs: {
    metadataHint: {
      type: 'object',
      additionalProperties: false,
      required: ['value', 'sourceBlockIds'],
      properties: { value: text, sourceBlockIds: idList('block', 100, 1) },
    },
    metadataHints: {
      type: 'array',
      maxItems: 50,
      items: { $ref: '#/$defs/metadataHint' },
    },
    document: {
      type: 'object',
      additionalProperties: false,
      required: [
        'documentId',
        'ordinal',
        'pageCount',
        'documentKindCandidate',
        'titleHints',
        'issuerHints',
        'competenceHints',
        'validityHints',
      ],
      properties: {
        documentId: id('document'),
        ordinal: { type: 'integer', minimum: 1, maximum: 20 },
        pageCount: { type: 'integer', minimum: 1, maximum: 10_000 },
        documentKindCandidate: { enum: COMMERCIAL_DOCUMENT_MAP_DOCUMENT_KINDS },
        titleHints: { $ref: '#/$defs/metadataHints' },
        issuerHints: { $ref: '#/$defs/metadataHints' },
        competenceHints: { $ref: '#/$defs/metadataHints' },
        validityHints: { $ref: '#/$defs/metadataHints' },
      },
    },
    contentBlock: {
      type: 'object',
      additionalProperties: false,
      required: ['contentBlockId', 'documentId', 'pageId', 'blockKind'],
      properties: {
        contentBlockId: id('block'),
        documentId: id('document'),
        pageId: id('page'),
        blockKind: { enum: ['HEADING', 'BODY', 'TABLE_REGION', 'NOTE_REGION', 'OTHER'] },
        label: text,
      },
    },
    page: {
      type: 'object',
      additionalProperties: false,
      required: [
        'pageId',
        'documentId',
        'pageNumber',
        'role',
        'sectionIds',
        'tableIds',
        'noteIds',
        'entityHintIds',
        'contextEdgeIds',
        'contentBlockIds',
      ],
      properties: {
        pageId: id('page'),
        documentId: id('document'),
        pageNumber: { type: 'integer', minimum: 1, maximum: 10_000 },
        role: { enum: COMMERCIAL_DOCUMENT_PAGE_ROLES },
        sectionIds: idList('section', 200),
        tableIds: idList('table', 200),
        noteIds: idList('note', 500),
        entityHintIds: idList('hint', 500),
        contextEdgeIds: idList('edge', 500),
        contentBlockIds: idList('block', 2_000, 1),
      },
    },
    section: {
      type: 'object',
      additionalProperties: false,
      required: [
        'sectionId',
        'documentId',
        'semanticRole',
        'pageIds',
        'entityHintIds',
        'sourceBlockIds',
      ],
      properties: {
        sectionId: id('section'),
        documentId: id('document'),
        titleHint: text,
        semanticRole: { enum: COMMERCIAL_DOCUMENT_SECTION_ROLES },
        pageIds: idList('page', 1_000, 1),
        parentSectionId: id('section'),
        entityHintIds: idList('hint', 1_000),
        sourceBlockIds: idList('block', 5_000, 1),
      },
    },
    tableSegment: {
      type: 'object',
      additionalProperties: false,
      required: ['pageId', 'position', 'inheritedHeaderBlockIds', 'sourceBlockIds'],
      properties: {
        pageId: id('page'),
        position: { enum: ['START', 'CONTINUE', 'END', 'WHOLE'] },
        inheritedHeaderBlockIds: idList('block', 200),
        sourceBlockIds: idList('block', 2_000, 1),
      },
    },
    table: {
      type: 'object',
      additionalProperties: false,
      required: [
        'tableId',
        'documentId',
        'pageIds',
        'headerBlockIds',
        'segments',
        'columnHeaderLabels',
        'entityHintIds',
        'footnoteNoteIds',
        'contextEdgeIds',
        'sourceBlockIds',
      ],
      properties: {
        tableId: id('table'),
        documentId: id('document'),
        titleHint: text,
        pageIds: idList('page', 1_000, 1),
        headerBlockIds: idList('block', 500, 1),
        segments: {
          type: 'array',
          minItems: 1,
          maxItems: 1_000,
          items: { $ref: '#/$defs/tableSegment' },
        },
        approximateRowCount: { type: 'integer', minimum: 0, maximum: 1_000_000 },
        columnHeaderLabels: textList(200),
        entityHintIds: idList('hint', 2_000),
        footnoteNoteIds: idList('note', 1_000),
        contextEdgeIds: idList('edge', 2_000),
        sourceBlockIds: idList('block', 10_000, 1),
      },
    },
    note: {
      type: 'object',
      additionalProperties: false,
      required: [
        'noteId',
        'documentId',
        'pageId',
        'noteKind',
        'relevantForExtraction',
        'sectionIds',
        'tableIds',
        'sourceBlockIds',
      ],
      properties: {
        noteId: id('note'),
        documentId: id('document'),
        pageId: id('page'),
        noteKind: { enum: COMMERCIAL_DOCUMENT_NOTE_KINDS },
        relevantForExtraction: { type: 'boolean' },
        sectionIds: idList('section', 200),
        tableIds: idList('table', 200),
        sourceBlockIds: idList('block', 500, 1),
      },
    },
    entityHint: {
      type: 'object',
      additionalProperties: false,
      required: ['entityHintId', 'documentId', 'hintKind', 'value', 'sourceBlockIds'],
      properties: {
        entityHintId: id('hint'),
        documentId: id('document'),
        hintKind: { enum: COMMERCIAL_DOCUMENT_ENTITY_HINT_KINDS },
        value: text,
        sourceBlockIds: idList('block', 500, 1),
      },
    },
    mapRef: {
      type: 'object',
      additionalProperties: false,
      required: ['refType', 'refId'],
      properties: {
        refType: { enum: ['PAGE', 'CONTENT_BLOCK', 'SECTION', 'TABLE', 'NOTE'] },
        refId: { type: 'string', minLength: 1, maxLength: 86 },
      },
    },
    contextEdge: {
      type: 'object',
      additionalProperties: false,
      required: ['contextEdgeId', 'relation', 'from', 'to', 'reason'],
      properties: {
        contextEdgeId: id('edge'),
        relation: { enum: COMMERCIAL_DOCUMENT_CONTEXT_RELATIONS },
        from: { $ref: '#/$defs/mapRef' },
        to: { $ref: '#/$defs/mapRef' },
        reason: text,
      },
    },
  },
} as const;

const unitIdLists = {
  primaryPageIds: idList('page', COMMERCIAL_EXTRACTION_UNIT_LIMITS.maxPagesPerUnit, 1),
  contextPageIds: idList('page', COMMERCIAL_EXTRACTION_UNIT_LIMITS.maxContextPagesPerUnit),
  primaryContentBlockIds: idList('block', 10_000, 1),
  contextContentBlockIds: idList('block', 10_000),
  sectionIds: idList('section', 1_000),
  tableIds: idList('table', COMMERCIAL_EXTRACTION_UNIT_LIMITS.maxTablesPerUnit),
  noteIds: idList('note', 4_000),
  entityHintIds: idList('hint', 5_000),
} as const;

export const commercialExtractionUnitPlanSchemaV1 = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://compra-car.local/schemas/CommercialExtractionUnitPlan-1.json',
  title: 'CommercialExtractionUnitPlan/1',
  type: 'object',
  additionalProperties: false,
  required: ['schemaVersion', 'sourceMapSchemaVersion', 'units', 'coverage'],
  properties: {
    schemaVersion: { const: COMMERCIAL_EXTRACTION_UNIT_PLAN_SCHEMA_VERSION },
    sourceMapSchemaVersion: { const: COMMERCIAL_DOCUMENT_MAP_SCHEMA_VERSION },
    units: {
      type: 'array',
      minItems: 1,
      maxItems: COMMERCIAL_EXTRACTION_UNIT_LIMITS.maxUnits,
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'unitId',
          'unitType',
          'ordinal',
          'documentId',
          ...Object.keys(unitIdLists),
          'reason',
          'overlaps',
        ],
        properties: {
          unitId: id('unit'),
          unitType: { enum: COMMERCIAL_EXTRACTION_UNIT_TYPES },
          ordinal: { type: 'integer', minimum: 1, maximum: 1_000 },
          documentId: id('document'),
          ...unitIdLists,
          expectedTableRows: { type: 'integer', minimum: 0, maximum: 1_000_000 },
          logicalTableId: id('table'),
          partition: {
            type: 'object',
            additionalProperties: false,
            required: ['index', 'count'],
            properties: {
              index: { type: 'integer', minimum: 1, maximum: 1_000 },
              count: { type: 'integer', minimum: 2, maximum: 1_000 },
            },
          },
          reason: text,
          overlaps: {
            type: 'array',
            maxItems: 10_000,
            items: {
              type: 'object',
              additionalProperties: false,
              required: ['refType', 'refId', 'usage', 'reason'],
              properties: {
                refType: { enum: ['PAGE', 'CONTENT_BLOCK', 'NOTE'] },
                refId: { type: 'string', minLength: 1, maxLength: 86 },
                usage: { enum: ['CONTEXT_ONLY', 'PARTITION_PRIMARY'] },
                reason: {
                  enum: [
                    'INHERITED_HEADER',
                    'SHARED_NOTE',
                    'DOCUMENT_RULE',
                    'SECTION_CONTEXT',
                    'TABLE_PARTITION',
                    'CONTEXT_EDGE',
                  ],
                },
              },
            },
          },
        },
      },
    },
    coverage: {
      type: 'object',
      additionalProperties: false,
      required: [
        'allPagesClassified',
        'assignedPageIds',
        'assignedSectionIds',
        'assignedTableIds',
        'reachableNoteIds',
        'assignedPrimaryContentBlockIds',
        'orphanPageIds',
        'orphanSectionIds',
        'orphanTableIds',
        'unreachableNoteIds',
        'orphanContentBlockIds',
      ],
      properties: {
        allPagesClassified: { type: 'boolean' },
        assignedPageIds: idList('page'),
        assignedSectionIds: idList('section'),
        assignedTableIds: idList('table'),
        reachableNoteIds: idList('note'),
        assignedPrimaryContentBlockIds: idList('block'),
        orphanPageIds: idList('page'),
        orphanSectionIds: idList('section'),
        orphanTableIds: idList('table'),
        unreachableNoteIds: idList('note'),
        orphanContentBlockIds: idList('block'),
      },
    },
  },
} as const;
