import {
  COMMERCIAL_DOCUMENT_BLOCK_TYPES,
  COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS,
  COMMERCIAL_DOCUMENT_FACT_TYPES,
  COMMERCIAL_DOCUMENT_KINDS,
  COMMERCIAL_DOCUMENT_RELATION_TYPES,
  COMMERCIAL_DOCUMENT_SCOPE_TYPES,
  COMMERCIAL_DOCUMENT_EXTRACTION_SCHEMA_VERSION,
} from './commercial-document-extraction';

const { maxExcerptLength, maxTextLength } = COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS;
const localId = (prefix: string) =>
  ({
    type: 'string',
    pattern: `^${prefix}-[a-z0-9][a-z0-9._-]{0,63}$`,
  }) as const;
const shortText = { type: 'string', minLength: 1, maxLength: maxTextLength } as const;
const stringList = (maxItems = 500) =>
  ({
    type: 'array',
    maxItems,
    uniqueItems: true,
    items: shortText,
  }) as const;
const idList = (prefix: string, maxItems = 2_000, minItems = 0) =>
  ({
    type: 'array',
    minItems,
    maxItems,
    uniqueItems: true,
    items: localId(prefix),
  }) as const;

export const commercialDocumentExtractionSchemaV1 = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://compra-car.local/schemas/CommercialDocumentExtraction-1.json',
  title: 'CommercialDocumentExtraction/1',
  type: 'object',
  additionalProperties: false,
  required: [
    'schemaVersion',
    'documents',
    'blocks',
    'tables',
    'vehicleIdentities',
    'facts',
    'scopes',
    'composition',
    'coverage',
  ],
  properties: {
    schemaVersion: { const: COMMERCIAL_DOCUMENT_EXTRACTION_SCHEMA_VERSION },
    documents: {
      type: 'array',
      minItems: 1,
      maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxDocuments,
      items: { $ref: '#/$defs/sourceDocument' },
    },
    blocks: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxBlocks,
      items: { $ref: '#/$defs/sourceBlock' },
    },
    tables: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxTables,
      items: { $ref: '#/$defs/table' },
    },
    vehicleIdentities: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxVehicleIdentities,
      items: { $ref: '#/$defs/vehicleIdentity' },
    },
    facts: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxFacts,
      items: { $ref: '#/$defs/fact' },
    },
    scopes: {
      type: 'array',
      maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxScopes,
      items: { $ref: '#/$defs/scope' },
    },
    composition: { $ref: '#/$defs/composition' },
    coverage: { $ref: '#/$defs/coverage' },
  },
  $defs: {
    confidence: {
      type: 'object',
      additionalProperties: false,
      required: ['score', 'ambiguous', 'requiresReview', 'reasons'],
      properties: {
        score: { type: 'integer', minimum: 0, maximum: 100 },
        ambiguous: { type: 'boolean' },
        requiresReview: { type: 'boolean' },
        reasons: stringList(50),
      },
    },
    evidence: {
      type: 'object',
      additionalProperties: false,
      required: ['blockIds'],
      properties: {
        blockIds: idList('block', 100, 1),
        tableId: localId('table'),
        rowId: localId('row'),
        excerpt: { type: 'string', minLength: 1, maxLength: maxExcerptLength },
      },
    },
    textCandidate: {
      type: 'object',
      additionalProperties: false,
      required: ['value', 'evidence', 'confidence'],
      properties: {
        value: shortText,
        evidence: { $ref: '#/$defs/evidence' },
        confidence: { $ref: '#/$defs/confidence' },
      },
    },
    validityCandidate: {
      type: 'object',
      additionalProperties: false,
      required: ['rawText', 'evidence', 'confidence'],
      properties: {
        startsOn: { type: 'string', format: 'date' },
        endsOn: { type: 'string', format: 'date' },
        rawText: shortText,
        evidence: { $ref: '#/$defs/evidence' },
        confidence: { $ref: '#/$defs/confidence' },
      },
    },
    sourceDocument: {
      type: 'object',
      additionalProperties: false,
      required: [
        'documentId',
        'ordinal',
        'pageCount',
        'documentKind',
        'competenceCandidates',
        'validityCandidates',
        'notes',
      ],
      properties: {
        documentId: localId('document'),
        ordinal: { type: 'integer', minimum: 1, maximum: 20 },
        pageCount: { type: 'integer', minimum: 1, maximum: 10_000 },
        documentKind: { enum: COMMERCIAL_DOCUMENT_KINDS },
        competenceCandidates: {
          type: 'array',
          maxItems: 50,
          items: { $ref: '#/$defs/textCandidate' },
        },
        validityCandidates: {
          type: 'array',
          maxItems: 50,
          items: { $ref: '#/$defs/validityCandidate' },
        },
        notes: {
          type: 'array',
          maxItems: 200,
          items: { $ref: '#/$defs/textCandidate' },
        },
      },
    },
    region: {
      type: 'object',
      additionalProperties: false,
      required: ['x', 'y', 'width', 'height'],
      properties: {
        x: { type: 'number', minimum: 0, maximum: 1 },
        y: { type: 'number', minimum: 0, maximum: 1 },
        width: { type: 'number', exclusiveMinimum: 0, maximum: 1 },
        height: { type: 'number', exclusiveMinimum: 0, maximum: 1 },
      },
    },
    sourceBlock: {
      type: 'object',
      additionalProperties: false,
      required: ['blockId', 'documentId', 'page', 'blockType', 'excerpt'],
      properties: {
        blockId: localId('block'),
        documentId: localId('document'),
        page: { type: 'integer', minimum: 1, maximum: 10_000 },
        blockType: { enum: COMMERCIAL_DOCUMENT_BLOCK_TYPES },
        section: shortText,
        title: shortText,
        excerpt: { type: 'string', minLength: 1, maxLength: maxExcerptLength },
        region: { $ref: '#/$defs/region' },
        tableId: localId('table'),
        rowId: localId('row'),
      },
    },
    tableColumn: {
      type: 'object',
      additionalProperties: false,
      required: ['columnId', 'header', 'inherited'],
      properties: {
        columnId: localId('column'),
        header: shortText,
        inherited: { type: 'boolean' },
      },
    },
    tableCell: {
      type: 'object',
      additionalProperties: false,
      required: ['columnId', 'text'],
      properties: { columnId: localId('column'), text: shortText },
    },
    tableRow: {
      type: 'object',
      additionalProperties: false,
      required: ['rowId', 'ordinal', 'page', 'cells', 'sourceBlockIds'],
      properties: {
        rowId: localId('row'),
        ordinal: { type: 'integer', minimum: 1, maximum: 100_000 },
        page: { type: 'integer', minimum: 1, maximum: 10_000 },
        cells: { type: 'array', minItems: 1, maxItems: 200, items: { $ref: '#/$defs/tableCell' } },
        sourceBlockIds: idList('block', 100, 1),
      },
    },
    tableSegment: {
      type: 'object',
      additionalProperties: false,
      required: ['page', 'sourceBlockIds'],
      properties: {
        page: { type: 'integer', minimum: 1, maximum: 10_000 },
        sourceBlockIds: idList('block', 100, 1),
        inheritsHeadersFromPage: { type: 'integer', minimum: 1, maximum: 10_000 },
      },
    },
    tableContinuation: {
      type: 'object',
      additionalProperties: false,
      required: ['continuedAcrossPages', 'inheritedHeaderBlockIds', 'segments'],
      properties: {
        continuedAcrossPages: { type: 'boolean' },
        inheritedHeaderBlockIds: idList('block', 100),
        segments: {
          type: 'array',
          minItems: 1,
          maxItems: 1_000,
          items: { $ref: '#/$defs/tableSegment' },
        },
      },
    },
    table: {
      type: 'object',
      additionalProperties: false,
      required: [
        'tableId',
        'documentId',
        'pages',
        'headerContext',
        'columns',
        'rows',
        'sourceBlockIds',
        'footnoteBlockIds',
        'continuation',
      ],
      properties: {
        tableId: localId('table'),
        documentId: localId('document'),
        pages: {
          type: 'array',
          minItems: 1,
          maxItems: 1_000,
          uniqueItems: true,
          items: { type: 'integer', minimum: 1, maximum: 10_000 },
        },
        title: shortText,
        headerContext: shortText,
        columns: {
          type: 'array',
          minItems: 1,
          maxItems: 200,
          items: { $ref: '#/$defs/tableColumn' },
        },
        rows: {
          type: 'array',
          maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxRowsPerTable,
          items: { $ref: '#/$defs/tableRow' },
        },
        sourceBlockIds: idList('block', 2_000, 1),
        footnoteBlockIds: idList('block', 500),
        continuation: { $ref: '#/$defs/tableContinuation' },
      },
    },
    vehicleIdentity: {
      type: 'object',
      additionalProperties: false,
      required: ['vehicleIdentityId', 'brand', 'model', 'evidence', 'confidence'],
      properties: {
        vehicleIdentityId: localId('vehicle'),
        brand: shortText,
        model: shortText,
        version: shortText,
        productionYear: { type: 'integer', minimum: 1886, maximum: 2100 },
        modelYear: { type: 'integer', minimum: 1886, maximum: 2100 },
        rawYearText: { type: 'string', minLength: 1, maxLength: 100 },
        evidence: { $ref: '#/$defs/evidence' },
        confidence: { $ref: '#/$defs/confidence' },
      },
    },
    moneyValue: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'amount', 'currency'],
      properties: {
        kind: { const: 'money' },
        amount: { type: 'string', pattern: '^(?:0|[1-9]\\d{0,11})(?:\\.\\d{1,2})?$' },
        currency: { type: 'string', pattern: '^[A-Z]{3}$' },
        rawText: shortText,
      },
    },
    percentageValue: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'percentage'],
      properties: {
        kind: { const: 'percentage' },
        percentage: { type: 'string', pattern: '^(?:0|[1-9]\\d{0,2})(?:\\.\\d{1,4})?$' },
        rawText: shortText,
      },
    },
    quantityValue: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'amount', 'unit'],
      properties: {
        kind: { const: 'quantity' },
        amount: { type: 'string', pattern: '^-?(?:0|[1-9]\\d{0,11})(?:\\.\\d{1,4})?$' },
        unit: { type: 'string', minLength: 1, maxLength: 50 },
        rawText: shortText,
      },
    },
    textValue: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'text'],
      properties: { kind: { const: 'text' }, text: shortText },
    },
    booleanValue: {
      type: 'object',
      additionalProperties: false,
      required: ['kind', 'value'],
      properties: { kind: { const: 'boolean' }, value: { type: 'boolean' }, rawText: shortText },
    },
    factValidity: {
      type: 'object',
      additionalProperties: false,
      minProperties: 1,
      properties: {
        startsOn: { type: 'string', format: 'date' },
        endsOn: { type: 'string', format: 'date' },
        rawText: shortText,
      },
    },
    fact: {
      type: 'object',
      additionalProperties: false,
      required: [
        'factId',
        'factType',
        'value',
        'eligibility',
        'restrictions',
        'scopeIds',
        'evidence',
        'confidence',
      ],
      properties: {
        factId: localId('fact'),
        factType: { enum: COMMERCIAL_DOCUMENT_FACT_TYPES },
        rawLabel: shortText,
        value: {
          oneOf: [
            { $ref: '#/$defs/moneyValue' },
            { $ref: '#/$defs/percentageValue' },
            { $ref: '#/$defs/quantityValue' },
            { $ref: '#/$defs/textValue' },
            { $ref: '#/$defs/booleanValue' },
          ],
        },
        channel: shortText,
        eligibility: stringList(100),
        restrictions: stringList(100),
        validity: { $ref: '#/$defs/factValidity' },
        scopeIds: idList('scope', 500, 1),
        evidence: { $ref: '#/$defs/evidence' },
        confidence: { $ref: '#/$defs/confidence' },
      },
    },
    scopeSelector: {
      type: 'object',
      additionalProperties: false,
      properties: {
        documentIds: idList('document', 20),
        brandLines: stringList(500),
        models: stringList(2_000),
        versions: stringList(2_000),
        vehicleIdentityIds: idList('vehicle', 2_000),
        channels: stringList(500),
        groupIds: idList('group', 2_000),
      },
    },
    scope: {
      type: 'object',
      additionalProperties: false,
      required: [
        'scopeId',
        'scopeType',
        'selector',
        'exclusions',
        'evidenceBlockIds',
        'ambiguous',
        'requiresReview',
      ],
      properties: {
        scopeId: localId('scope'),
        scopeType: { enum: COMMERCIAL_DOCUMENT_SCOPE_TYPES },
        selector: { $ref: '#/$defs/scopeSelector' },
        exclusions: { $ref: '#/$defs/scopeSelector' },
        evidenceBlockIds: idList('block', 500, 1),
        ambiguous: { type: 'boolean' },
        requiresReview: { type: 'boolean' },
      },
    },
    compositionGroup: {
      type: 'object',
      additionalProperties: false,
      required: ['groupId', 'groupType', 'memberFactIds', 'sharedFactIds', 'scopeIds'],
      properties: {
        groupId: localId('group'),
        groupType: { enum: ['ALTERNATIVE', 'CUMULATIVE'] },
        memberFactIds: idList('fact', 2_000, 2),
        sharedFactIds: idList('fact', 2_000),
        scopeIds: idList('scope', 500, 1),
        parentGroupId: localId('group'),
      },
    },
    compositionRelation: {
      type: 'object',
      additionalProperties: false,
      required: [
        'relationId',
        'relationType',
        'factIds',
        'groupIds',
        'scopeIds',
        'evidenceBlockIds',
      ],
      properties: {
        relationId: localId('relation'),
        relationType: { enum: COMMERCIAL_DOCUMENT_RELATION_TYPES },
        factIds: idList('fact', 2_000, 1),
        groupIds: idList('group', 2_000),
        scopeIds: idList('scope', 500),
        evidenceBlockIds: idList('block', 500, 1),
      },
    },
    composition: {
      type: 'object',
      additionalProperties: false,
      required: ['groups', 'relationships'],
      properties: {
        groups: {
          type: 'array',
          maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxGroups,
          items: { $ref: '#/$defs/compositionGroup' },
        },
        relationships: {
          type: 'array',
          maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxRelationships,
          items: { $ref: '#/$defs/compositionRelation' },
        },
      },
    },
    extractionUnit: {
      type: 'object',
      additionalProperties: false,
      required: ['unitId', 'status', 'sourceBlockIds', 'extractedItemCount'],
      properties: {
        unitId: localId('unit'),
        status: { enum: ['expected', 'complete', 'incomplete', 'ambiguous'] },
        sourceBlockIds: idList('block', 2_000, 1),
        expectedItemCount: { type: 'integer', minimum: 0, maximum: 1_000_000 },
        extractedItemCount: { type: 'integer', minimum: 0, maximum: 1_000_000 },
      },
    },
    coverageGap: {
      type: 'object',
      additionalProperties: false,
      required: ['gapId', 'gapType', 'message'],
      properties: {
        gapId: localId('gap'),
        gapType: {
          enum: [
            'INCOMPLETE_BLOCK',
            'UNRESOLVED_TABLE_ROW',
            'UNRESOLVED_SCOPE',
            'MISSING_VEHICLE',
            'AMBIGUITY',
            'OTHER',
          ],
        },
        message: shortText,
        unitId: localId('unit'),
        blockId: localId('block'),
        tableId: localId('table'),
        rowId: localId('row'),
        scopeId: localId('scope'),
      },
    },
    unresolvedTableRow: {
      type: 'object',
      additionalProperties: false,
      required: ['tableId', 'rowId'],
      properties: { tableId: localId('table'), rowId: localId('row') },
    },
    coverage: {
      type: 'object',
      additionalProperties: false,
      required: [
        'status',
        'expectedUnitCount',
        'completedUnitCount',
        'extractedVehicleCount',
        'expectedFamilies',
        'extractedFamilies',
        'units',
        'gaps',
        'incompleteBlockIds',
        'unresolvedTableRows',
        'unresolvedScopeIds',
      ],
      properties: {
        status: { enum: ['complete', 'partial', 'ambiguous'] },
        expectedUnitCount: { type: 'integer', minimum: 0, maximum: 1_000_000 },
        completedUnitCount: { type: 'integer', minimum: 0, maximum: 1_000_000 },
        expectedVehicleCount: { type: 'integer', minimum: 0, maximum: 1_000_000 },
        extractedVehicleCount: { type: 'integer', minimum: 0, maximum: 1_000_000 },
        expectedFamilies: stringList(10_000),
        extractedFamilies: stringList(10_000),
        units: {
          type: 'array',
          maxItems: COMMERCIAL_DOCUMENT_EXTRACTION_LIMITS.maxExtractionUnits,
          items: { $ref: '#/$defs/extractionUnit' },
        },
        gaps: { type: 'array', maxItems: 10_000, items: { $ref: '#/$defs/coverageGap' } },
        incompleteBlockIds: idList('block', 2_000),
        unresolvedTableRows: {
          type: 'array',
          maxItems: 10_000,
          items: { $ref: '#/$defs/unresolvedTableRow' },
        },
        unresolvedScopeIds: idList('scope', 5_000),
      },
    },
  },
} as const;
