import type { SpecSourceTarget, SpecObservation, SpecApplicability } from './spec-source-types';
export type DocumentIntelligenceTarget = Omit<SpecSourceTarget, 'modelYear'> & {
  readonly modelYear: number | null;
};
export const DOCUMENT_SOURCE_CLASSES = [
  'TECHNICAL_SHEET',
  'OFFICIAL_MODEL_PAGE',
  'OFFICIAL_CONFIGURATOR',
  'OFFICIAL_STRUCTURED_DATA',
  'OFFICIAL_TECHNICAL_PAGE',
  'OWNER_MANUAL',
  'DEALER',
  'PRESS',
  'MEDIA_REVIEW',
  'WEBMOTORS',
  'FORUM',
  'AGGREGATOR',
  'THIRD_PARTY_DATABASE',
  'UNKNOWN',
] as const;
export type DocumentSourceClass = (typeof DOCUMENT_SOURCE_CLASSES)[number];
export interface DocumentScope {
  model: string | null;
  version: string | null;
  modelYear: number | null;
}
export interface DocumentBlock {
  locator: string;
  type: 'PAGE' | 'SECTION' | 'TABLE' | 'CARD' | 'JSON' | 'TEXT';
  text: string;
  parentLocator: string | null;
  scope: DocumentScope;
  heading: string | null;
  page?: number;
  /** Reading-order text supplied by PDF.js, not generated by a model. */
  readingText?: string;
  tableRows?: readonly (readonly string[])[];
}
export interface DocumentIntelligenceSource {
  format:
    'PDF_FILE' | 'HTML_DOCUMENT' | 'STRUCTURED_HTML' | 'STRUCTURED_JSON' | 'CONFIGURATOR_SNAPSHOT';
  sourceClass: DocumentSourceClass;
  official: boolean;
  reference: string;
  finalUrl: string;
  sourceHash: string;
  contentType: string;
  byteSize: number;
  filename?: string;
  bytes?: Uint8Array;
  title: string | null;
  h1: readonly string[];
  blocks: readonly DocumentBlock[];
  truncated: boolean;
  /** Only a lossless upstream adapter may set this, never the model. */
  losslessStructured?: boolean;
}
export type EvidenceType = 'TEXT_SPAN' | 'TEXT_WINDOW' | 'STRUCTURAL_CONTEXT' | 'LAYOUT_CONTEXT';
export type GroundingQuality =
  'EXACT_TEXT' | 'NORMALIZED_TEXT' | 'BOUNDED_WINDOW' | 'STRUCTURAL_CONTEXT' | 'NOT_GROUNDED';
export interface DocumentEvidence {
  /** Optional only for replay compatibility with v1. New model schema requires these fields. */
  page?: number | null;
  evidenceType?: EvidenceType;
  sectionHeading?: string | null;
  parentContext?: string | null;
  sourceHash: string;
  locator: string;
  quote: string;
}
export interface DocumentApplicability extends DocumentScope {
  versionBinding: SpecApplicability['versionBinding'];
  yearBinding: SpecApplicability['yearBinding'];
}
export interface TechnicalSheetItem {
  sourceLabel: string;
  rawValue: string | null;
  rawUnit: string | null;
  kind: 'VALUE' | 'PRESENT' | 'EXPLICIT_ABSENT' | 'TEXT' | 'COMPOSITE' | 'OPTION';
  present: boolean | null;
  subgroup: string | null;
  parentGroup: string | null;
  rawText: string;
  evidence: DocumentEvidence[];
  applicability: DocumentApplicability;
}
export interface TechnicalSheetContent {
  documentIdentity: {
    brand: string | null;
    model: string | null;
    version: string | null;
    modelYear: number | null;
    evidence: DocumentEvidence[];
  };
  sections: {
    sourceHeading: string;
    normalizedHeading: string | null;
    applicability: DocumentApplicability;
    items: TechnicalSheetItem[];
  }[];
}
export interface DocumentUsage {
  inputTokens: number;
  cachedInputTokens: number;
  outputTokens: number;
  reasoningTokens: number;
}
export interface DocumentRequestAudit {
  model: string;
  responseId: string;
  extractionPass: 'PRIMARY' | 'REPAIR';
  usage: DocumentUsage;
  durationMs: number;
  countedInputTokens: number;
  maximumCostUsd: number;
  actualCostUsd: number;
}
export interface TechnicalSheetExtraction extends TechnicalSheetContent {
  extractionMetadata: DocumentRequestAudit & { sourceHash: string };
}
export interface ExtractionIssue {
  code: string;
  path: string;
  severity: 'REPAIR' | 'REVIEW' | 'WARNING';
  detail: string;
}
export interface SourceStructureCensus {
  pageCount: number;
  headings: string[];
  markerCount: number;
  rowCount: number;
  tableCount: number;
  cardCount: number;
  listCount: number;
  jsonCount: number;
  blockCount: number;
  textCharacters: number;
}
export interface ExtractionValidation {
  grounding?: { locator: string; quote: string; quality: GroundingQuality }[];
  census?: SourceStructureCensus;
  completeness?: { confidence: 'HIGH' | 'MEDIUM' | 'LOW'; reasons: string[] };
  status: 'PASS' | 'REPAIR_REQUIRED' | 'HUMAN_REVIEW_REQUIRED';
  issues: ExtractionIssue[];
  inventory: TechnicalSheetContent | null;
  observations: SpecObservation[];
}
export interface DocumentIntelligenceOptions {
  hardCostCapUsd?: number;
  maxRepairCalls?: 0 | 1;
  maxOutputTokens?: number;
}
export interface DocumentIntelligenceResult {
  status: 'PASS' | 'HUMAN_REVIEW_REQUIRED';
  reason: string | null;
  strategy: 'DOCUMENT_INTELLIGENCE' | 'DETERMINISTIC_STRUCTURED' | 'REJECT_SOURCE';
  target: DocumentIntelligenceTarget;
  source: Omit<DocumentIntelligenceSource, 'bytes'>;
  extraction: TechnicalSheetExtraction | null;
  observations: SpecObservation[];
  validations: ExtractionValidation[];
  requests: DocumentRequestAudit[];
  totalCostUsd: number;
  durationMs: number;
  softCostWarning: boolean;
}
export interface DocumentIntelligenceProvider {
  extract(
    source: DocumentIntelligenceSource,
    target: DocumentIntelligenceTarget,
    options?: DocumentIntelligenceOptions,
  ): Promise<DocumentIntelligenceResult>;
}
export interface DocumentModelRequest {
  model: string;
  source: DocumentIntelligenceSource;
  target: DocumentIntelligenceTarget;
  repair?: { proposal: unknown; issues: readonly ExtractionIssue[] };
}
export interface DocumentModelResponse {
  content: unknown;
  model: string;
  responseId: string;
  usage: DocumentUsage;
  durationMs: number;
  completed: boolean;
}
export interface DocumentModelTransport {
  count(request: DocumentModelRequest): Promise<number>;
  generate(request: DocumentModelRequest, maxOutputTokens: number): Promise<DocumentModelResponse>;
}
