import type { OfficialProductCandidate } from './new-product-check-types';
import type { AdministrativeVehicle } from '../admin/administrative-vehicle';
import { catalogMmvIdentityId } from './catalog-mmv-identity';
/** Offline capture 2506bcb5-7ff7-4529-bbd2-29b51efd5778: original 18 candidates.
 * Catalog is a reconstruction from the acceptance cases: 6 saved rows + 10 synthetic rows.
 * It is NOT a full snapshot of the original 51-row catalog. */
export const jeepCapturedMmvCandidates: readonly OfficialProductCandidate[] = [
  {
    brand: 'Jeep',
    model: 'Renegade',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'RENEGADE ALTITUDE T270 4X2',
    trim: 'Altitude',
    powertrainLabel: 'T270',
    engineDisplacement: 1.332,
    engineLabel: 'Motor T270 Turbo Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 6 marchas',
    drivetrain: '4X2',
    productionYear: null,
    modelYear: 2027,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/renegade/monte.html?campaign_id=49A&mvs=611&year=2027',
        title: 'Jeep | Monte o Seu Renegade',
        excerpt: 'RENEGADE ALTITUDE T270 4X2; MODEL YEAR 2027; câmbio automático de 6 marchas.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Renegade Turbo Flex: 1.332 cm³ e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Renegade',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'RENEGADE LONGITUDE T270 MHEV 4X2',
    trim: 'Longitude',
    powertrainLabel: 'T270 MHEV',
    engineDisplacement: 1.332,
    engineLabel: 'T270 Híbrido MHEV',
    propulsion: 'MHEV',
    transmission: 'Automático de 6 marchas',
    drivetrain: '4X2',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/renegade/monte.html?campaign_id=49A&mvs=611&year=2027',
        title: 'Jeep | Monte o Seu Renegade',
        excerpt: 'RENEGADE LONGITUDE T270 MHEV 4X2.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt:
          'Longitude e Sahara: T270 Híbrido MHEV, 1.332 cm³ e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Renegade',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'RENEGADE SAHARA T270 MHEV 4X2',
    trim: 'Sahara',
    powertrainLabel: 'T270 MHEV',
    engineDisplacement: 1.332,
    engineLabel: 'T270 Híbrido MHEV',
    propulsion: 'MHEV',
    transmission: 'Automático de 6 marchas',
    drivetrain: '4X2',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/renegade/monte.html?campaign_id=49A&mvs=611&year=2027',
        title: 'Jeep | Monte o Seu Renegade',
        excerpt: 'RENEGADE SAHARA T270 MHEV 4X2.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt:
          'Longitude e Sahara: T270 Híbrido MHEV, 1.332 cm³ e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Renegade',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'RENEGADE WILLYS T270 4X4',
    trim: 'Willys',
    powertrainLabel: 'T270',
    engineDisplacement: 1.332,
    engineLabel: 'T270 Turbo Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 6 marchas',
    drivetrain: '4X4',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/renegade/monte.html?campaign_id=49A&mvs=611&year=2027',
        title: 'Jeep | Monte o Seu Renegade',
        excerpt: 'RENEGADE WILLYS T270 4X4.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Willys: motor Turbo Flex, 1.332 cm³ e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Compass',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMPASS SPORT T270',
    trim: 'Sport',
    powertrainLabel: 'T270',
    engineDisplacement: 1.332,
    engineLabel: 'Motor Turbo Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 6 marchas',
    drivetrain: null,
    productionYear: null,
    modelYear: 2026,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/compass/monte.html?mvs=675CA21&year=2026',
        title: 'Monte o Seu Compass | Jeep',
        excerpt: 'COMPASS SPORT T270; Model Year 2026; câmbio automático de 6 marchas.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Compass Sport: Turbo Flex, 1.332 cm³ e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Compass',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMPASS LONGITUDE T270',
    trim: 'Longitude',
    powertrainLabel: 'T270',
    engineDisplacement: 1.332,
    engineLabel: 'Motor Turbo Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 6 marchas',
    drivetrain: null,
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/compass/monte.html?mvs=675CA21&year=2026',
        title: 'Monte o Seu Compass | Jeep',
        excerpt: 'COMPASS LONGITUDE T270.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Compass Longitude: Turbo Flex, 1.332 cm³ e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Compass',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMPASS SERIE S T270',
    trim: 'Serie S',
    powertrainLabel: 'T270',
    engineDisplacement: 1.332,
    engineLabel: 'Motor Turbo Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 6 marchas',
    drivetrain: null,
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/compass/monte.html?mvs=675CA21&year=2026',
        title: 'Monte o Seu Compass | Jeep',
        excerpt: 'COMPASS SERIE S T270.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Compass Série S: Turbo Flex, 1.332 cm³ e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Compass',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMPASS BLACKHAWK HURRICANE FLEX',
    trim: 'Blackhawk',
    powertrainLabel: 'Hurricane Flex',
    engineDisplacement: 1.995,
    engineLabel: 'Motor Turbo Hurricane Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 9 marchas',
    drivetrain: '4x4 com reduzida',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/compass/monte.html?mvs=675CA21&year=2026',
        title: 'Monte o Seu Compass | Jeep',
        excerpt: 'COMPASS BLACKHAWK HURRICANE FLEX.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt:
          'Blackhawk Flex: 1.995 cm³, automático de 9 velocidades e tração 4x4 com reduzida.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Commander',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMMANDER LONGITUDE T270 7L',
    trim: 'Longitude',
    powertrainLabel: 'T270',
    engineDisplacement: null,
    engineLabel: 'Motor Turbo Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 6 marchas',
    drivetrain: null,
    productionYear: null,
    modelYear: 2027,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/commander/monte.html?mvs=559&offerId=86&openFundingPlans=true&year=2023',
        title: 'Monte seu Commander | Jeep',
        excerpt: 'COMMANDER LONGITUDE T270 7L; MODEL YEAR 2027.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=04B&mvs=675&offerId=86&year=2025',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Commander Longitude: motor Turbo Flex e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Commander',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMMANDER LIMITED T270 MHEV',
    trim: 'Limited',
    powertrainLabel: 'T270 MHEV',
    engineDisplacement: null,
    engineLabel: 'T270 Híbrido MHEV',
    propulsion: 'MHEV',
    transmission: 'Automático de 6 marchas',
    drivetrain: '4x2',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/commander/monte.html?mvs=559&offerId=86&openFundingPlans=true&year=2023',
        title: 'Monte seu Commander | Jeep',
        excerpt: 'COMMANDER LIMITED T270 MHEV.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt:
          'Commander Limited: motor Híbrido MHEV, tração 4x2 e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Commander',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMMANDER OVERLAND T270 MHEV',
    trim: 'Overland',
    powertrainLabel: 'T270 MHEV',
    engineDisplacement: null,
    engineLabel: 'T270 Híbrido MHEV',
    propulsion: 'MHEV',
    transmission: 'Automático de 6 marchas',
    drivetrain: '4x2',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/commander/monte.html?mvs=559&offerId=86&openFundingPlans=true&year=2023',
        title: 'Monte seu Commander | Jeep',
        excerpt: 'COMMANDER OVERLAND T270 MHEV.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt:
          'Commander Overland: motor Híbrido MHEV, tração 4x2 e câmbio automático de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Commander',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMMANDER OVERLAND 2.2T DIESEL 4X4',
    trim: 'Overland',
    powertrainLabel: '2.2T Diesel',
    engineDisplacement: 2.184,
    engineLabel: 'Turbo Diesel 2.2L',
    propulsion: 'ICE',
    transmission: 'Automático de 9 marchas',
    drivetrain: '4X4',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/commander/monte.html?mvs=559&offerId=86&openFundingPlans=true&year=2023',
        title: 'Monte seu Commander | Jeep',
        excerpt: 'COMMANDER OVERLAND 2.2T DIESEL 4X4.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=04B&mvs=675&offerId=86&year=2025',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Overland 2.2L: 2.184 cm³, câmbio automático de 9 velocidades e tração 4x4.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Commander',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'COMMANDER BLACKHAWK HURRICANE 4X4 FLEX',
    trim: 'Blackhawk',
    powertrainLabel: 'Hurricane',
    engineDisplacement: 1.995,
    engineLabel: 'Motor Turbo Hurricane Flex',
    propulsion: 'ICE',
    transmission: 'Automático de 9 marchas',
    drivetrain: '4X4',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/commander/monte.html?mvs=559&offerId=86&openFundingPlans=true&year=2023',
        title: 'Monte seu Commander | Jeep',
        excerpt: 'COMMANDER BLACKHAWK HURRICANE 4X4 FLEX.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Commander Blackhawk: 1.995 cm³, câmbio automático de 9 velocidades e tração 4x4.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Avenger',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'AVENGER ALTITUDE T200 MHEV CVT',
    trim: 'Altitude',
    powertrainLabel: 'T200 MHEV',
    engineDisplacement: 0.99,
    engineLabel: 'T200 Turbo Híbrido MHEV Flex',
    propulsion: 'MHEV',
    transmission: 'CVT',
    drivetrain: null,
    productionYear: null,
    modelYear: null,
    confidence: 0.8,
    evidence: [
      {
        url: 'https://www.jeep.com.br/proprietarios/acessorios/acessorios.html?campaign_id=66A&mvs=611&year=2025',
        title: 'Catálogo de Acessórios | Jeep',
        excerpt: 'Versão: AVENGER ALTITUDE T200 MHEV CVT.',
        evidenceType: 'OTHER_OFFICIAL',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'Avenger: 990 cm³ e câmbio automático CVT de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Avenger',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'AVENGER LIMITED T200 MHEV CVT',
    trim: 'Limited',
    powertrainLabel: 'T200 MHEV',
    engineDisplacement: 0.99,
    engineLabel: 'T200 Turbo Híbrido MHEV Flex',
    propulsion: 'MHEV',
    transmission: 'CVT',
    drivetrain: null,
    productionYear: null,
    modelYear: null,
    confidence: 0.8,
    evidence: [
      {
        url: 'https://www.jeep.com.br/proprietarios/acessorios/acessorios.html?campaign_id=66A&mvs=611&year=2025',
        title: 'Catálogo de Acessórios | Jeep',
        excerpt: 'Versão: AVENGER LIMITED T200 MHEV CVT.',
        evidenceType: 'OTHER_OFFICIAL',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'T200 Turbo Híbrido MHEV Flex; Avenger com CVT de 6 velocidades.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Avenger',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'AVENGER LONGITUDE T200 MHEV CVT',
    trim: 'Longitude',
    powertrainLabel: 'T200 MHEV',
    engineDisplacement: 0.99,
    engineLabel: 'T200 Turbo Híbrido MHEV Flex',
    propulsion: 'MHEV',
    transmission: 'CVT',
    drivetrain: null,
    productionYear: null,
    modelYear: null,
    confidence: 0.8,
    evidence: [
      {
        url: 'https://www.jeep.com.br/proprietarios/acessorios/acessorios.html?campaign_id=66A&mvs=611&year=2025',
        title: 'Catálogo de Acessórios | Jeep',
        excerpt: 'Versão: AVENGER LONGITUDE T200 MHEV CVT.',
        evidenceType: 'OTHER_OFFICIAL',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=10B&mvs=671&year=2026',
        title: 'Motores Jeep | Jeep',
        excerpt: 'T200 Turbo Híbrido MHEV Flex; Avenger com 990 cm³.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Gladiator',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'GLADIATOR RUBICON',
    trim: 'Rubicon',
    powertrainLabel: '3.6 V6',
    engineDisplacement: 3.604,
    engineLabel: 'Motor 3.6L V6',
    propulsion: 'ICE',
    transmission: 'Automático de 8 velocidades',
    drivetrain: '4x4 com reduzida',
    productionYear: null,
    modelYear: null,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/gladiator/monte.html?app=true&bonusLovers=true&mvs=685&offerId=547619&year=2026',
        title: 'Monte seu Jeep Gladiator | Jeep',
        excerpt: 'GLADIATOR RUBICON; câmbio automático de 8 velocidades.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=04B&mvs=675&offerId=86&year=2025',
        title: 'Motores Jeep | Jeep',
        excerpt:
          'Gladiator Rubicon: 3.604 cm³, automático de 8 velocidades e tração 4x4 com reduzida.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
  {
    brand: 'Jeep',
    model: 'Wrangler',
    taxonomy: 'VARIANT',
    officialVersionLabel: 'Wrangler Rubicon 4X4',
    trim: 'Rubicon',
    powertrainLabel: null,
    engineDisplacement: 1.995,
    engineLabel: 'Motor 2.0 Turbo',
    propulsion: 'ICE',
    transmission: 'Automático de 8 velocidades',
    drivetrain: '4x4 Rock-Trac com reduzida',
    productionYear: null,
    modelYear: 2026,
    confidence: 0.95,
    evidence: [
      {
        url: 'https://www.jeep.com.br/wrangler/monte.html?campaign_id=66A&mvs=671&year=2026',
        title: 'Monte seu Wrangler | Jeep',
        excerpt: 'Wrangler Rubicon 4X4; Model Year 26; câmbio automático de 8 velocidades.',
        evidenceType: 'CONFIGURATOR',
      },
      {
        url: 'https://www.jeep.com.br/motores-jeep.html?campaign_id=04B&mvs=675&offerId=86&year=2025',
        title: 'Motores Jeep | Jeep',
        excerpt:
          'Rubicon: motor 2.0 Turbo, 1.995 cm³, automático de 8 velocidades e 4x4 Rock-Trac.',
        evidenceType: 'MODEL_PAGE',
      },
    ],
    extractionWarnings: [],
  },
];
export const jeepCapturedMmvCatalog: readonly AdministrativeVehicle[] = [
  {
    id: 'regression-0',
    brand: 'Jeep',
    model: 'Renegade',
    version: 'Altitude 1.3 TGDI AT',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-1',
    brand: 'Jeep',
    model: 'Renegade',
    version: 'Longitude 1.3 TGDI AT MHEV',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-2',
    brand: 'Jeep',
    model: 'Renegade',
    version: 'Sahara 1.3 TGDI AT MHEV',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-3',
    brand: 'Jeep',
    model: 'Renegade',
    version: 'Willys 1.3 TGDI AT 4x4',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-4',
    brand: 'Jeep',
    model: 'Compass',
    version: 'Sport 1.3 TGDI AT',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-5',
    brand: 'Jeep',
    model: 'Compass',
    version: 'Longitude 1.3 TGDI AT',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-6',
    brand: 'Jeep',
    model: 'Compass',
    version: 'Serie S 1.3 TGDI AT',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-7',
    brand: 'Jeep',
    model: 'Compass',
    version: 'Blackhawk 2.0 TGDI AT',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: '960',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Longitude 1.3 TGDI AT',
    modelYear: 2025,
    productionYear: 2025,
    isActive: true,
    isPublic: false,
  },
  {
    id: '996',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Longitude 1.3 TGDI AT',
    modelYear: 2026,
    productionYear: 2025,
    isActive: true,
    isPublic: false,
  },
  {
    id: '1064',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Longitude 1.3 TGDI AT',
    modelYear: 2026,
    productionYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: '1128',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Longitude 1.3 TGDI AT',
    modelYear: 2027,
    productionYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: '1129',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Limited 1.3 TGDI AT MHEV',
    modelYear: 2027,
    productionYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: '1130',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Overland 1.3 TGDI AT MHEV',
    modelYear: 2027,
    productionYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-11',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Overland 2.2 TD AT 4x4',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
  {
    id: 'regression-12',
    brand: 'Jeep',
    model: 'Commander',
    version: 'Blackhawk Hurricane 2.0 TGDI AT 4x4',
    productionYear: 2025,
    modelYear: 2026,
    isActive: true,
    isPublic: false,
  },
];
const expectedVersions = [
  'Altitude 1.3 TGDI AT',
  'Longitude 1.3 TGDI AT MHEV',
  'Sahara 1.3 TGDI AT MHEV',
  'Willys 1.3 TGDI AT 4x4',
  'Sport 1.3 TGDI AT',
  'Longitude 1.3 TGDI AT',
  'Serie S 1.3 TGDI AT',
  'Blackhawk 2.0 TGDI AT',
  'Longitude 1.3 TGDI AT',
  'Limited 1.3 TGDI AT MHEV',
  'Overland 1.3 TGDI AT MHEV',
  'Overland 2.2 TD AT 4x4',
  'Blackhawk Hurricane 2.0 TGDI AT 4x4',
];
export const jeepCapturedMmvExpectations = expectedVersions.map((version, index) => ({
  candidate: jeepCapturedMmvCandidates[index]!,
  mmvIdentityId: catalogMmvIdentityId({
    brand: 'Jeep',
    model: jeepCapturedMmvCandidates[index]!.model,
    version,
  }),
}));
