import { StyleSheet } from '@react-pdf/renderer';

export const comparisonPdfStyles = StyleSheet.create({
  page: {
    backgroundColor: '#020617',
    color: '#f1f5f9',
    fontFamily: 'Helvetica',
    paddingBottom: 24,
    paddingHorizontal: 27.5,
    paddingTop: 104,
  },
  header: {
    backgroundColor: '#020617',
    left: 27.5,
    position: 'absolute',
    top: 16,
    width: 540,
  },
  identityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 24,
    justifyContent: 'space-between',
  },
  brand: {
    color: '#22d3ee',
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  heading: {
    color: '#f1f5f9',
    fontSize: 11,
    fontWeight: 700,
  },
  mode: {
    color: '#94a3b8',
    fontSize: 7,
    marginTop: 2,
    textAlign: 'right',
  },
  columnHeader: {
    backgroundColor: '#0f172a',
    borderColor: '#334155',
    borderRadius: 5,
    borderWidth: 1,
    flexDirection: 'row',
    height: 58,
    overflow: 'hidden',
  },
  itemHeader: {
    borderRightColor: '#334155',
    borderRightWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  itemHeaderText: {
    color: '#94a3b8',
    fontSize: 7.5,
    fontWeight: 700,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  vehicleHeader: {
    borderRightColor: '#334155',
    borderRightWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  lastColumn: {
    borderRightWidth: 0,
  },
  vehicleRole: {
    color: '#64748b',
    fontSize: 5.5,
    fontWeight: 700,
    letterSpacing: 0.45,
    marginBottom: 3,
    textTransform: 'uppercase',
  },
  referenceRole: {
    color: '#67e8f9',
  },
  vehicleName: {
    color: '#f1f5f9',
    fontSize: 7.5,
    fontWeight: 700,
    lineHeight: 1.15,
    maxLines: 2,
  },
  referenceVehicle: {
    backgroundColor: '#0e2934',
  },
  table: {
    width: 540,
  },
  category: {
    backgroundColor: '#1e293b',
    borderBottomColor: '#334155',
    borderBottomWidth: 1,
    height: 20,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  categoryText: {
    color: '#cbd5e1',
    fontSize: 7,
    fontWeight: 700,
    letterSpacing: 0.65,
    textTransform: 'uppercase',
  },
  row: {
    backgroundColor: '#0f172a',
    borderBottomColor: '#1e293b',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 28,
  },
  itemCell: {
    borderRightColor: '#1e293b',
    borderRightWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  itemLabel: {
    color: '#e2e8f0',
    fontWeight: 700,
    lineHeight: 1,
    maxLines: 1,
  },
  valueCell: {
    alignItems: 'center',
    borderRightColor: '#1e293b',
    borderRightWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: 28,
    paddingHorizontal: 4,
    position: 'relative',
  },
  advantageCell: {
    backgroundColor: '#0e2934',
  },
  valueText: {
    color: '#cbd5e1',
    fontWeight: 700,
    maxLines: 1,
    textAlign: 'center',
  },
  presenceDot: {
    backgroundColor: '#f1f5f9',
    borderRadius: 2.5,
    height: 5,
    width: 5,
  },
  advantageIcon: {
    height: 10,
    position: 'absolute',
    right: 3,
    width: 10,
  },
});
