import { StyleSheet } from '@react-pdf/renderer';

export const comparisonPdfStyles = StyleSheet.create({
  page: {
    backgroundColor: '#FFFFFF',
    color: '#1A1D21',
    fontFamily: 'Helvetica',
    paddingBottom: 34,
    paddingHorizontal: 28,
    paddingTop: 150,
  },
  header: {
    backgroundColor: '#FFFFFF',
    left: 28,
    position: 'absolute',
    top: 22,
    zIndex: 10,
  },
  headerTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    height: 48,
    justifyContent: 'space-between',
  },
  brandSlot: {
    borderLeftColor: '#9ABCC8',
    borderLeftWidth: 4,
    paddingLeft: 8,
  },
  brand: {
    color: '#1A1D21',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  heading: {
    color: '#1A1D21',
    fontSize: 15,
    fontWeight: 700,
    marginTop: 3,
  },
  headerMeta: { alignItems: 'flex-end' },
  mode: { color: '#1A1D21', fontSize: 9, fontWeight: 700 },
  generatedAt: { color: '#62676E', fontSize: 8, marginTop: 3 },
  intro: { color: '#62676E', fontSize: 8.5, marginBottom: 7 },
  columnHeader: {
    backgroundColor: '#F1F3F4',
    borderBottomColor: '#1A1D21',
    borderBottomWidth: 1,
    borderTopColor: '#D8DCDF',
    borderTopWidth: 1,
    flexDirection: 'row',
    minHeight: 66,
  },
  itemHeader: { justifyContent: 'center', paddingHorizontal: 9 },
  itemHeaderText: {
    color: '#62676E',
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  vehicleHeader: {
    borderLeftColor: '#D8DCDF',
    borderLeftWidth: 1,
    justifyContent: 'center',
    paddingHorizontal: 7,
  },
  referenceVehicle: { backgroundColor: '#E9F1F4' },
  vehicleRole: {
    color: '#62676E',
    fontSize: 7.5,
    fontWeight: 700,
    letterSpacing: 0.45,
    marginBottom: 3,
    textTransform: 'uppercase',
  },
  referenceRole: { color: '#4D7786' },
  vehicleName: { color: '#1A1D21', fontSize: 9, fontWeight: 700, lineHeight: 1.15 },
  vehicleVersion: { color: '#41464C', fontSize: 8.5, lineHeight: 1.15, marginTop: 2 },
  vehicleYears: { color: '#62676E', fontSize: 8, marginTop: 2 },
  category: {
    backgroundColor: '#1A1D21',
    height: 22,
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  categoryText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0.55,
    textTransform: 'uppercase',
  },
  row: {
    borderBottomColor: '#E2E5E7',
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 31,
  },
  itemCell: { justifyContent: 'center', paddingHorizontal: 9, paddingVertical: 6 },
  itemLabel: { color: '#1A1D21', fontWeight: 400, lineHeight: 1.2 },
  valueCell: {
    alignItems: 'center',
    borderLeftColor: '#E2E5E7',
    borderLeftWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    minHeight: 31,
    paddingHorizontal: 7,
    position: 'relative',
  },
  advantageCell: { backgroundColor: '#FFF4EC' },
  valueText: { color: '#1A1D21', fontWeight: 400, maxLines: 2, textAlign: 'center' },
  presenceDot: { backgroundColor: '#1A1D21', borderRadius: 3, height: 6, width: 6 },
  advantageIcon: { height: 11, position: 'absolute', right: 4, width: 11 },
  emptyState: {
    backgroundColor: '#F7F8F8',
    borderColor: '#D8DCDF',
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 24,
  },
  emptyTitle: { color: '#1A1D21', fontSize: 11, fontWeight: 700 },
  emptyText: { color: '#62676E', fontSize: 9, marginTop: 5 },
  footer: {
    bottom: 14,
    color: '#747A80',
    fontSize: 7.5,
    left: 28,
    position: 'absolute',
    textAlign: 'right',
  },
});
