-- This migration is intentionally structural and transactional when executed by the
-- Supabase migration runner. It contains no data backfill. Existing rows keep NULL in
-- newly added compatibility columns; defaults configured below apply only to new rows.
-- `registration` and `present_value_subsidy` remain in the older enums solely for
-- historical compatibility and are rejected by the new commercial-offer publication flow.

alter type public.policy_calculation_method
  add value if not exists 'proportional_ipva';
alter type public.policy_calculation_method
  add value if not exists 'discounted_promotional_cash_flow_difference';
alter type public.policy_calculation_method
  add value if not exists 'non_monetized';
alter type public.commercial_policy_type
  add value if not exists 'free_registration';
alter type public.commercial_policy_type
  add value if not exists 'free_maintenance';
alter type public.commercial_policy_type
  add value if not exists 'fuel_or_recharge_voucher';

do $$
begin
  if not exists (select 1 from pg_type where typname = 'dealer_rebate_allocation_method' and typnamespace = 'public'::regnamespace) then
    create type public.dealer_rebate_allocation_method as enum (
      'explicit_legacy_component',
      'proportional_legacy_total',
      'unallocated_legacy_total'
    );
  end if;
end;
$$;

alter table public.product_public_prices
  add column if not exists price_type text,
  add column if not exists ends_on date,
  add column if not exists source_reference text,
  add column if not exists legacy_source_id bigint;

alter table public.product_public_prices
  alter column price_type set default 'msrp';

create table if not exists public.commercial_offers (
  id bigint generated by default as identity primary key,
  product_id integer not null references public.products(id) on delete restrict,
  public_price_id bigint references public.product_public_prices(id) on delete restrict,
  source_system text not null,
  source_reference text not null,
  legacy_source_id bigint,
  valid_from date not null,
  valid_to date not null,
  status public.pricing_workflow_status not null default 'draft',
  blocking_issues jsonb not null default '[]'::jsonb,
  published_at timestamp with time zone,
  published_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid references public.profiles(id) on delete set null,
  lock_version integer not null default 1,
  constraint commercial_offers_source_key unique (source_system, source_reference),
  constraint commercial_offers_validity_check check (valid_from <= valid_to),
  constraint commercial_offers_source_check check (
    btrim(source_system) <> '' and btrim(source_reference) <> ''
  ),
  constraint commercial_offers_status_check check (status in ('draft', 'published', 'archived')),
  constraint commercial_offers_blocking_issues_check check (
    jsonb_typeof(blocking_issues) = 'array'
  ),
  constraint commercial_offers_published_check check (
    status <> 'published' or (published_at is not null and published_by is not null)
  ),
  constraint commercial_offers_lock_version_check check (lock_version > 0)
);

alter table public.commercial_policies
  add column if not exists commercial_offer_id bigint,
  add column if not exists calculation_base_price_id bigint,
  add column if not exists customer_benefit_amount numeric(14,2),
  add column if not exists dealer_rebate_amount numeric(14,2),
  add column if not exists dealer_rebate_allocation_method public.dealer_rebate_allocation_method,
  add column if not exists dealer_rebate_allocation_base numeric(14,2),
  add column if not exists dealer_rebate_allocation_percentage numeric(12,8),
  add column if not exists dealer_rebate_rounding_residual numeric(14,8),
  add column if not exists legacy_policy_source text,
  add column if not exists legacy_offer_id bigint,
  add column if not exists legacy_source_column text,
  add column if not exists legacy_dealer_rebate_value numeric(14,2),
  add column if not exists fixed_amount numeric(14,2),
  add column if not exists percentage_rate numeric(14,12),
  add column if not exists voucher_type text,
  add column if not exists policy_parameters jsonb,
  add column if not exists annual_rate numeric(14,12),
  add column if not exists coverage_years numeric(6,2),
  add column if not exists remaining_months smallint,
  add column if not exists offer_month smallint,
  add column if not exists financed_principal numeric(14,2);

alter table public.commercial_policies
  alter column policy_parameters set default '{}'::jsonb;

alter table public.financial_parameter_sets
  add column if not exists annual_cdi_rate numeric(14,12),
  add column if not exists monthly_cdi_rate numeric(14,12),
  add column if not exists monthly_spread_rate numeric(14,12),
  add column if not exists monthly_reference_rate numeric(14,12),
  add column if not exists methodology text,
  add column if not exists valid_to date;

alter table public.commercial_policy_accumulators
  add column if not exists commercial_offer_id bigint,
  add column if not exists relation_type text,
  add column if not exists relation_origin text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_commercial_offer_id_fkey') then
    alter table public.commercial_policies add constraint commercial_policies_commercial_offer_id_fkey
      foreign key (commercial_offer_id) references public.commercial_offers(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_calculation_base_price_id_fkey') then
    alter table public.commercial_policies add constraint commercial_policies_calculation_base_price_id_fkey
      foreign key (calculation_base_price_id) references public.product_public_prices(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policy_accumulators_commercial_offer_id_fkey') then
    alter table public.commercial_policy_accumulators add constraint commercial_policy_accumulators_commercial_offer_id_fkey
      foreign key (commercial_offer_id) references public.commercial_offers(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'product_public_prices_legacy_validity_check') then
    alter table public.product_public_prices add constraint product_public_prices_legacy_validity_check
      check ((price_type is null or price_type = 'msrp') and (ends_on is null or ends_on >= starts_on));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_legacy_amounts_check') then
    alter table public.commercial_policies add constraint commercial_policies_legacy_amounts_check check (
      (customer_benefit_amount is null or customer_benefit_amount >= 0)
      and (dealer_rebate_amount is null or dealer_rebate_amount >= 0)
      and (dealer_rebate_allocation_base is null or dealer_rebate_allocation_base > 0)
      and (dealer_rebate_allocation_percentage is null or dealer_rebate_allocation_percentage between 0 and 100)
      and (fixed_amount is null or fixed_amount > 0)
      and (percentage_rate is null or percentage_rate between 0 and 1)
      and (annual_rate is null or annual_rate between 0 and 1)
      and (coverage_years is null or coverage_years > 0)
      and (remaining_months is null or remaining_months between 1 and 12)
      and (offer_month is null or offer_month between 1 and 12)
      and (financed_principal is null or financed_principal >= 0)
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_rebate_allocation_check') then
    alter table public.commercial_policies add constraint commercial_policies_rebate_allocation_check check (
      (dealer_rebate_amount is null and dealer_rebate_allocation_method is null)
      or (
        policy_type::text in ('retail_bonus', 'trade_in_bonus', 'subsidized_financing')
        and dealer_rebate_amount is not null
        and dealer_rebate_allocation_method::text in ('explicit_legacy_component', 'proportional_legacy_total')
      )
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_parameters_check') then
    alter table public.commercial_policies add constraint commercial_policies_parameters_check check (
      (policy_parameters is null or jsonb_typeof(policy_parameters) = 'object')
      and (voucher_type is null or voucher_type in ('fuel', 'electric_recharge', 'unspecified'))
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'financial_parameter_sets_legacy_rates_check') then
    alter table public.financial_parameter_sets add constraint financial_parameter_sets_legacy_rates_check check (
      (annual_cdi_rate is null and monthly_cdi_rate is null and monthly_spread_rate is null and monthly_reference_rate is null)
      or (annual_cdi_rate between 0 and 1 and monthly_cdi_rate between 0 and 1
          and monthly_spread_rate between 0 and 1 and monthly_reference_rate between 0 and 1
          and abs(monthly_reference_rate - monthly_cdi_rate - monthly_spread_rate) < 0.000000000001
          and methodology = 'effective_annual_cdi_plus_monthly_spread')
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'financial_parameter_sets_legacy_validity_check') then
    alter table public.financial_parameter_sets add constraint financial_parameter_sets_legacy_validity_check
      check (valid_to is null or valid_to >= effective_from);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policy_accumulators_relation_check') then
    alter table public.commercial_policy_accumulators add constraint commercial_policy_accumulators_relation_check check (
      (relation_type is null and relation_origin is null)
      or (relation_type in ('OR', 'AND') and relation_origin in ('legacy_default', 'manual_review'))
    );
  end if;
end;
$$;

create index if not exists commercial_offers_product_validity_idx
  on public.commercial_offers(product_id, valid_from, valid_to);
create index if not exists commercial_offers_public_price_id_idx
  on public.commercial_offers(public_price_id);
create index if not exists commercial_offers_legacy_source_id_idx
  on public.commercial_offers(legacy_source_id) where legacy_source_id is not null;
create index if not exists commercial_policies_commercial_offer_id_idx
  on public.commercial_policies(commercial_offer_id);
create index if not exists commercial_policies_calculation_base_price_id_idx
  on public.commercial_policies(calculation_base_price_id);
create index if not exists commercial_policy_accumulators_commercial_offer_id_idx
  on public.commercial_policy_accumulators(commercial_offer_id);

alter table public.commercial_offers enable row level security;
revoke all on table public.commercial_offers from public, anon, authenticated;
grant select, insert, update, delete on table public.commercial_offers to service_role;
revoke all on sequence public.commercial_offers_id_seq from public, anon, authenticated;
grant usage, select on sequence public.commercial_offers_id_seq to service_role;

alter table public.pricing_audit_events
  drop constraint if exists pricing_audit_events_aggregate_type_check;
alter table public.pricing_audit_events
  add constraint pricing_audit_events_aggregate_type_check check (
    aggregate_type in (
      'product_public_price',
      'financial_parameter_set',
      'commercial_policy',
      'commercial_policy_application',
      'commercial_policy_accumulator',
      'commercial_offer',
      'pricing_import_batch',
      'pricing_import_row'
    )
  );

create or replace function public.insert_pricing_publish_audit(
  p_aggregate_type text,
  p_aggregate_id bigint,
  p_before_snapshot jsonb,
  p_after_snapshot jsonb,
  p_actor_id uuid,
  p_correlation_id uuid
)
returns void language plpgsql security invoker set search_path = '' as $$
begin
  if p_aggregate_type not in (
    'product_public_price',
    'financial_parameter_set',
    'commercial_policy',
    'commercial_policy_accumulator',
    'commercial_offer'
  ) then
    raise exception using errcode = '22023', message = 'pricing audit validation failed: aggregate_type is not publishable';
  end if;
  if p_aggregate_id is null then raise exception using errcode = '22004', message = 'pricing audit validation failed: aggregate_id is required'; end if;
  if p_actor_id is null then raise exception using errcode = '22004', message = 'pricing audit validation failed: actor_id is required'; end if;
  if p_correlation_id is null then raise exception using errcode = '22004', message = 'pricing audit validation failed: correlation_id is required'; end if;
  if p_before_snapshot is null or p_after_snapshot is null then
    raise exception using errcode = '22004', message = 'pricing audit validation failed: before and after snapshots are required';
  end if;
  if exists (
    select 1 from public.pricing_audit_events as event
     where event.aggregate_type = p_aggregate_type and event.aggregate_id = p_aggregate_id
       and event.action = 'publish'::public.pricing_audit_action and event.correlation_id = p_correlation_id
  ) then
    raise exception using errcode = '23505', message = 'pricing audit validation failed: duplicate publish event';
  end if;
  insert into public.pricing_audit_events (
    aggregate_type, aggregate_id, action, before_snapshot, after_snapshot, actor_id, correlation_id
  ) values (
    p_aggregate_type, p_aggregate_id, 'publish', p_before_snapshot, p_after_snapshot, p_actor_id, p_correlation_id
  );
end;
$$;

create or replace function public.pricing_jsonb_positive_number(
  p_value jsonb,
  p_integer_only boolean
)
returns boolean language plpgsql immutable security invoker set search_path = '' as $$
declare
  parsed numeric;
begin
  if p_value is null or jsonb_typeof(p_value) <> 'number' then return false; end if;
  begin
    parsed := p_value::text::numeric;
  exception when others then
    return false;
  end;
  return parsed > 0 and (not p_integer_only or parsed = trunc(parsed));
end;
$$;

create or replace function public.validate_commercial_policy_for_offer(
  p_policy_id bigint,
  p_offer_id bigint
)
returns void language plpgsql security invoker set search_path = '' as $$
declare
  policy_record public.commercial_policies%rowtype;
  offer_record public.commercial_offers%rowtype;
  base_price_amount numeric;
  maintenance_identified boolean;
  reference_rate numeric;
  promotional_rate numeric;
  promotional_payment numeric;
  promotional_present_value numeric;
  expected_financing_benefit numeric;
begin
  select * into policy_record from public.commercial_policies where id = p_policy_id;
  if not found then raise exception using errcode = 'P0002', message = 'commercial policy does not exist'; end if;
  select * into offer_record from public.commercial_offers where id = p_offer_id;
  if not found then raise exception using errcode = 'P0002', message = 'commercial offer does not exist'; end if;
  if policy_record.commercial_offer_id is distinct from offer_record.id then
    raise exception using errcode = '23514', message = 'published policy must be linked to its commercial offer';
  end if;
  if policy_record.calculation_base_price_id is not null
     and policy_record.calculation_base_price_id is distinct from offer_record.public_price_id then
    raise exception using errcode = '23514', message = 'policy calculation price must match commercial offer price';
  end if;
  if policy_record.calculation_base_price_id is not null then
    select amount into base_price_amount from public.product_public_prices
     where id = policy_record.calculation_base_price_id
       and product_id = offer_record.product_id
       and status = 'published' and amount > 0;
    if not found then raise exception using errcode = '23514', message = 'published positive calculation base price is required'; end if;
  end if;
  if (policy_record.dealer_rebate_amount is null) is distinct from
     (policy_record.dealer_rebate_allocation_method is null) then
    raise exception using errcode = '23514', message = 'dealer rebate amount and allocation method must be set together';
  end if;
  if policy_record.dealer_rebate_amount is not null and (
       policy_record.dealer_rebate_amount <= 0
       or policy_record.policy_type::text not in ('retail_bonus', 'trade_in_bonus', 'subsidized_financing')
       or policy_record.dealer_rebate_allocation_method::text not in ('explicit_legacy_component', 'proportional_legacy_total')
     ) then
    raise exception using errcode = '23514', message = 'dealer rebate allocation is not publishable';
  end if;

  if policy_record.policy_type::text in ('retail_bonus', 'trade_in_bonus') then
    if policy_record.calculation_method::text <> 'fixed_amount' or policy_record.fixed_amount is null
       or policy_record.customer_benefit_amount is null or policy_record.customer_benefit_amount <= 0
       or policy_record.customer_benefit_amount is distinct from policy_record.fixed_amount then
      raise exception using errcode = '23514', message = 'bonus policy is not publishable';
    end if;
  elsif policy_record.policy_type::text = 'free_ipva' then
    if policy_record.calculation_method::text <> 'proportional_ipva' or policy_record.annual_rate is null
       or policy_record.annual_rate <= 0 or policy_record.annual_rate > 1 or policy_record.customer_benefit_amount is null
       or policy_record.customer_benefit_amount <= 0 or policy_record.calculation_base_price_id is null
       or policy_record.offer_month is null or policy_record.offer_month not between 1 and 12
       or policy_record.remaining_months is null or policy_record.remaining_months <> 13 - policy_record.offer_month
       or policy_record.customer_benefit_amount is distinct from round(base_price_amount * policy_record.annual_rate * policy_record.remaining_months / 12, 2) then
      raise exception using errcode = '23514', message = 'proportional IPVA policy is not publishable';
    end if;
  elsif policy_record.policy_type::text = 'free_insurance' then
    if policy_record.calculation_method::text <> 'percentage_of_msrp' or policy_record.coverage_years is null or policy_record.coverage_years <= 0
       or policy_record.annual_rate is null or policy_record.annual_rate <= 0 or policy_record.annual_rate > 1
       or policy_record.customer_benefit_amount is null or policy_record.customer_benefit_amount <= 0
       or policy_record.calculation_base_price_id is null
       or policy_record.customer_benefit_amount is distinct from round(base_price_amount * policy_record.annual_rate * policy_record.coverage_years, 2) then
      raise exception using errcode = '23514', message = 'insurance policy is not publishable';
    end if;
  elsif policy_record.policy_type::text = 'subsidized_financing' then
    if policy_record.calculation_method::text <> 'discounted_promotional_cash_flow_difference'
       or policy_record.term_months is null or policy_record.term_months <= 0
       or policy_record.customer_interest_rate_monthly is null or policy_record.customer_interest_rate_monthly < 0
       or policy_record.down_payment_percentage is null or policy_record.down_payment_percentage < 0 or policy_record.down_payment_percentage >= 100
       or policy_record.financed_principal is null or policy_record.financed_principal <= 0 or policy_record.financial_parameter_set_id is null
       or policy_record.calculation_base_price_id is null or policy_record.customer_benefit_amount is null
       or policy_record.customer_benefit_amount <= 0 then
      raise exception using errcode = '23514', message = 'financing policy is not publishable';
    end if;
    if policy_record.financed_principal is distinct from round(
      base_price_amount * (1 - policy_record.down_payment_percentage / 100), 2
    ) then
      raise exception using errcode = '23514', message = 'financing principal does not match the published MSRP and down payment';
    end if;
    select parameter_set.monthly_reference_rate into reference_rate
      from public.financial_parameter_sets as parameter_set
     where parameter_set.id = policy_record.financial_parameter_set_id
       and parameter_set.status = 'published'
       and parameter_set.monthly_reference_rate is not null
       and parameter_set.monthly_reference_rate >= 0
       and parameter_set.effective_from <= offer_record.valid_from
       and (parameter_set.valid_to is null or parameter_set.valid_to >= offer_record.valid_to);
    if not found then
      raise exception using errcode = '23514', message = 'financing requires a compatible published financial parameter set';
    end if;
    promotional_rate := policy_record.customer_interest_rate_monthly / 100;
    promotional_payment := case
      when promotional_rate = 0 then policy_record.financed_principal / policy_record.term_months
      else policy_record.financed_principal * promotional_rate
        * power(1 + promotional_rate, policy_record.term_months)
        / (power(1 + promotional_rate, policy_record.term_months) - 1)
    end;
    promotional_present_value := case
      when reference_rate = 0 then promotional_payment * policy_record.term_months
      else promotional_payment
        * (1 - power(1 + reference_rate, -policy_record.term_months)) / reference_rate
    end;
    expected_financing_benefit := round(
      policy_record.financed_principal - promotional_present_value, 2
    );
    if expected_financing_benefit <= 0
       or policy_record.customer_benefit_amount is distinct from expected_financing_benefit then
      raise exception using errcode = '23514', message = 'financing customer benefit does not match the approved present-value calculation';
    end if;
  elsif policy_record.policy_type::text = 'free_wallbox' then
    if policy_record.calculation_method::text <> 'fixed_amount' or policy_record.fixed_amount is null
       or policy_record.fixed_amount <= 0 or policy_record.customer_benefit_amount is distinct from policy_record.fixed_amount then
      raise exception using errcode = '23514', message = 'wallbox policy is not publishable';
    end if;
  elsif policy_record.policy_type::text = 'free_registration' then
    if policy_record.calculation_method::text <> 'percentage_of_msrp' or policy_record.percentage_rate is null
       or policy_record.percentage_rate <> 0.01 or policy_record.calculation_base_price_id is null
       or policy_record.customer_benefit_amount is null or policy_record.customer_benefit_amount <= 0
       or policy_record.customer_benefit_amount is distinct from round(base_price_amount * policy_record.percentage_rate, 2) then
      raise exception using errcode = '23514', message = 'registration policy is not publishable';
    end if;
  elsif policy_record.policy_type::text = 'free_maintenance' then
    maintenance_identified :=
      nullif(btrim(policy_record.description), '') is not null
      or nullif(btrim(policy_record.policy_parameters ->> 'description'), '') is not null
      or public.pricing_jsonb_positive_number(policy_record.policy_parameters -> 'maintenance_count', true)
      or public.pricing_jsonb_positive_number(policy_record.policy_parameters -> 'coverage_months', true)
      or public.pricing_jsonb_positive_number(policy_record.policy_parameters -> 'coverage_km', false);
    if policy_record.calculation_method::text <> 'non_monetized'
       or policy_record.customer_benefit_amount is not null or not maintenance_identified then
      raise exception using errcode = '23514', message = 'maintenance policy requires a description or valid positive coverage';
    end if;
  elsif policy_record.policy_type::text = 'fuel_or_recharge_voucher' then
    if policy_record.calculation_method::text <> 'fixed_amount' or policy_record.fixed_amount is null
       or policy_record.customer_benefit_amount is distinct from policy_record.fixed_amount
       or policy_record.customer_benefit_amount is null or policy_record.customer_benefit_amount <= 0
       or policy_record.voucher_type is null
       or policy_record.voucher_type not in ('fuel', 'electric_recharge', 'unspecified') then
      raise exception using errcode = '23514', message = 'voucher policy is not publishable';
    end if;
  elsif policy_record.policy_type::text = 'other' then
    if policy_record.calculation_method::text <> 'fixed_amount' or policy_record.fixed_amount is null
       or policy_record.customer_benefit_amount is null or policy_record.customer_benefit_amount <= 0
       or policy_record.customer_benefit_amount is distinct from policy_record.fixed_amount
       or (
         policy_record.legacy_policy_source is distinct from 'others_bonus'
         and nullif(btrim(policy_record.description), '') is null
       ) then
      raise exception using errcode = '23514', message = 'other policy is not publishable';
    end if;
  else
    raise exception using errcode = '23514', message = 'deprecated or unsupported policy type is not publishable in commercial offers';
  end if;
end;
$$;

create or replace function public.assert_commercial_offer_publishable(p_offer_id bigint)
returns void language plpgsql security invoker set search_path = '' as $$
declare
  offer_record public.commercial_offers%rowtype;
  policy_record record;
begin
  select * into offer_record from public.commercial_offers where id = p_offer_id;
  if not found then raise exception using errcode = 'P0002', message = 'commercial offer does not exist'; end if;
  if offer_record.status <> 'draft' then
    raise exception using errcode = '55000', message = 'commercial offer is not in a publishable transition state';
  end if;
  if jsonb_typeof(offer_record.blocking_issues) <> 'array' or jsonb_array_length(offer_record.blocking_issues) > 0 then
    raise exception using errcode = '23514', message = 'commercial offer has blocking issues';
  end if;
  if not exists (select 1 from public.products where id = offer_record.product_id) then
    raise exception using errcode = '23514', message = 'commercial offer product does not exist';
  end if;
  if offer_record.public_price_id is null or not exists (
    select 1 from public.product_public_prices as price
     where price.id = offer_record.public_price_id
       and price.product_id = offer_record.product_id
       and price.status = 'published'
       and price.amount > 0
       and price.currency_code = 'BRL'
       and price.price_type = 'msrp'
       and price.starts_on <= offer_record.valid_from
       and (price.ends_on is null or price.ends_on >= offer_record.valid_to)
  ) then
    raise exception using errcode = '23514', message = 'commercial offer requires a compatible published MSRP';
  end if;
  for policy_record in
    select id, status from public.commercial_policies
     where commercial_offer_id = offer_record.id and status <> 'archived'
     order by id
  loop
    if policy_record.status not in ('draft', 'published') then
      raise exception using errcode = '23514', message = 'commercial offer contains a policy requiring review';
    end if;
    perform public.validate_commercial_policy_for_offer(policy_record.id, offer_record.id);
  end loop;
end;
$$;

create or replace function public.validate_commercial_offer_publication()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if new.status = 'published' and (tg_op = 'INSERT' or old.status <> 'published') then
    if current_user <> 'postgres'
       or current_setting('app.pricing_commercial_offer_publication_id', true) is distinct from new.id::text then
      raise exception using errcode = '42501', message = 'commercial offer publication requires publish_commercial_offer';
    end if;
    perform public.assert_commercial_offer_publishable(new.id);
  end if;
  return new;
end;
$$;

create or replace function public.validate_legacy_policy_publication()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if new.status = 'published' and (tg_op = 'INSERT' or old.status <> 'published') then
    if new.commercial_offer_id is null then
      -- Preserve the prior SECURITY DEFINER publisher for historical application-backed records.
      -- Browser/service roles still cannot publish an unlinked policy directly.
      if current_user = 'postgres' then return new; end if;
      raise exception using errcode = '23514', message = 'published policy must be linked to a commercial offer';
    end if;
    if current_user <> 'postgres'
       or current_setting('app.pricing_commercial_offer_publication_id', true)
         is distinct from new.commercial_offer_id::text then
      raise exception using errcode = '42501', message = 'linked policy publication requires publish_commercial_offer';
    end if;
    perform public.validate_commercial_policy_for_offer(new.id, new.commercial_offer_id);
  end if;
  return new;
end;
$$;

create or replace function public.publish_commercial_offer(
  p_offer_id bigint,
  p_actor_id uuid,
  p_expected_lock_version integer,
  p_correlation_id uuid
)
returns public.commercial_offers language plpgsql security definer set search_path = '' as $$
declare
  offer_record public.commercial_offers%rowtype;
  before_snapshot jsonb;
  after_snapshot jsonb;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  if p_expected_lock_version is null then
    raise exception using errcode = '22004', message = 'commercial offer publication requires expected_lock_version';
  end if;
  if p_correlation_id is null then
    raise exception using errcode = '22004', message = 'commercial offer publication requires correlation_id';
  end if;

  select * into offer_record from public.commercial_offers
   where id = p_offer_id for update;
  if not found then raise exception using errcode = 'P0002', message = 'commercial offer does not exist'; end if;
  if offer_record.status <> 'draft' then
    raise exception using errcode = '55000', message = 'commercial offer is not draft';
  end if;
  if offer_record.lock_version <> p_expected_lock_version then
    raise exception using errcode = '40001', message = 'stale commercial offer lock_version';
  end if;

  perform 1 from public.commercial_policies
   where commercial_offer_id = offer_record.id and status <> 'archived'
   order by id for update;
  perform public.assert_commercial_offer_publishable(offer_record.id);
  before_snapshot := to_jsonb(offer_record);

  perform pg_catalog.set_config(
    'app.pricing_commercial_offer_publication_id', offer_record.id::text, true
  );
  update public.commercial_policies
     set status = 'published',
         reviewed_at = coalesce(reviewed_at, pg_catalog.now()),
         reviewed_by = coalesce(reviewed_by, p_actor_id),
         published_at = pg_catalog.now(),
         published_by = p_actor_id,
         updated_at = pg_catalog.now(),
         updated_by = p_actor_id,
         lock_version = lock_version + 1
   where commercial_offer_id = offer_record.id and status = 'draft';

  update public.commercial_offers
     set status = 'published',
         published_at = pg_catalog.now(),
         published_by = p_actor_id,
         updated_at = pg_catalog.now(),
         updated_by = p_actor_id,
         lock_version = lock_version + 1
   where id = offer_record.id
  returning * into offer_record;

  after_snapshot := to_jsonb(offer_record);
  perform public.insert_pricing_publish_audit(
    'commercial_offer', offer_record.id, before_snapshot, after_snapshot, p_actor_id, p_correlation_id
  );
  return offer_record;
end;
$$;

alter function public.publish_commercial_offer(bigint, uuid, integer, uuid) owner to postgres;
revoke all on function public.publish_commercial_offer(bigint, uuid, integer, uuid)
from public, anon, authenticated, service_role;
grant execute on function public.publish_commercial_offer(bigint, uuid, integer, uuid)
to service_role;

-- Trigger replacements below are deliberate and transaction-scoped: each named trigger belongs to
-- this migration and is recreated immediately, except the older generic offer publication trigger,
-- which is superseded by the context-bound validator above.
drop trigger if exists commercial_offers_validate_publication on public.commercial_offers;
create trigger commercial_offers_validate_publication before insert or update on public.commercial_offers
for each row execute function public.validate_commercial_offer_publication();
drop trigger if exists commercial_policies_validate_legacy_publication on public.commercial_policies;
create trigger commercial_policies_validate_legacy_publication before insert or update on public.commercial_policies
for each row execute function public.validate_legacy_policy_publication();

create or replace function public.prevent_terminal_pricing_migration_rule_change()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if old.status::text = 'archived' and new.status is distinct from old.status then
    raise exception using errcode = '55000', message = 'archived pricing records are immutable';
  end if;
  if old.status::text = 'published' and new.status::text not in ('published', 'archived') then
    raise exception using errcode = '55000', message = 'published pricing records may only be archived';
  end if;
  if old.status::text in ('published', 'archived')
     and to_jsonb(new) - array['status','updated_at','updated_by','lock_version']
       is distinct from to_jsonb(old) - array['status','updated_at','updated_by','lock_version'] then
    raise exception using errcode = '55000', message = 'published or archived pricing migration fields are immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists commercial_offers_prevent_terminal_change on public.commercial_offers;
create trigger commercial_offers_prevent_terminal_change before update on public.commercial_offers
for each row execute function public.prevent_terminal_pricing_migration_rule_change();
drop trigger if exists commercial_offers_require_publication_function on public.commercial_offers;
drop trigger if exists commercial_policies_prevent_terminal_migration_rule_change on public.commercial_policies;
create trigger commercial_policies_prevent_terminal_migration_rule_change before update on public.commercial_policies
for each row execute function public.prevent_terminal_pricing_migration_rule_change();
drop trigger if exists financial_parameter_sets_prevent_terminal_migration_rule_change on public.financial_parameter_sets;
create trigger financial_parameter_sets_prevent_terminal_migration_rule_change before update on public.financial_parameter_sets
for each row execute function public.prevent_terminal_pricing_migration_rule_change();
drop trigger if exists commercial_policy_accumulators_prevent_terminal_migration_rule_change on public.commercial_policy_accumulators;
create trigger commercial_policy_accumulators_prevent_terminal_migration_rule_change before update on public.commercial_policy_accumulators
for each row execute function public.prevent_terminal_pricing_migration_rule_change();

create or replace function public.prevent_terminal_commercial_offer_delete()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if old.status in ('published', 'archived') then
    raise exception using errcode = '55000', message = 'published or archived commercial offers cannot be deleted';
  end if;
  return old;
end;
$$;
drop trigger if exists commercial_offers_prevent_terminal_delete on public.commercial_offers;
create trigger commercial_offers_prevent_terminal_delete before delete on public.commercial_offers
for each row execute function public.prevent_terminal_commercial_offer_delete();

alter function public.pricing_jsonb_positive_number(jsonb, boolean) owner to postgres;
alter function public.validate_commercial_policy_for_offer(bigint, bigint) owner to postgres;
alter function public.assert_commercial_offer_publishable(bigint) owner to postgres;
alter function public.validate_commercial_offer_publication() owner to postgres;
alter function public.validate_legacy_policy_publication() owner to postgres;
alter function public.prevent_terminal_pricing_migration_rule_change() owner to postgres;
alter function public.prevent_terminal_commercial_offer_delete() owner to postgres;
revoke all on function public.pricing_jsonb_positive_number(jsonb, boolean) from public, anon, authenticated, service_role;
revoke all on function public.validate_commercial_policy_for_offer(bigint, bigint) from public, anon, authenticated, service_role;
revoke all on function public.assert_commercial_offer_publishable(bigint) from public, anon, authenticated, service_role;
revoke all on function public.validate_commercial_offer_publication() from public, anon, authenticated, service_role;
revoke all on function public.validate_legacy_policy_publication() from public, anon, authenticated, service_role;
revoke all on function public.prevent_terminal_pricing_migration_rule_change() from public, anon, authenticated, service_role;
revoke all on function public.prevent_terminal_commercial_offer_delete() from public, anon, authenticated, service_role;

comment on table public.commercial_offers is 'Versioned commercial campaign aggregate; legacy ids are audit metadata only.';
comment on table public.commercial_policy_applications is 'Legacy per-product calculation results retained for compatibility; commercial offers use policy-native validated amounts.';
comment on column public.commercial_policies.dealer_rebate_amount is 'Dealer contribution excluded from gross customer benefit.';
comment on column public.commercial_policies.calculation_base_price_id is 'Versioned MSRP used by the policy calculation.';
comment on column public.commercial_policies.dealer_rebate_allocation_method is 'Auditable legacy rebate allocation; only retail, trade-in and financing are eligible.';
comment on column public.commercial_policies.policy_parameters is 'Validated type-specific metadata such as maintenance coverage; not an economic amount.';
