alter type public.policy_calculation_method
  add value if not exists 'proportional_ipva';
alter type public.policy_calculation_method
  add value if not exists 'discounted_promotional_cash_flow_difference';
alter type public.policy_calculation_method
  add value if not exists 'non_monetized';
alter type public.commercial_policy_type
  add value if not exists 'free_registration';
alter type public.commercial_policy_type
  add value if not exists 'free_maintenance';
alter type public.commercial_policy_type
  add value if not exists 'fuel_or_recharge_voucher';

do $$
begin
  if not exists (select 1 from pg_type where typname = 'dealer_rebate_allocation_method' and typnamespace = 'public'::regnamespace) then
    create type public.dealer_rebate_allocation_method as enum (
      'explicit_legacy_component',
      'proportional_legacy_total',
      'unallocated_legacy_total'
    );
  end if;
end;
$$;

alter table public.product_public_prices
  add column if not exists price_type text not null default 'msrp',
  add column if not exists ends_on date,
  add column if not exists source_reference text,
  add column if not exists legacy_source_id bigint;

create table if not exists public.commercial_offers (
  id bigint generated by default as identity primary key,
  product_id integer not null references public.products(id) on delete restrict,
  public_price_id bigint references public.product_public_prices(id) on delete restrict,
  source_system text not null,
  source_reference text not null,
  legacy_source_id bigint,
  valid_from date not null,
  valid_to date not null,
  status public.pricing_workflow_status not null default 'draft',
  blocking_issues jsonb not null default '[]'::jsonb,
  published_at timestamp with time zone,
  published_by uuid references public.profiles(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid references public.profiles(id) on delete set null,
  lock_version integer not null default 1,
  constraint commercial_offers_source_key unique (source_system, source_reference),
  constraint commercial_offers_validity_check check (valid_from <= valid_to),
  constraint commercial_offers_source_check check (
    btrim(source_system) <> '' and btrim(source_reference) <> ''
  ),
  constraint commercial_offers_status_check check (status in ('draft', 'published', 'archived')),
  constraint commercial_offers_blocking_issues_check check (
    jsonb_typeof(blocking_issues) = 'array'
  ),
  constraint commercial_offers_published_check check (
    status <> 'published' or (published_at is not null and published_by is not null)
  ),
  constraint commercial_offers_lock_version_check check (lock_version > 0)
);

alter table public.commercial_policies
  add column if not exists commercial_offer_id bigint,
  add column if not exists calculation_base_price_id bigint,
  add column if not exists customer_benefit_amount numeric(14,2),
  add column if not exists dealer_rebate_amount numeric(14,2),
  add column if not exists dealer_rebate_allocation_method public.dealer_rebate_allocation_method,
  add column if not exists dealer_rebate_allocation_base numeric(14,2),
  add column if not exists dealer_rebate_allocation_percentage numeric(12,8),
  add column if not exists dealer_rebate_rounding_residual numeric(14,8),
  add column if not exists legacy_policy_source text,
  add column if not exists legacy_offer_id bigint,
  add column if not exists legacy_source_column text,
  add column if not exists legacy_dealer_rebate_value numeric(14,2),
  add column if not exists fixed_amount numeric(14,2),
  add column if not exists percentage_rate numeric(14,12),
  add column if not exists voucher_type text,
  add column if not exists policy_parameters jsonb not null default '{}'::jsonb,
  add column if not exists annual_rate numeric(14,12),
  add column if not exists coverage_years numeric(6,2),
  add column if not exists remaining_months smallint,
  add column if not exists offer_month smallint,
  add column if not exists financed_principal numeric(14,2);

alter table public.financial_parameter_sets
  add column if not exists annual_cdi_rate numeric(14,12),
  add column if not exists monthly_cdi_rate numeric(14,12),
  add column if not exists monthly_spread_rate numeric(14,12),
  add column if not exists monthly_reference_rate numeric(14,12),
  add column if not exists methodology text,
  add column if not exists valid_to date;

alter table public.commercial_policy_accumulators
  add column if not exists commercial_offer_id bigint,
  add column if not exists relation_type text,
  add column if not exists relation_origin text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_commercial_offer_id_fkey') then
    alter table public.commercial_policies add constraint commercial_policies_commercial_offer_id_fkey
      foreign key (commercial_offer_id) references public.commercial_offers(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_calculation_base_price_id_fkey') then
    alter table public.commercial_policies add constraint commercial_policies_calculation_base_price_id_fkey
      foreign key (calculation_base_price_id) references public.product_public_prices(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policy_accumulators_commercial_offer_id_fkey') then
    alter table public.commercial_policy_accumulators add constraint commercial_policy_accumulators_commercial_offer_id_fkey
      foreign key (commercial_offer_id) references public.commercial_offers(id) on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'product_public_prices_legacy_validity_check') then
    alter table public.product_public_prices add constraint product_public_prices_legacy_validity_check
      check (price_type = 'msrp' and (ends_on is null or ends_on >= starts_on));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_legacy_amounts_check') then
    alter table public.commercial_policies add constraint commercial_policies_legacy_amounts_check check (
      (customer_benefit_amount is null or customer_benefit_amount >= 0)
      and (dealer_rebate_amount is null or dealer_rebate_amount >= 0)
      and (dealer_rebate_allocation_base is null or dealer_rebate_allocation_base > 0)
      and (dealer_rebate_allocation_percentage is null or dealer_rebate_allocation_percentage between 0 and 100)
      and (fixed_amount is null or fixed_amount > 0)
      and (percentage_rate is null or percentage_rate between 0 and 1)
      and (annual_rate is null or annual_rate between 0 and 1)
      and (coverage_years is null or coverage_years > 0)
      and (remaining_months is null or remaining_months between 1 and 12)
      and (offer_month is null or offer_month between 1 and 12)
      and (financed_principal is null or financed_principal >= 0)
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_rebate_allocation_check') then
    alter table public.commercial_policies add constraint commercial_policies_rebate_allocation_check check (
      (dealer_rebate_amount is null and dealer_rebate_allocation_method is null)
      or (
        policy_type::text in ('retail_bonus', 'trade_in_bonus', 'subsidized_financing')
        and dealer_rebate_amount is not null
        and dealer_rebate_allocation_method::text in ('explicit_legacy_component', 'proportional_legacy_total')
      )
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policies_parameters_check') then
    alter table public.commercial_policies add constraint commercial_policies_parameters_check check (
      jsonb_typeof(policy_parameters) = 'object'
      and (voucher_type is null or voucher_type in ('fuel', 'electric_recharge', 'unspecified'))
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'financial_parameter_sets_legacy_rates_check') then
    alter table public.financial_parameter_sets add constraint financial_parameter_sets_legacy_rates_check check (
      (annual_cdi_rate is null and monthly_cdi_rate is null and monthly_spread_rate is null and monthly_reference_rate is null)
      or (annual_cdi_rate between 0 and 1 and monthly_cdi_rate between 0 and 1
          and monthly_spread_rate between 0 and 1 and monthly_reference_rate between 0 and 1
          and abs(monthly_reference_rate - monthly_cdi_rate - monthly_spread_rate) < 0.000000000001
          and methodology = 'effective_annual_cdi_plus_monthly_spread')
    );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'financial_parameter_sets_legacy_validity_check') then
    alter table public.financial_parameter_sets add constraint financial_parameter_sets_legacy_validity_check
      check (valid_to is null or valid_to >= effective_from);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'commercial_policy_accumulators_relation_check') then
    alter table public.commercial_policy_accumulators add constraint commercial_policy_accumulators_relation_check check (
      (relation_type is null and relation_origin is null)
      or (relation_type in ('OR', 'AND') and relation_origin in ('legacy_default', 'manual_review'))
    );
  end if;
end;
$$;

create index if not exists commercial_offers_product_validity_idx
  on public.commercial_offers(product_id, valid_from, valid_to);
create index if not exists commercial_offers_public_price_id_idx
  on public.commercial_offers(public_price_id);
create index if not exists commercial_offers_legacy_source_id_idx
  on public.commercial_offers(legacy_source_id) where legacy_source_id is not null;
create index if not exists commercial_policies_commercial_offer_id_idx
  on public.commercial_policies(commercial_offer_id);
create index if not exists commercial_policies_calculation_base_price_id_idx
  on public.commercial_policies(calculation_base_price_id);
create index if not exists commercial_policy_accumulators_commercial_offer_id_idx
  on public.commercial_policy_accumulators(commercial_offer_id);

alter table public.commercial_offers enable row level security;
revoke all on table public.commercial_offers from public, anon, authenticated;
grant select, insert, update, delete on table public.commercial_offers to service_role;
revoke all on sequence public.commercial_offers_id_seq from public, anon, authenticated;
grant usage, select on sequence public.commercial_offers_id_seq to service_role;

create or replace function public.validate_commercial_offer_publication()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if new.status = 'published' then
    if new.valid_from > new.valid_to or btrim(new.source_system) = '' or btrim(new.source_reference) = ''
       or jsonb_array_length(new.blocking_issues) > 0
       or not exists (select 1 from public.products p where p.id = new.product_id)
       or new.public_price_id is null
       or not exists (
         select 1 from public.product_public_prices p
          where p.id = new.public_price_id and p.product_id = new.product_id and p.amount > 0
       )
       or exists (select 1 from public.commercial_policies p
                   where p.commercial_offer_id = new.id and p.status not in ('published', 'archived')) then
      raise exception using errcode = '23514', message = 'commercial offer is not publishable';
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.validate_legacy_policy_publication()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare
  offer_record public.commercial_offers%rowtype;
  base_price_amount numeric;
begin
  if new.status <> 'published' then return new; end if;
  if new.commercial_offer_id is null then
    raise exception using errcode = '23514', message = 'published policy must be linked to a commercial offer';
  end if;
  select * into offer_record from public.commercial_offers where id = new.commercial_offer_id;
  if not found then raise exception using errcode = '23514', message = 'commercial offer is required'; end if;
  if new.calculation_base_price_id is not null and new.calculation_base_price_id is distinct from offer_record.public_price_id then
    raise exception using errcode = '23514', message = 'policy calculation price must match commercial offer price';
  end if;
  if new.calculation_base_price_id is not null then
    select amount into base_price_amount
      from public.product_public_prices
     where id = new.calculation_base_price_id and amount > 0;
    if not found then
      raise exception using errcode = '23514', message = 'positive calculation base price is required';
    end if;
  end if;
  if new.dealer_rebate_amount is not null and (
       new.policy_type::text not in ('retail_bonus', 'trade_in_bonus', 'subsidized_financing')
       or new.dealer_rebate_allocation_method is null
       or new.dealer_rebate_allocation_method::text = 'unallocated_legacy_total'
     ) then
    raise exception using errcode = '23514', message = 'dealer rebate allocation is not publishable';
  end if;

  if new.policy_type::text in ('retail_bonus', 'trade_in_bonus') then
    if new.calculation_method::text <> 'fixed_amount' or new.fixed_amount is null
       or new.customer_benefit_amount is null or new.customer_benefit_amount <= 0
       or new.customer_benefit_amount is distinct from new.fixed_amount then
      raise exception using errcode = '23514', message = 'bonus policy is not publishable';
    end if;
  elsif new.policy_type::text = 'free_ipva' then
    if new.calculation_method::text <> 'proportional_ipva' or new.annual_rate is null
       or new.annual_rate <= 0 or new.annual_rate > 1 or new.customer_benefit_amount is null
       or new.customer_benefit_amount <= 0 or new.calculation_base_price_id is null
       or new.offer_month is null or new.offer_month not between 1 and 12
       or new.remaining_months is null or new.remaining_months <> 13 - new.offer_month
       or new.customer_benefit_amount is distinct from round(base_price_amount * new.annual_rate * new.remaining_months / 12, 2) then
      raise exception using errcode = '23514', message = 'proportional IPVA policy is not publishable';
    end if;
  elsif new.policy_type::text = 'free_insurance' then
    if new.calculation_method::text <> 'percentage_of_msrp' or new.coverage_years is null or new.coverage_years <= 0
       or new.annual_rate is null or new.annual_rate <= 0 or new.annual_rate > 1
       or new.customer_benefit_amount is null or new.customer_benefit_amount <= 0
       or new.calculation_base_price_id is null
       or new.customer_benefit_amount is distinct from round(base_price_amount * new.annual_rate * new.coverage_years, 2) then
      raise exception using errcode = '23514', message = 'insurance policy is not publishable';
    end if;
  elsif new.policy_type::text = 'subsidized_financing' then
    if new.calculation_method::text <> 'discounted_promotional_cash_flow_difference'
       or new.term_months is null or new.term_months <= 0
       or new.customer_interest_rate_monthly is null or new.customer_interest_rate_monthly < 0
       or new.down_payment_percentage is null or new.down_payment_percentage < 0 or new.down_payment_percentage >= 100
       or new.financed_principal is null or new.financed_principal <= 0 or new.financial_parameter_set_id is null
       or new.calculation_base_price_id is null or new.customer_benefit_amount is null
       or new.customer_benefit_amount <= 0 then
      raise exception using errcode = '23514', message = 'financing policy is not publishable';
    end if;
  elsif new.policy_type::text = 'free_wallbox' then
    if new.calculation_method::text <> 'fixed_amount' or new.fixed_amount is null
       or new.fixed_amount <= 0 or new.customer_benefit_amount is distinct from new.fixed_amount then
      raise exception using errcode = '23514', message = 'wallbox policy is not publishable';
    end if;
  elsif new.policy_type::text = 'free_registration' then
    if new.calculation_method::text <> 'percentage_of_msrp' or new.percentage_rate is null
       or new.percentage_rate <= 0 or new.calculation_base_price_id is null
       or new.customer_benefit_amount is null or new.customer_benefit_amount <= 0
       or new.customer_benefit_amount is distinct from round(base_price_amount * new.percentage_rate, 2) then
      raise exception using errcode = '23514', message = 'registration policy is not publishable';
    end if;
  elsif new.policy_type::text = 'free_maintenance' then
    if new.calculation_method::text <> 'non_monetized' or new.customer_benefit_amount is not null
       or (
         nullif(btrim(new.description), '') is null
         and nullif(btrim(new.policy_parameters ->> 'description'), '') is null
         and nullif(btrim(new.policy_parameters ->> 'maintenance_count'), '') is null
         and nullif(btrim(new.policy_parameters ->> 'coverage_months'), '') is null
         and nullif(btrim(new.policy_parameters ->> 'coverage_km'), '') is null
       ) then
      raise exception using errcode = '23514', message = 'maintenance policy is not publishable';
    end if;
  elsif new.policy_type::text = 'fuel_or_recharge_voucher' then
    if new.calculation_method::text <> 'fixed_amount' or new.fixed_amount is null
       or new.customer_benefit_amount is distinct from new.fixed_amount
       or new.customer_benefit_amount is null
       or new.customer_benefit_amount <= 0
       or new.voucher_type not in ('fuel', 'electric_recharge', 'unspecified') then
      raise exception using errcode = '23514', message = 'voucher policy is not publishable';
    end if;
  elsif new.policy_type::text = 'other' then
    if new.calculation_method::text <> 'fixed_amount' or new.fixed_amount is null
       or new.customer_benefit_amount is null or new.customer_benefit_amount <= 0
       or new.customer_benefit_amount is distinct from new.fixed_amount then
      raise exception using errcode = '23514', message = 'other policy is not publishable';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists commercial_offers_validate_publication on public.commercial_offers;
create trigger commercial_offers_validate_publication before insert or update on public.commercial_offers
for each row execute function public.validate_commercial_offer_publication();
drop trigger if exists commercial_policies_validate_legacy_publication on public.commercial_policies;
create trigger commercial_policies_validate_legacy_publication before insert or update on public.commercial_policies
for each row execute function public.validate_legacy_policy_publication();

create or replace function public.prevent_terminal_pricing_migration_rule_change()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if old.status::text = 'archived' and new.status is distinct from old.status then
    raise exception using errcode = '55000', message = 'archived pricing records are immutable';
  end if;
  if old.status::text = 'published' and new.status::text not in ('published', 'archived') then
    raise exception using errcode = '55000', message = 'published pricing records may only be archived';
  end if;
  if old.status::text in ('published', 'archived')
     and to_jsonb(new) - array['status','updated_at','updated_by','lock_version']
       is distinct from to_jsonb(old) - array['status','updated_at','updated_by','lock_version'] then
    raise exception using errcode = '55000', message = 'published or archived pricing migration fields are immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists commercial_offers_prevent_terminal_change on public.commercial_offers;
create trigger commercial_offers_prevent_terminal_change before update on public.commercial_offers
for each row execute function public.prevent_terminal_pricing_migration_rule_change();
drop trigger if exists commercial_offers_require_publication_function on public.commercial_offers;
create trigger commercial_offers_require_publication_function before insert or update on public.commercial_offers
for each row execute function public.prevent_direct_pricing_publication();
drop trigger if exists commercial_policies_prevent_terminal_migration_rule_change on public.commercial_policies;
create trigger commercial_policies_prevent_terminal_migration_rule_change before update on public.commercial_policies
for each row execute function public.prevent_terminal_pricing_migration_rule_change();
drop trigger if exists financial_parameter_sets_prevent_terminal_migration_rule_change on public.financial_parameter_sets;
create trigger financial_parameter_sets_prevent_terminal_migration_rule_change before update on public.financial_parameter_sets
for each row execute function public.prevent_terminal_pricing_migration_rule_change();
drop trigger if exists commercial_policy_accumulators_prevent_terminal_migration_rule_change on public.commercial_policy_accumulators;
create trigger commercial_policy_accumulators_prevent_terminal_migration_rule_change before update on public.commercial_policy_accumulators
for each row execute function public.prevent_terminal_pricing_migration_rule_change();

comment on table public.commercial_offers is 'Versioned commercial campaign aggregate; legacy ids are audit metadata only.';
comment on column public.commercial_policies.dealer_rebate_amount is 'Dealer contribution excluded from gross customer benefit.';
comment on column public.commercial_policies.calculation_base_price_id is 'Versioned MSRP used by the policy calculation.';
comment on column public.commercial_policies.dealer_rebate_allocation_method is 'Auditable legacy rebate allocation; only retail, trade-in and financing are eligible.';
comment on column public.commercial_policies.policy_parameters is 'Validated type-specific metadata such as maintenance coverage; not an economic amount.';
