create type public.pricing_import_status as enum (
  'uploaded',
  'extracting',
  'needs_review',
  'ready',
  'promoting',
  'promoted',
  'failed',
  'rejected',
  'archived'
);

create type public.pricing_import_row_status as enum (
  'parsed',
  'unmatched',
  'needs_review',
  'approved',
  'rejected',
  'promoted'
);

create type public.pricing_review_decision as enum (
  'approve',
  'reject',
  'request_changes',
  'match_product',
  'classify'
);

create type public.pricing_audit_action as enum (
  'insert',
  'update',
  'publish',
  'reject',
  'archive',
  'link',
  'unlink',
  'promote'
);

create table public.pricing_import_batches (
  id bigint generated by default as identity,
  source_type public.pricing_source_type not null,
  idempotency_key text not null,
  original_file_name text,
  storage_object_path text,
  content_sha256 character(64),
  campaign_reference text,
  valid_from date,
  valid_to date,
  extractor_provider text,
  extractor_model text,
  prompt_version text,
  schema_version text not null,
  status public.pricing_import_status not null default 'uploaded',
  metadata jsonb not null default '{}'::jsonb,
  legacy_import_id bigint,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  promoted_at timestamp with time zone,
  promoted_by uuid,
  lock_version integer not null default 1,
  constraint pricing_import_batches_pkey primary key (id),
  constraint pricing_import_batches_idempotency_key_key unique (idempotency_key),
  constraint pricing_import_batches_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_batches_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_batches_reviewed_by_fkey foreign key (reviewed_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_batches_promoted_by_fkey foreign key (promoted_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_batches_source_type_check check (source_type <> 'manual'),
  constraint pricing_import_batches_idempotency_key_check check (
    btrim(idempotency_key) <> ''
  ),
  constraint pricing_import_batches_content_sha256_check check (
    content_sha256 is null or btrim(content_sha256) ~ '^[0-9A-Fa-f]{64}$'
  ),
  constraint pricing_import_batches_dates_check check (
    valid_to is null or valid_from is null or valid_to >= valid_from
  ),
  constraint pricing_import_batches_schema_version_check check (
    btrim(schema_version) <> ''
  ),
  constraint pricing_import_batches_lock_version_check check (lock_version > 0)
);

create unique index pricing_import_batches_legacy_import_id_key
  on public.pricing_import_batches (legacy_import_id)
  where legacy_import_id is not null;
create index pricing_import_batches_status_created_at_idx
  on public.pricing_import_batches (status, created_at);
create index pricing_import_batches_content_sha256_idx
  on public.pricing_import_batches (content_sha256);
create index pricing_import_batches_source_type_created_at_idx
  on public.pricing_import_batches (source_type, created_at);

create table public.pricing_import_rows (
  id bigint generated by default as identity,
  batch_id bigint not null,
  source_row_number integer not null,
  source_page integer,
  legacy_source_table text,
  legacy_source_id bigint,
  raw_text text,
  raw_payload jsonb not null default '{}'::jsonb,
  normalized_payload jsonb not null default '{}'::jsonb,
  confidence_score numeric(5,2),
  matched_product_id integer,
  status public.pricing_import_row_status not null default 'parsed',
  issue_codes text[] not null default '{}'::text[],
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  lock_version integer not null default 1,
  constraint pricing_import_rows_pkey primary key (id),
  constraint pricing_import_rows_batch_source_row_key unique (batch_id, source_row_number),
  constraint pricing_import_rows_batch_id_fkey foreign key (batch_id)
    references public.pricing_import_batches(id) on delete cascade,
  constraint pricing_import_rows_matched_product_id_fkey foreign key (matched_product_id)
    references public.products(id) on delete restrict,
  constraint pricing_import_rows_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_rows_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_rows_source_row_number_check check (source_row_number > 0),
  constraint pricing_import_rows_source_page_check check (
    source_page is null or source_page > 0
  ),
  constraint pricing_import_rows_legacy_source_table_check check (
    legacy_source_table is null
    or legacy_source_table in (
      'price_offer_import_rows',
      'price_offers_staging',
      'product_price_offers'
    )
  ),
  constraint pricing_import_rows_confidence_score_check check (
    confidence_score is null or confidence_score between 0 and 100
  ),
  constraint pricing_import_rows_lock_version_check check (lock_version > 0)
);

create unique index pricing_import_rows_legacy_source_key
  on public.pricing_import_rows (legacy_source_table, legacy_source_id)
  where legacy_source_table is not null and legacy_source_id is not null;
create index pricing_import_rows_batch_status_idx
  on public.pricing_import_rows (batch_id, status);
create index pricing_import_rows_matched_product_id_idx
  on public.pricing_import_rows (matched_product_id);

create table public.pricing_import_row_outputs (
  id bigint generated by default as identity,
  import_row_id bigint not null,
  public_price_id bigint,
  policy_id bigint,
  accumulator_id bigint,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  constraint pricing_import_row_outputs_pkey primary key (id),
  constraint pricing_import_row_outputs_import_row_id_fkey foreign key (import_row_id)
    references public.pricing_import_rows(id) on delete restrict,
  constraint pricing_import_row_outputs_public_price_id_fkey foreign key (public_price_id)
    references public.product_public_prices(id) on delete restrict,
  constraint pricing_import_row_outputs_policy_id_fkey foreign key (policy_id)
    references public.commercial_policies(id) on delete restrict,
  constraint pricing_import_row_outputs_accumulator_id_fkey foreign key (accumulator_id)
    references public.commercial_policy_accumulators(id) on delete restrict,
  constraint pricing_import_row_outputs_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_row_outputs_exactly_one_check check (
    num_nonnulls(public_price_id, policy_id, accumulator_id) = 1
  )
);

create unique index pricing_import_row_outputs_import_public_price_key
  on public.pricing_import_row_outputs (import_row_id, public_price_id)
  where public_price_id is not null;
create unique index pricing_import_row_outputs_import_policy_key
  on public.pricing_import_row_outputs (import_row_id, policy_id)
  where policy_id is not null;
create unique index pricing_import_row_outputs_import_accumulator_key
  on public.pricing_import_row_outputs (import_row_id, accumulator_id)
  where accumulator_id is not null;
create index pricing_import_row_outputs_import_row_id_idx
  on public.pricing_import_row_outputs (import_row_id);
create index pricing_import_row_outputs_public_price_id_idx
  on public.pricing_import_row_outputs (public_price_id);
create index pricing_import_row_outputs_policy_id_idx
  on public.pricing_import_row_outputs (policy_id);
create index pricing_import_row_outputs_accumulator_id_idx
  on public.pricing_import_row_outputs (accumulator_id);

create table public.pricing_import_row_reviews (
  id bigint generated by default as identity,
  import_row_id bigint not null,
  decision public.pricing_review_decision not null,
  previous_status public.pricing_import_row_status not null,
  next_status public.pricing_import_row_status not null,
  notes text,
  snapshot jsonb not null,
  reviewed_at timestamp with time zone not null default now(),
  reviewed_by uuid not null,
  constraint pricing_import_row_reviews_pkey primary key (id),
  constraint pricing_import_row_reviews_import_row_id_fkey foreign key (import_row_id)
    references public.pricing_import_rows(id) on delete restrict,
  constraint pricing_import_row_reviews_reviewed_by_fkey foreign key (reviewed_by)
    references public.profiles(id) on delete restrict,
  constraint pricing_import_row_reviews_notes_check check (
    decision not in ('reject', 'request_changes')
    or nullif(btrim(notes), '') is not null
  )
);

create index pricing_import_row_reviews_import_reviewed_at_idx
  on public.pricing_import_row_reviews (import_row_id, reviewed_at desc);
create index pricing_import_row_reviews_reviewer_reviewed_at_idx
  on public.pricing_import_row_reviews (reviewed_by, reviewed_at desc);

create table public.pricing_audit_events (
  id bigint generated by default as identity,
  aggregate_type text not null,
  aggregate_id bigint not null,
  action public.pricing_audit_action not null,
  before_snapshot jsonb,
  after_snapshot jsonb,
  reason text,
  actor_id uuid,
  occurred_at timestamp with time zone not null default now(),
  correlation_id uuid not null,
  constraint pricing_audit_events_pkey primary key (id),
  constraint pricing_audit_events_actor_id_fkey foreign key (actor_id)
    references public.profiles(id) on delete set null,
  constraint pricing_audit_events_aggregate_type_check check (
    aggregate_type in (
      'product_public_price',
      'financial_parameter_set',
      'commercial_policy',
      'commercial_policy_application',
      'commercial_policy_accumulator',
      'pricing_import_batch',
      'pricing_import_row'
    )
  ),
  constraint pricing_audit_events_snapshot_check check (
    before_snapshot is not null or after_snapshot is not null
  ),
  constraint pricing_audit_events_reason_check check (
    action not in ('update', 'reject', 'archive')
    or nullif(btrim(reason), '') is not null
  )
);

create index pricing_audit_events_aggregate_occurred_at_idx
  on public.pricing_audit_events (aggregate_type, aggregate_id, occurred_at desc);
create index pricing_audit_events_actor_occurred_at_idx
  on public.pricing_audit_events (actor_id, occurred_at desc);
create index pricing_audit_events_correlation_id_idx
  on public.pricing_audit_events (correlation_id);

alter table public.product_public_prices
  add constraint product_public_prices_source_import_row_id_fkey
  foreign key (source_import_row_id)
  references public.pricing_import_rows(id)
  on delete restrict;

alter table public.commercial_policies
  add constraint commercial_policies_source_import_row_id_fkey
  foreign key (source_import_row_id)
  references public.pricing_import_rows(id)
  on delete restrict;

alter table public.commercial_policy_accumulators
  add constraint commercial_policy_accumulators_source_import_row_id_fkey
  foreign key (source_import_row_id)
  references public.pricing_import_rows(id)
  on delete restrict;

alter table public.pricing_import_batches enable row level security;
alter table public.pricing_import_rows enable row level security;
alter table public.pricing_import_row_outputs enable row level security;
alter table public.pricing_import_row_reviews enable row level security;
alter table public.pricing_audit_events enable row level security;

revoke all privileges on table
  public.pricing_import_batches,
  public.pricing_import_rows,
  public.pricing_import_row_outputs,
  public.pricing_import_row_reviews,
  public.pricing_audit_events
from public, anon, authenticated, service_role;

revoke all privileges on sequence
  public.pricing_import_batches_id_seq,
  public.pricing_import_rows_id_seq,
  public.pricing_import_row_outputs_id_seq,
  public.pricing_import_row_reviews_id_seq,
  public.pricing_audit_events_id_seq
from public, anon, authenticated, service_role;

grant select, insert, update on table
  public.pricing_import_batches,
  public.pricing_import_rows,
  public.pricing_import_row_outputs,
  public.pricing_import_row_reviews
to service_role;

grant select, insert on table public.pricing_audit_events
to service_role;

grant usage, select on sequence
  public.pricing_import_batches_id_seq,
  public.pricing_import_rows_id_seq,
  public.pricing_import_row_outputs_id_seq,
  public.pricing_import_row_reviews_id_seq,
  public.pricing_audit_events_id_seq
to service_role;
