create type public.pricing_workflow_status as enum (
  'draft',
  'needs_review',
  'published',
  'rejected',
  'archived'
);

create type public.commercial_policy_type as enum (
  'retail_bonus',
  'trade_in_bonus',
  'subsidized_financing',
  'free_ipva',
  'free_insurance',
  'free_wallbox',
  'registration',
  'other'
);

create type public.commercial_policy_scope_type as enum (
  'model',
  'product_set'
);

create type public.policy_calculation_method as enum (
  'fixed_amount',
  'percentage_of_msrp',
  'present_value_subsidy',
  'manual_amount'
);

create type public.pricing_source_type as enum (
  'manual',
  'legacy_backfill',
  'ai_extraction',
  'api_import'
);

create table public.product_public_prices (
  id bigint generated by default as identity,
  product_id integer not null,
  amount numeric(14,2) not null,
  currency_code character(3) not null default 'BRL',
  starts_on date not null,
  status public.pricing_workflow_status not null default 'draft',
  source_type public.pricing_source_type not null,
  source_import_row_id bigint,
  source_snapshot jsonb not null default '{}'::jsonb,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  published_at timestamp with time zone,
  published_by uuid,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  lock_version integer not null default 1,
  constraint product_public_prices_pkey primary key (id),
  constraint product_public_prices_product_starts_on_key unique (product_id, starts_on),
  constraint product_public_prices_product_id_fkey foreign key (product_id)
    references public.products(id) on delete restrict,
  constraint product_public_prices_reviewed_by_fkey foreign key (reviewed_by)
    references public.profiles(id) on delete set null,
  constraint product_public_prices_published_by_fkey foreign key (published_by)
    references public.profiles(id) on delete set null,
  constraint product_public_prices_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint product_public_prices_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint product_public_prices_amount_check check (amount >= 0),
  constraint product_public_prices_currency_code_check check (currency_code = 'BRL'),
  constraint product_public_prices_zero_status_check check (
    amount <> 0 or status in ('draft', 'needs_review')
  ),
  constraint product_public_prices_published_check check (
    status <> 'published'
    or (amount > 0 and published_at is not null and published_by is not null)
  ),
  constraint product_public_prices_source_import_check check (
    source_type = 'manual' or source_import_row_id is not null
  ),
  constraint product_public_prices_lock_version_check check (lock_version > 0)
);

create index product_public_prices_product_starts_on_idx
  on public.product_public_prices (product_id, starts_on desc);
create index product_public_prices_published_product_starts_on_idx
  on public.product_public_prices (product_id, starts_on desc)
  where status = 'published';
create index product_public_prices_status_starts_on_idx
  on public.product_public_prices (status, starts_on);
create index product_public_prices_source_import_row_id_idx
  on public.product_public_prices (source_import_row_id)
  where source_import_row_id is not null;

create table public.financial_parameter_sets (
  id bigint generated by default as identity,
  version integer not null,
  name text not null,
  effective_from date not null,
  cdi_monthly_percentage numeric(9,6) not null,
  spread_monthly_percentage numeric(9,6) not null,
  status public.pricing_workflow_status not null default 'draft',
  source_type public.pricing_source_type not null,
  source_reference text,
  source_snapshot jsonb not null default '{}'::jsonb,
  notes text,
  published_at timestamp with time zone,
  published_by uuid,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  lock_version integer not null default 1,
  constraint financial_parameter_sets_pkey primary key (id),
  constraint financial_parameter_sets_version_key unique (version),
  constraint financial_parameter_sets_published_by_fkey foreign key (published_by)
    references public.profiles(id) on delete set null,
  constraint financial_parameter_sets_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint financial_parameter_sets_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint financial_parameter_sets_version_check check (version > 0),
  constraint financial_parameter_sets_name_check check (btrim(name) <> ''),
  constraint financial_parameter_sets_cdi_monthly_percentage_check check (
    cdi_monthly_percentage between 0 and 100
  ),
  constraint financial_parameter_sets_spread_monthly_percentage_check check (
    spread_monthly_percentage between 0 and 100
  ),
  constraint financial_parameter_sets_published_check check (
    status <> 'published' or (published_at is not null and published_by is not null)
  ),
  constraint financial_parameter_sets_lock_version_check check (lock_version > 0)
);

create index financial_parameter_sets_status_effective_from_idx
  on public.financial_parameter_sets (status, effective_from desc);

create table public.commercial_policies (
  id bigint generated by default as identity,
  policy_type public.commercial_policy_type not null,
  scope_type public.commercial_policy_scope_type not null,
  model_brand text,
  model_name text,
  scope_snapshot jsonb not null,
  title text not null,
  description text,
  starts_on date not null,
  ends_on date,
  benefit_percentage numeric(9,6),
  down_payment_percentage numeric(9,6),
  term_months integer,
  customer_interest_rate_monthly numeric(9,6),
  calculation_method public.policy_calculation_method not null,
  financial_parameter_set_id bigint,
  status public.pricing_workflow_status not null default 'draft',
  source_type public.pricing_source_type not null,
  source_import_row_id bigint,
  supersedes_policy_id bigint,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  published_at timestamp with time zone,
  published_by uuid,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  lock_version integer not null default 1,
  constraint commercial_policies_pkey primary key (id),
  constraint commercial_policies_financial_parameter_set_id_fkey
    foreign key (financial_parameter_set_id)
    references public.financial_parameter_sets(id) on delete restrict,
  constraint commercial_policies_supersedes_policy_id_fkey foreign key (supersedes_policy_id)
    references public.commercial_policies(id) on delete restrict,
  constraint commercial_policies_reviewed_by_fkey foreign key (reviewed_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policies_published_by_fkey foreign key (published_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policies_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policies_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policies_title_check check (btrim(title) <> ''),
  constraint commercial_policies_dates_check check (ends_on is null or ends_on >= starts_on),
  constraint commercial_policies_benefit_percentage_check check (
    benefit_percentage is null or benefit_percentage between 0 and 100
  ),
  constraint commercial_policies_down_payment_percentage_check check (
    down_payment_percentage is null or down_payment_percentage between 0 and 100
  ),
  constraint commercial_policies_customer_interest_rate_monthly_check check (
    customer_interest_rate_monthly is null
    or customer_interest_rate_monthly between 0 and 100
  ),
  constraint commercial_policies_term_months_check check (
    term_months is null or term_months > 0
  ),
  constraint commercial_policies_scope_check check (
    (
      scope_type = 'model'
      and nullif(btrim(model_brand), '') is not null
      and nullif(btrim(model_name), '') is not null
    )
    or (
      scope_type = 'product_set'
      and model_brand is null
      and model_name is null
    )
  ),
  constraint commercial_policies_supersedes_policy_check check (
    supersedes_policy_id is null or supersedes_policy_id <> id
  ),
  constraint commercial_policies_source_import_check check (
    source_type = 'manual' or source_import_row_id is not null
  ),
  constraint commercial_policies_published_check check (
    status <> 'published' or (published_at is not null and published_by is not null)
  ),
  constraint commercial_policies_lock_version_check check (lock_version > 0)
);

create index commercial_policies_status_dates_idx
  on public.commercial_policies (status, starts_on, ends_on);
create index commercial_policies_policy_type_status_idx
  on public.commercial_policies (policy_type, status);
create index commercial_policies_model_scope_idx
  on public.commercial_policies (model_brand, model_name, starts_on)
  where scope_type = 'model';
create index commercial_policies_source_import_row_id_idx
  on public.commercial_policies (source_import_row_id)
  where source_import_row_id is not null;
create index commercial_policies_supersedes_policy_id_idx
  on public.commercial_policies (supersedes_policy_id);

create table public.commercial_policy_applications (
  id bigint generated by default as identity,
  policy_id bigint not null,
  product_id integer not null,
  basis_public_price_id bigint,
  input_monetary_value numeric(14,2),
  monetary_value numeric(14,2) not null,
  currency_code character(3) not null default 'BRL',
  calculation_snapshot jsonb not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  lock_version integer not null default 1,
  constraint commercial_policy_applications_pkey primary key (id),
  constraint commercial_policy_applications_policy_product_key unique (policy_id, product_id),
  constraint commercial_policy_applications_policy_id_fkey foreign key (policy_id)
    references public.commercial_policies(id) on delete cascade,
  constraint commercial_policy_applications_product_id_fkey foreign key (product_id)
    references public.products(id) on delete restrict,
  constraint commercial_policy_applications_basis_public_price_id_fkey
    foreign key (basis_public_price_id)
    references public.product_public_prices(id) on delete restrict,
  constraint commercial_policy_applications_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_applications_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_applications_input_monetary_value_check check (
    input_monetary_value is null or input_monetary_value >= 0
  ),
  constraint commercial_policy_applications_monetary_value_check check (monetary_value >= 0),
  constraint commercial_policy_applications_currency_code_check check (currency_code = 'BRL'),
  constraint commercial_policy_applications_lock_version_check check (lock_version > 0)
);

create index commercial_policy_applications_product_policy_idx
  on public.commercial_policy_applications (product_id, policy_id);
create index commercial_policy_applications_basis_public_price_id_idx
  on public.commercial_policy_applications (basis_public_price_id);
create index commercial_policy_applications_policy_id_idx
  on public.commercial_policy_applications (policy_id);

create table public.commercial_policy_accumulators (
  id bigint generated by default as identity,
  title text not null,
  description text,
  starts_on date not null,
  ends_on date,
  combination_fingerprint text,
  status public.pricing_workflow_status not null default 'draft',
  source_type public.pricing_source_type not null,
  source_import_row_id bigint,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  published_at timestamp with time zone,
  published_by uuid,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  lock_version integer not null default 1,
  constraint commercial_policy_accumulators_pkey primary key (id),
  constraint commercial_policy_accumulators_combination_fingerprint_key
    unique (combination_fingerprint),
  constraint commercial_policy_accumulators_reviewed_by_fkey foreign key (reviewed_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_accumulators_published_by_fkey foreign key (published_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_accumulators_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_accumulators_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_accumulators_title_check check (btrim(title) <> ''),
  constraint commercial_policy_accumulators_dates_check check (
    ends_on is null or ends_on >= starts_on
  ),
  constraint commercial_policy_accumulators_fingerprint_check check (
    combination_fingerprint is null or btrim(combination_fingerprint) <> ''
  ),
  constraint commercial_policy_accumulators_source_import_check check (
    source_type = 'manual' or source_import_row_id is not null
  ),
  constraint commercial_policy_accumulators_published_check check (
    status <> 'published'
    or (
      nullif(btrim(combination_fingerprint), '') is not null
      and published_at is not null
      and published_by is not null
    )
  ),
  constraint commercial_policy_accumulators_lock_version_check check (lock_version > 0)
);

create index commercial_policy_accumulators_status_dates_idx
  on public.commercial_policy_accumulators (status, starts_on, ends_on);
create index commercial_policy_accumulators_source_import_row_id_idx
  on public.commercial_policy_accumulators (source_import_row_id)
  where source_import_row_id is not null;

create table public.commercial_policy_accumulator_items (
  accumulator_id bigint not null,
  policy_id bigint not null,
  position smallint not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  constraint commercial_policy_accumulator_items_pkey primary key (accumulator_id, policy_id),
  constraint commercial_policy_accumulator_items_accumulator_position_key
    unique (accumulator_id, position),
  constraint commercial_policy_accumulator_items_accumulator_id_fkey
    foreign key (accumulator_id)
    references public.commercial_policy_accumulators(id) on delete cascade,
  constraint commercial_policy_accumulator_items_policy_id_fkey foreign key (policy_id)
    references public.commercial_policies(id) on delete restrict,
  constraint commercial_policy_accumulator_items_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_accumulator_items_position_check check (position > 0)
);

create index commercial_policy_accumulator_items_policy_accumulator_idx
  on public.commercial_policy_accumulator_items (policy_id, accumulator_id);

create table public.commercial_policy_accumulator_values (
  id bigint generated by default as identity,
  accumulator_id bigint not null,
  product_id integer not null,
  monetary_value numeric(14,2) not null,
  currency_code character(3) not null default 'BRL',
  calculation_snapshot jsonb not null,
  created_at timestamp with time zone not null default now(),
  created_by uuid,
  updated_at timestamp with time zone not null default now(),
  updated_by uuid,
  constraint commercial_policy_accumulator_values_pkey primary key (id),
  constraint commercial_policy_accumulator_values_accumulator_product_key
    unique (accumulator_id, product_id),
  constraint commercial_policy_accumulator_values_accumulator_id_fkey
    foreign key (accumulator_id)
    references public.commercial_policy_accumulators(id) on delete cascade,
  constraint commercial_policy_accumulator_values_product_id_fkey foreign key (product_id)
    references public.products(id) on delete restrict,
  constraint commercial_policy_accumulator_values_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_accumulator_values_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint commercial_policy_accumulator_values_monetary_value_check check (
    monetary_value >= 0
  ),
  constraint commercial_policy_accumulator_values_currency_code_check check (
    currency_code = 'BRL'
  )
);

create index commercial_policy_accumulator_values_product_accumulator_idx
  on public.commercial_policy_accumulator_values (product_id, accumulator_id);
create index commercial_policy_accumulator_values_accumulator_id_idx
  on public.commercial_policy_accumulator_values (accumulator_id);
