create function public.is_valid_import_artifact_usage(p_usage jsonb)
returns boolean language sql immutable security invoker set search_path='' as $$
  select pg_catalog.jsonb_typeof(p_usage)='object'
    and not exists (
      select 1 from pg_catalog.jsonb_object_keys(p_usage) as key
      where key not in ('inputUnits','outputUnits','totalUnits')
    )
    and not exists (
      select 1 from pg_catalog.jsonb_each(p_usage) as item
      where pg_catalog.jsonb_typeof(item.value)<>'number'
        or (item.value::text)::numeric<0
        or pg_catalog.trunc((item.value::text)::numeric)<>(item.value::text)::numeric
    )
$$;

create table public.pricing_import_processing_artifacts (
  id bigint generated by default as identity primary key,
  artifact_key text not null unique check (artifact_key ~ '^artifact-[0-9a-f]{64}$'),
  batch_id bigint not null references public.pricing_import_batches(id) on delete restrict,
  processing_job_id bigint not null references public.pricing_import_processing_jobs(id) on delete restrict,
  document_id bigint references public.pricing_import_documents(id) on delete restrict,
  unit_id text check (unit_id is null or unit_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  stage text not null check (stage in ('document_map','unit_plan','unit_extraction','merge','semantic_reconciliation','domain_mapping')),
  status text not null default 'queued' check (status in ('queued','processing','succeeded','failed')),
  manifest_schema_version text not null check (manifest_schema_version='SegmentedImportArtifactManifest/1'),
  artifact_schema_version text not null check (nullif(pg_catalog.btrim(artifact_schema_version),'') is not null and pg_catalog.length(artifact_schema_version)<=128),
  artifact_version integer not null check (artifact_version>=1),
  pipeline_version text not null check (pipeline_version='segmented-import/1'),
  attempt integer not null check (attempt>=1),
  correlation_id uuid not null,
  content_sha256 character(64) not null check (pg_catalog.btrim(content_sha256) ~ '^[0-9a-f]{64}$'),
  content_size_bytes bigint not null check (content_size_bytes between 0 and 8388608),
  storage_bucket text not null check (storage_bucket='import-processing-artifacts'),
  storage_object_path text not null,
  idempotency_key text not null unique check (idempotency_key ~ '^segmented-artifact-[0-9a-f]{64}$'),
  retry_of_artifact_id bigint references public.pricing_import_processing_artifacts(id) on delete restrict,
  supersedes_artifact_id bigint references public.pricing_import_processing_artifacts(id) on delete restrict,
  provider text check (provider is null or provider ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'),
  provider_version text check (provider_version is null or provider_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  prompt_version text check (prompt_version is null or prompt_version ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  model text check (model is null or model ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$'),
  provider_run_id text check (provider_run_id is null or provider_run_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$'),
  usage_metadata jsonb not null default '{}'::jsonb,
  duration_ms integer check (duration_ms is null or duration_ms>=0),
  error_code text check (error_code is null or error_code ~ '^[A-Z0-9_]{1,64}$'),
  error_message text check (error_message is null or (nullif(pg_catalog.btrim(error_message),'') is not null and pg_catalog.length(error_message)<=500)),
  created_at timestamptz not null default pg_catalog.now(),
  started_at timestamptz,
  completed_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default pg_catalog.now(),
  updated_by uuid references public.profiles(id) on delete set null,
  lock_version integer not null default 1 check (lock_version>=1),
  constraint pricing_import_processing_artifacts_storage_path_check check (
    storage_object_path = batch_id::text||'/'||processing_job_id::text||'/'||stage||'/'||artifact_key||'.json'
    and storage_object_path !~ '(^|/)\.\.(/|$)'
  ),
  constraint pricing_import_processing_artifacts_identity_check check (
    retry_of_artifact_id is distinct from id and supersedes_artifact_id is distinct from id
  ),
  constraint pricing_import_processing_artifacts_provider_stage_check check (
    stage in ('document_map','unit_extraction')
    or (provider is null and provider_version is null and prompt_version is null and model is null
      and provider_run_id is null and usage_metadata='{}'::jsonb and duration_ms is null)
  ),
  constraint pricing_import_processing_artifacts_usage_check check (public.is_valid_import_artifact_usage(usage_metadata)),
  constraint pricing_import_processing_artifacts_lifecycle_check check (
    (status='queued' and started_at is null and completed_at is null and error_code is null and error_message is null)
    or (status='processing' and started_at is not null and completed_at is null and error_code is null and error_message is null)
    or (status='succeeded' and started_at is not null and completed_at is not null and error_code is null and error_message is null)
    or (status='failed' and completed_at is not null and error_code is not null and error_message is not null)
  )
);

create index pricing_import_processing_artifacts_job_stage_idx
  on public.pricing_import_processing_artifacts(processing_job_id,stage,status,artifact_version desc,attempt desc);
create index pricing_import_processing_artifacts_batch_created_idx
  on public.pricing_import_processing_artifacts(batch_id,created_at desc);
create index pricing_import_processing_artifacts_retry_idx
  on public.pricing_import_processing_artifacts(retry_of_artifact_id) where retry_of_artifact_id is not null;
create unique index pricing_import_processing_artifacts_storage_key
  on public.pricing_import_processing_artifacts(storage_bucket,storage_object_path);

create table public.pricing_import_processing_artifact_dependencies (
  artifact_id bigint not null references public.pricing_import_processing_artifacts(id) on delete restrict,
  source_artifact_id bigint not null references public.pricing_import_processing_artifacts(id) on delete restrict,
  ordinal integer not null check (ordinal>=0),
  created_at timestamptz not null default pg_catalog.now(),
  primary key(artifact_id,source_artifact_id),
  unique(artifact_id,ordinal),
  check (artifact_id<>source_artifact_id)
);
create index pricing_import_processing_artifact_dependencies_source_idx
  on public.pricing_import_processing_artifact_dependencies(source_artifact_id);

create function public.protect_import_processing_artifact()
returns trigger language plpgsql security invoker set search_path='' as $$
begin
  if tg_op='DELETE' then raise exception using errcode='55000',message='processing artifacts are retained for audit'; end if;
  if old.status in ('succeeded','failed') then raise exception using errcode='55000',message='terminal processing artifact is immutable'; end if;
  if new.artifact_key is distinct from old.artifact_key or new.batch_id is distinct from old.batch_id
    or new.processing_job_id is distinct from old.processing_job_id or new.document_id is distinct from old.document_id
    or new.unit_id is distinct from old.unit_id or new.stage is distinct from old.stage
    or new.manifest_schema_version is distinct from old.manifest_schema_version
    or new.artifact_schema_version is distinct from old.artifact_schema_version
    or new.artifact_version is distinct from old.artifact_version or new.pipeline_version is distinct from old.pipeline_version
    or new.attempt is distinct from old.attempt or new.correlation_id is distinct from old.correlation_id
    or new.idempotency_key is distinct from old.idempotency_key or new.retry_of_artifact_id is distinct from old.retry_of_artifact_id
    or new.supersedes_artifact_id is distinct from old.supersedes_artifact_id
    or new.content_sha256 is distinct from old.content_sha256 or new.content_size_bytes is distinct from old.content_size_bytes
    or new.storage_bucket is distinct from old.storage_bucket or new.storage_object_path is distinct from old.storage_object_path
    or new.provider is distinct from old.provider or new.provider_version is distinct from old.provider_version
    or new.prompt_version is distinct from old.prompt_version or new.model is distinct from old.model
  then raise exception using errcode='55000',message='processing artifact identity is immutable'; end if;
  if old.status='queued' and new.status not in ('processing','failed')
    or old.status='processing' and new.status not in ('succeeded','failed')
  then raise exception using errcode='55000',message='invalid processing artifact lifecycle transition'; end if;
  return new;
end $$;

create function public.validate_import_processing_artifact_dependency()
returns trigger language plpgsql security invoker set search_path='' as $$
declare target public.pricing_import_processing_artifacts%rowtype; source public.pricing_import_processing_artifacts%rowtype; expected text;
begin
  if new.artifact_id=new.source_artifact_id then raise exception using errcode='23514',message='artifact self dependency is forbidden'; end if;
  select * into target from public.pricing_import_processing_artifacts where id=new.artifact_id;
  select * into source from public.pricing_import_processing_artifacts where id=new.source_artifact_id;
  if target.status<>'queued' then raise exception using errcode='55000',message='dependencies can only be attached while artifact is queued'; end if;
  if source.status<>'succeeded' then raise exception using errcode='55000',message='artifact dependency must be succeeded'; end if;
  if source.batch_id<>target.batch_id or source.processing_job_id<>target.processing_job_id then raise exception using errcode='23514',message='artifact dependency must belong to the same batch and job'; end if;
  if exists(
    with recursive ancestry(id) as (
      select new.source_artifact_id union
      select d.source_artifact_id from public.pricing_import_processing_artifact_dependencies d join ancestry a on d.artifact_id=a.id
    ) select 1 from ancestry where id=new.artifact_id
  ) then raise exception using errcode='23514',message='artifact dependency cycle is forbidden'; end if;
  expected:=case target.stage when 'unit_plan' then 'document_map' when 'unit_extraction' then 'unit_plan'
    when 'merge' then 'unit_extraction' when 'semantic_reconciliation' then 'merge' when 'domain_mapping' then 'semantic_reconciliation' end;
  if expected is null or source.stage<>expected then raise exception using errcode='23514',message='artifact dependency stage is incompatible'; end if;
  return new;
end $$;

create function public.protect_import_processing_artifact_dependency()
returns trigger language plpgsql security invoker set search_path='' as $$
begin raise exception using errcode='55000',message='artifact dependencies are immutable'; end $$;

create trigger pricing_import_processing_artifacts_set_updated_at before update on public.pricing_import_processing_artifacts
for each row execute function public.set_pricing_updated_at();
create trigger pricing_import_processing_artifacts_protect before update or delete on public.pricing_import_processing_artifacts
for each row execute function public.protect_import_processing_artifact();
create trigger pricing_import_processing_artifact_dependencies_validate before insert on public.pricing_import_processing_artifact_dependencies
for each row execute function public.validate_import_processing_artifact_dependency();
create trigger pricing_import_processing_artifact_dependencies_protect before update or delete on public.pricing_import_processing_artifact_dependencies
for each row execute function public.protect_import_processing_artifact_dependency();

alter table public.pricing_audit_events drop constraint pricing_audit_events_aggregate_type_check;
alter table public.pricing_audit_events add constraint pricing_audit_events_aggregate_type_check check (
  aggregate_type in ('product_public_price','financial_parameter_set','commercial_policy','commercial_policy_application',
  'commercial_policy_accumulator','commercial_offer','pricing_import_batch','pricing_import_row','pricing_import_document',
  'pricing_import_processing_job','pricing_import_processing_artifact')
);

create function public.reserve_import_processing_artifact(
  p_artifact_key text,p_batch_id bigint,p_processing_job_id bigint,p_document_id bigint,p_unit_id text,p_stage text,
  p_manifest_schema_version text,p_artifact_schema_version text,p_artifact_version integer,p_pipeline_version text,p_attempt integer,
  p_content_sha256 text,p_content_size_bytes bigint,p_storage_bucket text,p_storage_object_path text,p_idempotency_key text,
  p_retry_of_artifact_id bigint,p_supersedes_artifact_id bigint,p_provider text,p_provider_version text,p_prompt_version text,p_model text,
  p_source_artifact_ids bigint[],p_claim_token uuid,p_expected_job_lock_version integer,p_actor_id uuid,p_correlation_id uuid
) returns jsonb language plpgsql security definer set search_path='' as $$
declare j public.pricing_import_processing_jobs%rowtype; a public.pricing_import_processing_artifacts%rowtype; source_id bigint; position integer:=0;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  select * into j from public.pricing_import_processing_jobs where id=p_processing_job_id for update;
  if not found or j.batch_id<>p_batch_id then raise exception using errcode='23503',message='artifact job and batch are invalid'; end if;
  if j.status<>'processing' or j.claim_token<>p_claim_token or j.claim_expires_at<=pg_catalog.now() then raise exception using errcode='55000',message='processing claim is invalid or expired'; end if;
  if j.lock_version<>p_expected_job_lock_version or j.correlation_id<>p_correlation_id then raise exception using errcode='40001',message='stale artifact job context'; end if;
  select * into a from public.pricing_import_processing_artifacts where idempotency_key=p_idempotency_key;
  if found then return pg_catalog.jsonb_build_object('artifactId',a.id,'artifactKey',a.artifact_key,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',true); end if;
  if p_document_id is not null and not exists(select 1 from public.pricing_import_documents where id=p_document_id and batch_id=p_batch_id) then
    raise exception using errcode='23503',message='artifact document is invalid';
  end if;
  if p_stage='document_map' and coalesce(pg_catalog.array_length(p_source_artifact_ids,1),0)<>0
    or p_stage<>'document_map' and coalesce(pg_catalog.array_length(p_source_artifact_ids,1),0)=0
  then raise exception using errcode='23514',message='artifact dependency cardinality is invalid'; end if;
  if p_retry_of_artifact_id is not null and not exists(select 1 from public.pricing_import_processing_artifacts where id=p_retry_of_artifact_id and status='failed' and batch_id=p_batch_id and processing_job_id=p_processing_job_id and stage=p_stage and attempt+1=p_attempt)
  then raise exception using errcode='23514',message='artifact retry lineage is invalid'; end if;
  if p_supersedes_artifact_id is not null and not exists(select 1 from public.pricing_import_processing_artifacts where id=p_supersedes_artifact_id and status='succeeded' and batch_id=p_batch_id and processing_job_id=p_processing_job_id and stage=p_stage)
  then raise exception using errcode='23514',message='artifact supersession lineage is invalid'; end if;
  insert into public.pricing_import_processing_artifacts(artifact_key,batch_id,processing_job_id,document_id,unit_id,stage,
    manifest_schema_version,artifact_schema_version,artifact_version,pipeline_version,attempt,correlation_id,content_sha256,
    content_size_bytes,storage_bucket,storage_object_path,idempotency_key,retry_of_artifact_id,supersedes_artifact_id,
    provider,provider_version,prompt_version,model,created_by,updated_by)
  values(p_artifact_key,p_batch_id,p_processing_job_id,p_document_id,p_unit_id,p_stage,p_manifest_schema_version,
    p_artifact_schema_version,p_artifact_version,p_pipeline_version,p_attempt,p_correlation_id,p_content_sha256,
    p_content_size_bytes,p_storage_bucket,p_storage_object_path,p_idempotency_key,p_retry_of_artifact_id,p_supersedes_artifact_id,
    p_provider,p_provider_version,p_prompt_version,p_model,p_actor_id,p_actor_id) returning * into a;
  foreach source_id in array coalesce(p_source_artifact_ids,array[]::bigint[]) loop
    insert into public.pricing_import_processing_artifact_dependencies(artifact_id,source_artifact_id,ordinal) values(a.id,source_id,position);
    position:=position+1;
  end loop;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id)
  values('pricing_import_processing_artifact',a.id,'insert',pg_catalog.jsonb_build_object('artifactId',a.id,'stage',a.stage,'attempt',a.attempt,'status',a.status),
    case when a.retry_of_artifact_id is not null then 'artifact retried' when a.supersedes_artifact_id is not null then 'artifact superseded' else 'artifact queued' end,p_actor_id,p_correlation_id);
  return pg_catalog.jsonb_build_object('artifactId',a.id,'artifactKey',a.artifact_key,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',false);
exception when unique_violation then
  select * into a from public.pricing_import_processing_artifacts where idempotency_key=p_idempotency_key;
  if found then return pg_catalog.jsonb_build_object('artifactId',a.id,'artifactKey',a.artifact_key,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',true); end if;
  raise;
end $$;

create function public.start_import_processing_artifact(p_artifact_id bigint,p_claim_token uuid,p_expected_lock_version integer,p_actor_id uuid,p_correlation_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare a public.pricing_import_processing_artifacts%rowtype; j public.pricing_import_processing_jobs%rowtype;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  select * into a from public.pricing_import_processing_artifacts where id=p_artifact_id for update;
  if not found then raise exception using errcode='P0002',message='processing artifact not found'; end if;
  if a.status='processing' then return pg_catalog.jsonb_build_object('artifactId',a.id,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',true); end if;
  select * into j from public.pricing_import_processing_jobs where id=a.processing_job_id;
  if j.status<>'processing' or j.claim_token<>p_claim_token or j.claim_expires_at<=pg_catalog.now() or a.correlation_id<>p_correlation_id then raise exception using errcode='55000',message='processing claim is invalid or expired'; end if;
  if a.status<>'queued' or a.lock_version<>p_expected_lock_version then raise exception using errcode='40001',message='stale artifact lock version'; end if;
  update public.pricing_import_processing_artifacts set status='processing',started_at=pg_catalog.now(),updated_by=p_actor_id where id=a.id returning * into a;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id)
  values('pricing_import_processing_artifact',a.id,'update',pg_catalog.jsonb_build_object('artifactId',a.id,'stage',a.stage,'attempt',a.attempt,'status',a.status),'artifact processing',p_actor_id,p_correlation_id);
  return pg_catalog.jsonb_build_object('artifactId',a.id,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',false);
end $$;

create function public.succeed_import_processing_artifact(p_artifact_id bigint,p_claim_token uuid,p_expected_lock_version integer,
  p_content_sha256 text,p_content_size_bytes bigint,p_storage_bucket text,p_storage_object_path text,p_provider_run_id text,
  p_usage_metadata jsonb,p_duration_ms integer,p_actor_id uuid,p_correlation_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare a public.pricing_import_processing_artifacts%rowtype; j public.pricing_import_processing_jobs%rowtype;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  select * into a from public.pricing_import_processing_artifacts where id=p_artifact_id for update;
  if not found then raise exception using errcode='P0002',message='processing artifact not found'; end if;
  if a.status='succeeded' and a.content_sha256=p_content_sha256::character(64) and a.content_size_bytes=p_content_size_bytes and a.storage_bucket=p_storage_bucket and a.storage_object_path=p_storage_object_path
  then return pg_catalog.jsonb_build_object('artifactId',a.id,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',true); end if;
  select * into j from public.pricing_import_processing_jobs where id=a.processing_job_id;
  if j.status<>'processing' or j.claim_token<>p_claim_token or j.claim_expires_at<=pg_catalog.now() or a.correlation_id<>p_correlation_id then raise exception using errcode='55000',message='processing claim is invalid or expired'; end if;
  if a.status<>'processing' or a.lock_version<>p_expected_lock_version then raise exception using errcode='40001',message='stale artifact lock version'; end if;
  if a.content_sha256<>p_content_sha256::character(64) or a.content_size_bytes<>p_content_size_bytes or a.storage_bucket<>p_storage_bucket or a.storage_object_path<>p_storage_object_path
  then raise exception using errcode='23514',message='verified artifact metadata does not match reservation'; end if;
  update public.pricing_import_processing_artifacts set status='succeeded',completed_at=pg_catalog.now(),provider_run_id=nullif(p_provider_run_id,''),
    usage_metadata=coalesce(p_usage_metadata,'{}'::jsonb),duration_ms=p_duration_ms,updated_by=p_actor_id where id=a.id returning * into a;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id)
  values('pricing_import_processing_artifact',a.id,'update',pg_catalog.jsonb_build_object('artifactId',a.id,'stage',a.stage,'attempt',a.attempt,'status',a.status,'contentSize',a.content_size_bytes,'usage',a.usage_metadata,'durationMs',a.duration_ms),'artifact succeeded',p_actor_id,p_correlation_id);
  return pg_catalog.jsonb_build_object('artifactId',a.id,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',false);
end $$;

create function public.fail_import_processing_artifact(p_artifact_id bigint,p_claim_token uuid,p_expected_lock_version integer,
  p_error_code text,p_error_message text,p_duration_ms integer,p_actor_id uuid,p_correlation_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare a public.pricing_import_processing_artifacts%rowtype; j public.pricing_import_processing_jobs%rowtype; safe_code text; safe_message text;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  safe_code:=pg_catalog.left(pg_catalog.upper(pg_catalog.regexp_replace(coalesce(p_error_code,''),'[^A-Za-z0-9_]','','g')),64);
  safe_message:=pg_catalog.left(pg_catalog.regexp_replace(coalesce(p_error_message,''),'(authorization[[:space:]]*:[[:space:]]*(bearer[[:space:]]+)?|apikey[[:space:]]*[:=][[:space:]]*|service[_-]?role[[:space:]]*[:=][[:space:]]*|bearer[[:space:]]+|sk-|sb_secret_|eyJ|postgres(?:ql)?://)[^[:space:]]+','[REDACTED]','gi'),500);
  if safe_code='' or nullif(pg_catalog.btrim(safe_message),'') is null then raise exception using errcode='22023',message='safe artifact diagnostic is required'; end if;
  select * into a from public.pricing_import_processing_artifacts where id=p_artifact_id for update;
  if not found then raise exception using errcode='P0002',message='processing artifact not found'; end if;
  if a.status='failed' then return pg_catalog.jsonb_build_object('artifactId',a.id,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',true); end if;
  select * into j from public.pricing_import_processing_jobs where id=a.processing_job_id;
  if j.status<>'processing' or j.claim_token<>p_claim_token or j.claim_expires_at<=pg_catalog.now() or a.correlation_id<>p_correlation_id then raise exception using errcode='55000',message='processing claim is invalid or expired'; end if;
  if a.status not in ('queued','processing') or a.lock_version<>p_expected_lock_version then raise exception using errcode='40001',message='stale artifact lock version'; end if;
  update public.pricing_import_processing_artifacts set status='failed',started_at=coalesce(started_at,pg_catalog.now()),completed_at=pg_catalog.now(),
    error_code=safe_code,error_message=safe_message,duration_ms=p_duration_ms,updated_by=p_actor_id where id=a.id returning * into a;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id)
  values('pricing_import_processing_artifact',a.id,'update',pg_catalog.jsonb_build_object('artifactId',a.id,'stage',a.stage,'attempt',a.attempt,'status',a.status,'errorCode',a.error_code,'durationMs',a.duration_ms),'artifact failed',p_actor_id,p_correlation_id);
  return pg_catalog.jsonb_build_object('artifactId',a.id,'status',a.status,'lockVersion',a.lock_version,'idempotentReplay',false);
end $$;

create function public.attach_import_processing_artifact_dependencies(p_artifact_id bigint,p_source_artifact_ids bigint[],p_actor_id uuid,p_correlation_id uuid)
returns integer language plpgsql security definer set search_path='' as $$
declare a public.pricing_import_processing_artifacts%rowtype; source_id bigint; position integer; inserted_count integer:=0;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  select * into a from public.pricing_import_processing_artifacts where id=p_artifact_id for update;
  if not found or a.correlation_id<>p_correlation_id then raise exception using errcode='P0002',message='processing artifact context not found'; end if;
  position:=coalesce((select max(ordinal)+1 from public.pricing_import_processing_artifact_dependencies where artifact_id=p_artifact_id),0);
  foreach source_id in array coalesce(p_source_artifact_ids,array[]::bigint[]) loop
    insert into public.pricing_import_processing_artifact_dependencies(artifact_id,source_artifact_id,ordinal) values(p_artifact_id,source_id,position) on conflict(artifact_id,source_artifact_id) do nothing;
    if found then inserted_count:=inserted_count+1; position:=position+1; end if;
  end loop;
  return inserted_count;
end $$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('import-processing-artifacts','import-processing-artifacts',false,8388608,array['application/json']::text[])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

alter table public.pricing_import_processing_artifacts enable row level security;
alter table public.pricing_import_processing_artifact_dependencies enable row level security;
revoke all on table public.pricing_import_processing_artifacts from public,anon,authenticated,service_role;
revoke all on table public.pricing_import_processing_artifact_dependencies from public,anon,authenticated,service_role;
revoke all on sequence public.pricing_import_processing_artifacts_id_seq from public,anon,authenticated,service_role;
grant select,insert,update on table public.pricing_import_processing_artifacts to service_role;
grant select,insert on table public.pricing_import_processing_artifact_dependencies to service_role;
grant usage,select on sequence public.pricing_import_processing_artifacts_id_seq to service_role;
revoke all on function public.is_valid_import_artifact_usage(jsonb) from public,anon,authenticated,service_role;
grant execute on function public.is_valid_import_artifact_usage(jsonb) to service_role;
revoke all on function public.protect_import_processing_artifact() from public,anon,authenticated,service_role;
revoke all on function public.validate_import_processing_artifact_dependency() from public,anon,authenticated,service_role;
revoke all on function public.protect_import_processing_artifact_dependency() from public,anon,authenticated,service_role;

revoke all on function public.reserve_import_processing_artifact(text,bigint,bigint,bigint,text,text,text,text,integer,text,integer,text,bigint,text,text,text,bigint,bigint,text,text,text,text,bigint[],uuid,integer,uuid,uuid) from public,anon,authenticated,service_role;
revoke all on function public.start_import_processing_artifact(bigint,uuid,integer,uuid,uuid) from public,anon,authenticated,service_role;
revoke all on function public.succeed_import_processing_artifact(bigint,uuid,integer,text,bigint,text,text,text,jsonb,integer,uuid,uuid) from public,anon,authenticated,service_role;
revoke all on function public.fail_import_processing_artifact(bigint,uuid,integer,text,text,integer,uuid,uuid) from public,anon,authenticated,service_role;
revoke all on function public.attach_import_processing_artifact_dependencies(bigint,bigint[],uuid,uuid) from public,anon,authenticated,service_role;
grant execute on function public.reserve_import_processing_artifact(text,bigint,bigint,bigint,text,text,text,text,integer,text,integer,text,bigint,text,text,text,bigint,bigint,text,text,text,text,bigint[],uuid,integer,uuid,uuid) to service_role;
grant execute on function public.start_import_processing_artifact(bigint,uuid,integer,uuid,uuid) to service_role;
grant execute on function public.succeed_import_processing_artifact(bigint,uuid,integer,text,bigint,text,text,text,jsonb,integer,uuid,uuid) to service_role;
grant execute on function public.fail_import_processing_artifact(bigint,uuid,integer,text,text,integer,uuid,uuid) to service_role;
grant execute on function public.attach_import_processing_artifact_dependencies(bigint,bigint[],uuid,uuid) to service_role;
