alter type public.pricing_source_type add value if not exists 'document_upload';

create type public.pricing_import_document_status as enum (
  'uploaded',
  'validated',
  'ready',
  'processing',
  'processed',
  'failed',
  'rejected',
  'archived'
);

create type public.pricing_import_document_type as enum (
  'pdf',
  'image',
  'spreadsheet',
  'csv',
  'json',
  'xml',
  'api',
  'crawler',
  'other'
);

create type public.pricing_import_document_role as enum (
  'primary',
  'errata',
  'complement',
  'financial_appendix',
  'trade_in_appendix',
  'technical_appendix',
  'other'
);

alter table public.pricing_import_batches
  add column plugin_key text not null default 'pricing_workflow',
  add column dossier_title text,
  add column competence date,
  add column notes text;

alter table public.pricing_import_batches
  add constraint pricing_import_batches_plugin_key_check check (
    plugin_key ~ '^[a-z][a-z0-9_]{1,63}$'
  ),
  add constraint pricing_import_batches_dossier_title_check check (
    dossier_title is null or nullif(pg_catalog.btrim(dossier_title), '') is not null
  ),
  add constraint pricing_import_batches_competence_check check (
    competence is null or competence = pg_catalog.date_trunc('month', competence)::date
  ),
  add constraint pricing_import_batches_notes_check check (
    notes is null or nullif(pg_catalog.btrim(notes), '') is not null
  );

create index pricing_import_batches_plugin_competence_updated_idx
  on public.pricing_import_batches (plugin_key, competence, updated_at desc);

create table public.pricing_import_documents (
  id bigint generated by default as identity,
  batch_id bigint not null,
  document_type public.pricing_import_document_type not null,
  original_file_name text not null,
  storage_bucket text not null,
  storage_object_path text not null,
  mime_type text not null,
  file_size_bytes bigint not null,
  content_sha256 character(64) not null,
  page_count integer,
  status public.pricing_import_document_status not null default 'uploaded',
  source_order integer not null,
  document_role public.pricing_import_document_role not null,
  provider_metadata jsonb not null default '{}'::jsonb,
  index_payload jsonb not null default '{}'::jsonb,
  error_code text,
  error_message text,
  lock_version integer not null default 1,
  created_at timestamp with time zone not null default pg_catalog.now(),
  updated_at timestamp with time zone not null default pg_catalog.now(),
  created_by uuid,
  updated_by uuid,
  constraint pricing_import_documents_pkey primary key (id),
  constraint pricing_import_documents_batch_id_fkey foreign key (batch_id)
    references public.pricing_import_batches(id) on delete restrict,
  constraint pricing_import_documents_created_by_fkey foreign key (created_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_documents_updated_by_fkey foreign key (updated_by)
    references public.profiles(id) on delete set null,
  constraint pricing_import_documents_original_file_name_check check (
    nullif(pg_catalog.btrim(original_file_name), '') is not null
    and pg_catalog.length(original_file_name) <= 255
  ),
  constraint pricing_import_documents_storage_bucket_check check (
    storage_bucket = 'import-engine-documents'
  ),
  constraint pricing_import_documents_storage_object_path_check check (
    storage_object_path ~ '^commercial_letters/[0-9a-f-]{36}/[0-9a-f-]{36}/[A-Za-z0-9._-]+$'
    and storage_object_path !~ '(^|/)\.\.(/|$)'
  ),
  constraint pricing_import_documents_mime_type_check check (
    mime_type = 'application/pdf'
  ),
  constraint pricing_import_documents_file_size_check check (
    file_size_bytes > 0 and file_size_bytes <= 33554432
  ),
  constraint pricing_import_documents_hash_check check (
    pg_catalog.btrim(content_sha256) ~ '^[0-9a-f]{64}$'
  ),
  constraint pricing_import_documents_page_count_check check (
    page_count is null or page_count > 0
  ),
  constraint pricing_import_documents_source_order_check check (source_order > 0),
  constraint pricing_import_documents_json_check check (
    pg_catalog.jsonb_typeof(provider_metadata) = 'object'
    and pg_catalog.jsonb_typeof(index_payload) = 'object'
  ),
  constraint pricing_import_documents_error_check check (
    (status = 'failed' and nullif(pg_catalog.btrim(error_code), '') is not null
      and nullif(pg_catalog.btrim(error_message), '') is not null)
    or (status <> 'failed' and error_code is null and error_message is null)
  ),
  constraint pricing_import_documents_lock_version_check check (lock_version > 0),
  constraint pricing_import_documents_batch_hash_key unique (batch_id, content_sha256),
  constraint pricing_import_documents_batch_source_order_key unique (batch_id, source_order),
  constraint pricing_import_documents_storage_object_key unique (storage_bucket, storage_object_path)
);

create index pricing_import_documents_batch_status_order_idx
  on public.pricing_import_documents (batch_id, status, source_order);
create index pricing_import_documents_content_sha256_idx
  on public.pricing_import_documents (content_sha256);

alter table public.pricing_audit_events
  drop constraint pricing_audit_events_aggregate_type_check;
alter table public.pricing_audit_events
  add constraint pricing_audit_events_aggregate_type_check check (
    aggregate_type in (
      'product_public_price',
      'financial_parameter_set',
      'commercial_policy',
      'commercial_policy_application',
      'commercial_policy_accumulator',
      'commercial_offer',
      'pricing_import_batch',
      'pricing_import_row',
      'pricing_import_document'
    )
  );

create function public.validate_pricing_import_document_lifecycle()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if old.status = new.status then
    return new;
  end if;
  if old.status = 'uploaded' and new.status not in ('validated', 'failed', 'rejected', 'archived')
     or old.status = 'validated' and new.status not in ('ready', 'failed', 'rejected', 'archived')
     or old.status = 'ready' and new.status not in ('processing', 'failed', 'rejected', 'archived')
     or old.status = 'processing' and new.status not in ('processed', 'failed')
     or old.status = 'processed' and new.status <> 'archived'
     or old.status = 'failed' and new.status not in ('uploaded', 'rejected', 'archived')
     or old.status = 'rejected' and new.status <> 'archived'
     or old.status = 'archived' then
    raise exception using errcode = '55000', message = 'invalid pricing import document lifecycle transition';
  end if;
  return new;
end;
$$;

create function public.protect_pricing_import_document()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    raise exception using errcode = '55000', message = 'pricing import documents are retained for audit';
  end if;
  if old.status in ('processing', 'processed', 'archived') and (
    new.batch_id is distinct from old.batch_id
    or new.document_type is distinct from old.document_type
    or new.original_file_name is distinct from old.original_file_name
    or new.storage_bucket is distinct from old.storage_bucket
    or new.storage_object_path is distinct from old.storage_object_path
    or new.mime_type is distinct from old.mime_type
    or new.file_size_bytes is distinct from old.file_size_bytes
    or new.content_sha256 is distinct from old.content_sha256
    or new.source_order is distinct from old.source_order
    or new.document_role is distinct from old.document_role
  ) then
    raise exception using errcode = '55000', message = 'processed import document identity is immutable';
  end if;
  return new;
end;
$$;

create function public.protect_import_engine_batch_identity()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if old.status in ('promoted', 'archived') and (
    new.plugin_key is distinct from old.plugin_key
    or new.dossier_title is distinct from old.dossier_title
    or new.competence is distinct from old.competence
    or new.notes is distinct from old.notes
  ) then
    raise exception using errcode = '55000', message = 'terminal import batch dossier identity is immutable';
  end if;
  return new;
end;
$$;

create trigger pricing_import_documents_set_updated_at
before update on public.pricing_import_documents
for each row execute function public.set_pricing_updated_at();
create trigger pricing_import_documents_validate_lifecycle
before update on public.pricing_import_documents
for each row execute function public.validate_pricing_import_document_lifecycle();
create trigger pricing_import_documents_protect
before update or delete on public.pricing_import_documents
for each row execute function public.protect_pricing_import_document();
create trigger pricing_import_batches_protect_dossier_identity
before update on public.pricing_import_batches
for each row execute function public.protect_import_engine_batch_identity();

create function public.create_import_engine_batch(
  p_title text,
  p_plugin_key text,
  p_competence date,
  p_notes text,
  p_idempotency_key text,
  p_documents jsonb,
  p_actor_id uuid,
  p_correlation_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  batch_record public.pricing_import_batches%rowtype;
  document_record public.pricing_import_documents%rowtype;
  item jsonb;
  document_ids jsonb := '[]'::jsonb;
  total integer;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  if p_correlation_id is null or nullif(pg_catalog.btrim(p_idempotency_key), '') is null then
    raise exception using errcode = '22004', message = 'import batch requires correlation and idempotency keys';
  end if;
  select * into batch_record from public.pricing_import_batches
    where idempotency_key = pg_catalog.btrim(p_idempotency_key);
  if found then
    return pg_catalog.jsonb_build_object(
      'batchId', batch_record.id, 'status', batch_record.status,
      'documentIds', coalesce((select pg_catalog.jsonb_agg(id order by source_order)
        from public.pricing_import_documents where batch_id = batch_record.id), '[]'::jsonb),
      'idempotentReplay', true
    );
  end if;
  if p_plugin_key <> 'commercial_letters' then
    raise exception using errcode = '22023', message = 'unsupported import plugin';
  end if;
  if nullif(pg_catalog.btrim(p_title), '') is null or pg_catalog.length(pg_catalog.btrim(p_title)) > 160 then
    raise exception using errcode = '22023', message = 'invalid import dossier title';
  end if;
  if p_competence is null or p_competence <> pg_catalog.date_trunc('month', p_competence)::date then
    raise exception using errcode = '22023', message = 'invalid import competence';
  end if;
  if pg_catalog.jsonb_typeof(p_documents) <> 'array' then
    raise exception using errcode = '22023', message = 'documents must be an array';
  end if;
  total := pg_catalog.jsonb_array_length(p_documents);
  if total < 1 or total > 20 then
    raise exception using errcode = '22023', message = 'an import dossier requires between 1 and 20 documents';
  end if;
  if exists (
    select 1 from pg_catalog.jsonb_array_elements(p_documents) d(value)
    group by value->>'contentSha256' having count(*) > 1
  ) or exists (
    select 1 from pg_catalog.jsonb_array_elements(p_documents) d(value)
    group by (value->>'sourceOrder')::integer having count(*) > 1
  ) then
    raise exception using errcode = '23505', message = 'duplicate document in import dossier';
  end if;
  for item in select value from pg_catalog.jsonb_array_elements(p_documents)
  loop
    if item->>'documentType' <> 'pdf'
       or item->>'mimeType' <> 'application/pdf'
       or item->>'storageBucket' <> 'import-engine-documents'
       or (item->>'fileSizeBytes')::bigint <= 0
       or (item->>'fileSizeBytes')::bigint > 33554432
       or item->>'contentSha256' !~ '^[0-9a-f]{64}$'
       or (item->>'sourceOrder')::integer <= 0
       or item->>'documentRole' not in (
         'primary','errata','complement','financial_appendix','trade_in_appendix','technical_appendix','other'
       ) then
      raise exception using errcode = '22023', message = 'invalid import document metadata';
    end if;
    if not exists (
      select 1 from storage.objects
      where bucket_id = item->>'storageBucket' and name = item->>'storageObjectPath'
    ) then
      raise exception using errcode = '23503', message = 'import document storage object does not exist';
    end if;
    if coalesce((item->>'duplicateAcknowledged')::boolean, false) = false and exists (
      select 1 from public.pricing_import_documents
      where content_sha256 = (item->>'contentSha256')::character(64)
    ) then
      raise exception using errcode = '23505', message = 'document already belongs to another import dossier';
    end if;
  end loop;

  insert into public.pricing_import_batches (
    source_type, idempotency_key, schema_version, status, metadata,
    plugin_key, dossier_title, competence, notes, created_by, updated_by
  ) values (
    'document_upload', pg_catalog.btrim(p_idempotency_key), 'import-engine/batch/1', 'uploaded',
    pg_catalog.jsonb_build_object('kind','import_engine','documentCount',total,'correlationId',p_correlation_id),
    p_plugin_key, pg_catalog.btrim(p_title), p_competence, nullif(pg_catalog.btrim(p_notes), ''),
    p_actor_id, p_actor_id
  ) returning * into batch_record;

  insert into public.pricing_audit_events (
    aggregate_type, aggregate_id, action, after_snapshot, reason, actor_id, correlation_id
  ) values (
    'pricing_import_batch', batch_record.id, 'insert', pg_catalog.to_jsonb(batch_record),
    'import dossier created', p_actor_id, p_correlation_id
  );

  for item in select value from pg_catalog.jsonb_array_elements(p_documents)
  loop
    insert into public.pricing_import_documents (
      batch_id, document_type, original_file_name, storage_bucket, storage_object_path,
      mime_type, file_size_bytes, content_sha256, status, source_order, document_role,
      provider_metadata, created_by, updated_by
    ) values (
      batch_record.id, (item->>'documentType')::public.pricing_import_document_type,
      pg_catalog.btrim(item->>'originalFileName'), item->>'storageBucket', item->>'storageObjectPath',
      item->>'mimeType', (item->>'fileSizeBytes')::bigint,
      (item->>'contentSha256')::character(64), 'ready', (item->>'sourceOrder')::integer,
      (item->>'documentRole')::public.pricing_import_document_role,
      pg_catalog.jsonb_build_object('duplicateAcknowledged',coalesce((item->>'duplicateAcknowledged')::boolean,false)),
      p_actor_id, p_actor_id
    ) returning * into document_record;
    document_ids := document_ids || pg_catalog.jsonb_build_array(document_record.id);
    insert into public.pricing_audit_events (
      aggregate_type, aggregate_id, action, after_snapshot, reason, actor_id, correlation_id
    ) values (
      'pricing_import_document', document_record.id, 'insert', pg_catalog.to_jsonb(document_record),
      'validated PDF stored privately', p_actor_id, p_correlation_id
    );
  end loop;

  update public.pricing_import_batches set status = 'ready', updated_by = p_actor_id
    where id = batch_record.id returning * into batch_record;
  insert into public.pricing_audit_events (
    aggregate_type, aggregate_id, action, before_snapshot, after_snapshot, reason, actor_id, correlation_id
  ) values (
    'pricing_import_batch', batch_record.id, 'update',
    pg_catalog.jsonb_build_object('status','uploaded'), pg_catalog.to_jsonb(batch_record),
    'all dossier documents are validated and ready', p_actor_id, p_correlation_id
  );
  return pg_catalog.jsonb_build_object(
    'batchId', batch_record.id, 'status', batch_record.status,
    'documentIds', document_ids, 'idempotentReplay', false
  );
end;
$$;

create function public.update_import_engine_document_role(
  p_document_id bigint,
  p_document_role public.pricing_import_document_role,
  p_expected_lock_version integer,
  p_actor_id uuid,
  p_correlation_id uuid
)
returns public.pricing_import_documents
language plpgsql
security definer
set search_path = ''
as $$
declare
  before_record public.pricing_import_documents%rowtype;
  after_record public.pricing_import_documents%rowtype;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  if p_correlation_id is null or p_expected_lock_version is null then
    raise exception using errcode='22004', message='document role update requires lock and correlation ID';
  end if;
  select * into before_record from public.pricing_import_documents where id=p_document_id for update;
  if not found then raise exception using errcode='P0002', message='import document does not exist'; end if;
  if before_record.lock_version<>p_expected_lock_version then raise exception using errcode='40001', message='stale import document lock version'; end if;
  if before_record.status not in ('uploaded','validated','ready','failed') then raise exception using errcode='55000', message='document role is no longer editable'; end if;
  update public.pricing_import_documents set document_role=p_document_role,updated_by=p_actor_id
    where id=p_document_id returning * into after_record;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,before_snapshot,after_snapshot,reason,actor_id,correlation_id)
    values('pricing_import_document',p_document_id,'update',pg_catalog.to_jsonb(before_record),pg_catalog.to_jsonb(after_record),'operator changed document role',p_actor_id,p_correlation_id);
  return after_record;
end;
$$;

create function public.reject_import_engine_document(
  p_document_id bigint,
  p_expected_lock_version integer,
  p_reason text,
  p_actor_id uuid,
  p_correlation_id uuid
)
returns public.pricing_import_documents
language plpgsql
security definer
set search_path = ''
as $$
declare
  before_record public.pricing_import_documents%rowtype;
  after_record public.pricing_import_documents%rowtype;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  if p_correlation_id is null or p_expected_lock_version is null or nullif(pg_catalog.btrim(p_reason),'') is null then
    raise exception using errcode='22004', message='document rejection requires lock, reason and correlation ID';
  end if;
  select * into before_record from public.pricing_import_documents where id=p_document_id for update;
  if not found then raise exception using errcode='P0002', message='import document does not exist'; end if;
  if before_record.lock_version<>p_expected_lock_version then raise exception using errcode='40001', message='stale import document lock version'; end if;
  if before_record.status not in ('uploaded','validated','ready','failed') then raise exception using errcode='55000', message='document can no longer be rejected'; end if;
  update public.pricing_import_documents set status='rejected',error_code=null,error_message=null,updated_by=p_actor_id
    where id=p_document_id returning * into after_record;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,before_snapshot,after_snapshot,reason,actor_id,correlation_id)
    values('pricing_import_document',p_document_id,'reject',pg_catalog.to_jsonb(before_record),pg_catalog.to_jsonb(after_record),pg_catalog.btrim(p_reason),p_actor_id,p_correlation_id);
  return after_record;
end;
$$;

create function public.archive_import_engine_batch(
  p_batch_id bigint,
  p_expected_lock_version integer,
  p_reason text,
  p_actor_id uuid,
  p_correlation_id uuid
)
returns public.pricing_import_batches
language plpgsql
security definer
set search_path = ''
as $$
declare
  before_record public.pricing_import_batches%rowtype;
  after_record public.pricing_import_batches%rowtype;
begin
  perform public.assert_active_pricing_admin(p_actor_id);
  if p_correlation_id is null or p_expected_lock_version is null or nullif(pg_catalog.btrim(p_reason),'') is null then
    raise exception using errcode='22004', message='batch archival requires lock, reason and correlation ID';
  end if;
  select * into before_record from public.pricing_import_batches where id=p_batch_id for update;
  if not found or before_record.plugin_key<>'commercial_letters' then raise exception using errcode='P0002', message='import batch does not exist'; end if;
  if before_record.lock_version<>p_expected_lock_version then raise exception using errcode='40001', message='stale import batch lock version'; end if;
  if before_record.status in ('extracting','needs_review','promoting','promoted','archived') then raise exception using errcode='55000', message='import batch can no longer be archived from this workflow'; end if;
  update public.pricing_import_documents set status='archived',updated_by=p_actor_id
    where batch_id=p_batch_id and status in ('uploaded','validated','ready','failed','rejected');
  update public.pricing_import_batches set status='archived',updated_by=p_actor_id
    where id=p_batch_id returning * into after_record;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,before_snapshot,after_snapshot,reason,actor_id,correlation_id)
    values('pricing_import_batch',p_batch_id,'archive',pg_catalog.to_jsonb(before_record),pg_catalog.to_jsonb(after_record),pg_catalog.btrim(p_reason),p_actor_id,p_correlation_id);
  return after_record;
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('import-engine-documents', 'import-engine-documents', false, 33554432, array['application/pdf']::text[])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.pricing_import_documents enable row level security;

revoke all privileges on table public.pricing_import_documents from public, anon, authenticated, service_role;
revoke all privileges on sequence public.pricing_import_documents_id_seq from public, anon, authenticated, service_role;
grant select, insert, update on table public.pricing_import_documents to service_role;
grant usage, select on sequence public.pricing_import_documents_id_seq to service_role;

revoke all on function public.validate_pricing_import_document_lifecycle() from public, anon, authenticated, service_role;
revoke all on function public.protect_pricing_import_document() from public, anon, authenticated, service_role;
revoke all on function public.protect_import_engine_batch_identity() from public, anon, authenticated, service_role;
revoke all on function public.create_import_engine_batch(text,text,date,text,text,jsonb,uuid,uuid) from public, anon, authenticated, service_role;
revoke all on function public.update_import_engine_document_role(bigint,public.pricing_import_document_role,integer,uuid,uuid) from public, anon, authenticated, service_role;
revoke all on function public.reject_import_engine_document(bigint,integer,text,uuid,uuid) from public, anon, authenticated, service_role;
revoke all on function public.archive_import_engine_batch(bigint,integer,text,uuid,uuid) from public, anon, authenticated, service_role;

grant execute on function public.create_import_engine_batch(text,text,date,text,text,jsonb,uuid,uuid) to service_role;
grant execute on function public.update_import_engine_document_role(bigint,public.pricing_import_document_role,integer,uuid,uuid) to service_role;
grant execute on function public.reject_import_engine_document(bigint,integer,text,uuid,uuid) to service_role;
grant execute on function public.archive_import_engine_batch(bigint,integer,text,uuid,uuid) to service_role;
