create type public.pricing_import_processing_job_status as enum ('queued','processing','succeeded','failed');

create table public.pricing_import_processing_jobs (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.pricing_import_batches(id) on delete restrict,
  attempt integer not null check (attempt > 0),
  status public.pricing_import_processing_job_status not null default 'queued',
  plugin_key text not null check (plugin_key = 'commercial_letters'),
  plugin_version text not null check (nullif(pg_catalog.btrim(plugin_version),'') is not null),
  provider_key text not null check (provider_key ~ '^[a-z][a-z0-9_-]{1,63}$'),
  provider_version text not null check (nullif(pg_catalog.btrim(provider_version),'') is not null),
  schema_version text not null check (schema_version = 'commercial-letter/mmv-payload/1'),
  claim_token uuid,
  claimed_at timestamptz,
  claim_expires_at timestamptz,
  completed_at timestamptz,
  provider_run_id text check (provider_run_id is null or pg_catalog.length(provider_run_id) <= 200),
  usage_metadata jsonb not null default '{}'::jsonb,
  error_code text,
  error_message text,
  correlation_id uuid not null,
  created_at timestamptz not null default pg_catalog.now(),
  created_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default pg_catalog.now(),
  updated_by uuid references public.profiles(id) on delete set null,
  lock_version integer not null default 1 check (lock_version > 0),
  unique(batch_id,attempt),
  check (pg_catalog.jsonb_typeof(usage_metadata)='object' and pg_catalog.length(usage_metadata::text)<=2048),
  check ((status='queued' and claim_token is null and claimed_at is null and claim_expires_at is null and completed_at is null)
    or (status='processing' and claim_token is not null and claimed_at is not null and claim_expires_at>claimed_at and completed_at is null)
    or (status in ('succeeded','failed') and claim_token is not null and claimed_at is not null and claim_expires_at is not null and completed_at is not null)),
  check ((status='failed' and nullif(pg_catalog.btrim(error_code),'') is not null and pg_catalog.length(error_code)<=64
      and nullif(pg_catalog.btrim(error_message),'') is not null and pg_catalog.length(error_message)<=1000)
    or (status<>'failed' and error_code is null and error_message is null))
);
create unique index pricing_import_processing_jobs_active_batch_idx on public.pricing_import_processing_jobs(batch_id) where status in ('queued','processing');
create index pricing_import_processing_jobs_batch_created_idx on public.pricing_import_processing_jobs(batch_id,created_at desc);
create index pricing_import_processing_jobs_reclaim_idx on public.pricing_import_processing_jobs(claim_expires_at) where status='processing';

create trigger pricing_import_processing_jobs_set_updated_at before update on public.pricing_import_processing_jobs
for each row execute function public.set_pricing_updated_at();

alter table public.pricing_import_rows add column generation_job_id bigint references public.pricing_import_processing_jobs(id) on delete restrict;
create index pricing_import_rows_generation_job_idx on public.pricing_import_rows(generation_job_id) where generation_job_id is not null;

alter table public.pricing_audit_events drop constraint pricing_audit_events_aggregate_type_check;
alter table public.pricing_audit_events add constraint pricing_audit_events_aggregate_type_check check (
  aggregate_type in ('product_public_price','financial_parameter_set','commercial_policy','commercial_policy_application',
  'commercial_policy_accumulator','commercial_offer','pricing_import_batch','pricing_import_row','pricing_import_document','pricing_import_processing_job')
);

alter table public.pricing_import_processing_jobs enable row level security;
revoke all on table public.pricing_import_processing_jobs from public,anon,authenticated,service_role;
revoke all on sequence public.pricing_import_processing_jobs_id_seq from public,anon,authenticated,service_role;
grant select,insert,update on table public.pricing_import_processing_jobs to service_role;
grant usage,select on sequence public.pricing_import_processing_jobs_id_seq to service_role;

create function public.enqueue_import_processing_job(p_batch_id bigint,p_plugin_version text,p_provider_key text,p_provider_version text,p_schema_version text,p_actor_id uuid,p_correlation_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare b public.pricing_import_batches%rowtype; j public.pricing_import_processing_jobs%rowtype;
begin
  if p_actor_id is null or p_correlation_id is null then raise exception using errcode='22023',message='actor and correlation are required'; end if;
  select * into b from public.pricing_import_batches where id=p_batch_id for update;
  if not found then raise exception using errcode='P0002',message='import batch not found'; end if;
  if b.plugin_key<>'commercial_letters' or b.status not in ('ready','failed') then raise exception using errcode='55000',message='batch is not eligible for extraction'; end if;
  if exists(select 1 from public.pricing_import_rows where batch_id=p_batch_id) then raise exception using errcode='55000',message='batch already has materialized rows'; end if;
  select * into j from public.pricing_import_processing_jobs where batch_id=p_batch_id and status in ('queued','processing');
  if found then return pg_catalog.jsonb_build_object('jobId',j.id,'attempt',j.attempt,'status',j.status,'idempotentReplay',true); end if;
  insert into public.pricing_import_processing_jobs(batch_id,attempt,plugin_key,plugin_version,provider_key,provider_version,schema_version,correlation_id,created_by,updated_by)
  values(p_batch_id,coalesce((select max(attempt)+1 from public.pricing_import_processing_jobs where batch_id=p_batch_id),1),'commercial_letters',p_plugin_version,p_provider_key,p_provider_version,p_schema_version,p_correlation_id,p_actor_id,p_actor_id) returning * into j;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id)
  values('pricing_import_processing_job',j.id,'insert',pg_catalog.jsonb_build_object('status',j.status,'attempt',j.attempt,'provider',j.provider_key,'providerVersion',j.provider_version,'plugin',j.plugin_key,'pluginVersion',j.plugin_version),'processing attempt queued',p_actor_id,j.correlation_id);
  return pg_catalog.jsonb_build_object('jobId',j.id,'attempt',j.attempt,'status',j.status,'idempotentReplay',false);
end $$;

create function public.claim_import_processing_job(p_job_id bigint,p_claim_token uuid,p_actor_id uuid,p_correlation_id uuid,p_lease_seconds integer)
returns jsonb language plpgsql security definer set search_path='' as $$
declare j public.pricing_import_processing_jobs%rowtype; b public.pricing_import_batches%rowtype; reclaim boolean:=false;
begin
  if p_claim_token is null or p_actor_id is null or p_correlation_id is null or p_lease_seconds not between 30 and 900 then raise exception using errcode='22023',message='valid claim inputs are required'; end if;
  select * into j from public.pricing_import_processing_jobs where id=p_job_id for update;
  if not found then raise exception using errcode='P0002',message='processing job not found'; end if;
  if j.correlation_id<>p_correlation_id then raise exception using errcode='22023',message='correlation mismatch'; end if;
  select * into b from public.pricing_import_batches where id=j.batch_id for update;
  if j.status='processing' and j.claim_token=p_claim_token and j.claim_expires_at>pg_catalog.now() then return pg_catalog.jsonb_build_object('jobId',j.id,'batchId',j.batch_id,'status',j.status,'idempotentReplay',true); end if;
  reclaim:=j.status='processing' and j.claim_expires_at<=pg_catalog.now();
  if j.status='queued' and b.status not in ('ready','failed') or reclaim and b.status<>'extracting' then raise exception using errcode='55000',message='batch is not eligible for claim'; end if;
  if j.status<>'queued' and not reclaim then raise exception using errcode='55000',message='processing job cannot be claimed'; end if;
  update public.pricing_import_processing_jobs set status='processing',claim_token=p_claim_token,claimed_at=pg_catalog.now(),claim_expires_at=pg_catalog.now()+pg_catalog.make_interval(secs=>p_lease_seconds),updated_by=p_actor_id where id=j.id returning * into j;
  if not reclaim then
    update public.pricing_import_batches set status='extracting',extractor_provider=j.provider_key,extractor_model=j.provider_version,prompt_version=j.plugin_version,schema_version=j.schema_version,metadata=metadata||pg_catalog.jsonb_build_object('lastProcessingJobId',j.id,'correlationId',j.correlation_id),updated_by=p_actor_id where id=j.batch_id;
    update public.pricing_import_documents set status='uploaded',error_code=null,error_message=null,updated_by=p_actor_id where batch_id=j.batch_id and status='failed';
    update public.pricing_import_documents set status='validated',updated_by=p_actor_id where batch_id=j.batch_id and status='uploaded';
    update public.pricing_import_documents set status='ready',updated_by=p_actor_id where batch_id=j.batch_id and status='validated';
    update public.pricing_import_documents set status='processing',updated_by=p_actor_id where batch_id=j.batch_id and status='ready';
  end if;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id)
  values('pricing_import_processing_job',j.id,'update',pg_catalog.jsonb_build_object('status',j.status,'claimedAt',j.claimed_at,'claimExpiresAt',j.claim_expires_at,'reclaimed',reclaim),case when reclaim then 'expired processing lease reclaimed' else 'processing attempt claimed' end,p_actor_id,j.correlation_id);
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id)
  values('pricing_import_batch',j.batch_id,'update',pg_catalog.jsonb_build_object('status','extracting','processingJobId',j.id),case when reclaim then 'batch processing lease reclaimed' else 'batch entered extraction' end,p_actor_id,j.correlation_id);
  return pg_catalog.jsonb_build_object('jobId',j.id,'batchId',j.batch_id,'status',j.status,'reclaimed',reclaim,'idempotentReplay',false);
end $$;

create function public.finalize_import_processing_job(p_job_id bigint,p_claim_token uuid,p_rows jsonb,p_provider_run_id text,p_usage jsonb,p_actor_id uuid,p_correlation_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare j public.pricing_import_processing_jobs%rowtype; b public.pricing_import_batches%rowtype; item jsonb; inserted_count integer:=0; total_bytes bigint:=0;
begin
  if p_actor_id is null or p_correlation_id is null then raise exception using errcode='22023',message='actor and correlation are required'; end if;
  select * into j from public.pricing_import_processing_jobs where id=p_job_id for update;
  if not found then raise exception using errcode='P0002',message='processing job not found'; end if;
  if j.correlation_id<>p_correlation_id then raise exception using errcode='22023',message='correlation mismatch'; end if;
  select * into b from public.pricing_import_batches where id=j.batch_id for update;
  if j.status='succeeded' and j.claim_token=p_claim_token then return pg_catalog.jsonb_build_object('jobId',j.id,'batchId',j.batch_id,'rowCount',(select count(*) from public.pricing_import_rows where generation_job_id=j.id),'idempotentReplay',true); end if;
  if j.status<>'processing' or j.claim_token<>p_claim_token or j.claim_expires_at<=pg_catalog.now() then raise exception using errcode='55000',message='processing claim is invalid or expired'; end if;
  if b.status<>'extracting' then raise exception using errcode='55000',message='batch is not extracting'; end if;
  if pg_catalog.jsonb_typeof(p_rows)<>'array' or pg_catalog.jsonb_array_length(p_rows) not between 1 and 100 then raise exception using errcode='22023',message='normalized row count is invalid'; end if;
  if pg_catalog.jsonb_typeof(p_usage)<>'object' or pg_catalog.length(p_usage::text)>2048 then raise exception using errcode='22023',message='usage metadata is invalid'; end if;
  for item in select value from pg_catalog.jsonb_array_elements(p_rows) loop
    total_bytes:=total_bytes+pg_catalog.octet_length((item->'rawPayload')::text)+pg_catalog.octet_length((item->'normalizedPayload')::text);
    if (item->>'sourceRowNumber')::integer<1 or pg_catalog.jsonb_typeof(item->'rawPayload')<>'object' or pg_catalog.jsonb_typeof(item->'normalizedPayload')<>'object'
      or item->'rawPayload'->>'schemaVersion'<>'commercial-letter/mmv-payload/1' or item->'normalizedPayload'->>'schemaVersion'<>'commercial-letter/mmv-payload/1'
      or (item->>'status') not in ('unmatched','needs_review') then raise exception using errcode='22023',message='invalid normalized row'; end if;
    if pg_catalog.octet_length((item->'rawPayload')::text)>262144 or pg_catalog.octet_length((item->'normalizedPayload')::text)>262144 then raise exception using errcode='22023',message='normalized row payload exceeds limit'; end if;
    insert into public.pricing_import_rows(batch_id,source_row_number,source_page,raw_payload,normalized_payload,confidence_score,matched_product_id,status,issue_codes,generation_job_id,created_by,updated_by)
    values(j.batch_id,(item->>'sourceRowNumber')::integer,nullif(item->>'sourcePage','')::integer,item->'rawPayload',item->'normalizedPayload',(item->>'confidenceScore')::numeric,nullif(item->>'matchedProductId','')::integer,(item->>'status')::public.pricing_import_row_status,array(select pg_catalog.jsonb_array_elements_text(item->'issueCodes')),j.id,p_actor_id,p_actor_id);
    inserted_count:=inserted_count+1;
  end loop;
  if total_bytes>10485760 then raise exception using errcode='22023',message='processing payload exceeds aggregate limit'; end if;
  update public.pricing_import_processing_jobs set status='succeeded',completed_at=pg_catalog.now(),provider_run_id=pg_catalog.left(p_provider_run_id,200),usage_metadata=p_usage,updated_by=p_actor_id where id=j.id returning * into j;
  update public.pricing_import_documents set status='processed',updated_by=p_actor_id where batch_id=j.batch_id and status='processing';
  update public.pricing_import_batches set status='needs_review',metadata=metadata||pg_catalog.jsonb_build_object('rowCount',inserted_count,'processedAt',pg_catalog.now(),'lastProcessingJobId',j.id,'correlationId',j.correlation_id),updated_by=p_actor_id where id=j.batch_id;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id) values
  ('pricing_import_processing_job',j.id,'update',pg_catalog.jsonb_build_object('status','succeeded','rowCount',inserted_count,'providerRunId',j.provider_run_id,'usage',j.usage_metadata),'processing attempt succeeded',p_actor_id,j.correlation_id),
  ('pricing_import_batch',j.batch_id,'update',pg_catalog.jsonb_build_object('status','needs_review','rowCount',inserted_count,'processingJobId',j.id),'extracted rows ready for human review',p_actor_id,j.correlation_id);
  return pg_catalog.jsonb_build_object('jobId',j.id,'batchId',j.batch_id,'rowCount',inserted_count,'idempotentReplay',false);
end $$;

create function public.fail_import_processing_job(p_job_id bigint,p_claim_token uuid,p_error_code text,p_error_message text,p_actor_id uuid,p_correlation_id uuid)
returns void language plpgsql security definer set search_path='' as $$
declare j public.pricing_import_processing_jobs%rowtype; b public.pricing_import_batches%rowtype; safe_code text; safe_message text;
begin
  if p_actor_id is null or p_correlation_id is null then raise exception using errcode='22023',message='actor and correlation are required'; end if;
  safe_code:=pg_catalog.upper(pg_catalog.regexp_replace(coalesce(p_error_code,''),'[^A-Za-z0-9_]','','g'));
  safe_message:=pg_catalog.left(pg_catalog.regexp_replace(coalesce(p_error_message,''),'(sk-|sb_secret_|eyJ|postgres(?:ql)?://)[^[:space:]]+','[REDACTED]','gi'),1000);
  if nullif(safe_code,'') is null or nullif(pg_catalog.btrim(safe_message),'') is null then raise exception using errcode='22023',message='safe error diagnostic is required'; end if;
  select * into j from public.pricing_import_processing_jobs where id=p_job_id for update;
  if not found then raise exception using errcode='P0002',message='processing job not found'; end if;
  if j.correlation_id<>p_correlation_id then raise exception using errcode='22023',message='correlation mismatch'; end if;
  select * into b from public.pricing_import_batches where id=j.batch_id for update;
  if j.status='failed' and j.claim_token=p_claim_token then return; end if;
  if j.status<>'processing' or j.claim_token<>p_claim_token or j.claim_expires_at<=pg_catalog.now() then raise exception using errcode='55000',message='processing claim is invalid or expired'; end if;
  if b.status<>'extracting' then raise exception using errcode='55000',message='batch is not extracting'; end if;
  update public.pricing_import_processing_jobs set status='failed',completed_at=pg_catalog.now(),error_code=pg_catalog.left(safe_code,64),error_message=safe_message,updated_by=p_actor_id where id=j.id returning * into j;
  update public.pricing_import_documents set status='failed',error_code='PROCESSING_FAILED',error_message='Processing failed; see job audit.',updated_by=p_actor_id where batch_id=j.batch_id and status='processing';
  update public.pricing_import_batches set status='failed',metadata=metadata||pg_catalog.jsonb_build_object('processingErrorCode',j.error_code,'processingErrorMessage',j.error_message,'lastProcessingJobId',j.id,'correlationId',j.correlation_id),updated_by=p_actor_id where id=j.batch_id;
  insert into public.pricing_audit_events(aggregate_type,aggregate_id,action,after_snapshot,reason,actor_id,correlation_id) values
  ('pricing_import_processing_job',j.id,'update',pg_catalog.jsonb_build_object('status','failed','errorCode',j.error_code,'errorMessage',j.error_message),'processing attempt failed',p_actor_id,j.correlation_id),
  ('pricing_import_batch',j.batch_id,'update',pg_catalog.jsonb_build_object('status','failed','processingJobId',j.id,'errorCode',j.error_code),'batch extraction failed',p_actor_id,j.correlation_id);
end $$;

revoke all on function public.enqueue_import_processing_job(bigint,text,text,text,text,uuid,uuid) from public,anon,authenticated,service_role;
revoke all on function public.claim_import_processing_job(bigint,uuid,uuid,uuid,integer) from public,anon,authenticated,service_role;
revoke all on function public.finalize_import_processing_job(bigint,uuid,jsonb,text,jsonb,uuid,uuid) from public,anon,authenticated,service_role;
revoke all on function public.fail_import_processing_job(bigint,uuid,text,text,uuid,uuid) from public,anon,authenticated,service_role;
grant execute on function public.enqueue_import_processing_job(bigint,text,text,text,text,uuid,uuid) to service_role;
grant execute on function public.claim_import_processing_job(bigint,uuid,uuid,uuid,integer) to service_role;
grant execute on function public.finalize_import_processing_job(bigint,uuid,jsonb,text,jsonb,uuid,uuid) to service_role;
grant execute on function public.fail_import_processing_job(bigint,uuid,text,text,uuid,uuid) to service_role;
