import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { canonicalJson } from './canonical.js';
import type { DryRunOptions, DryRunResult } from './types.js';

export interface CsvColumn<T> {
  header: string;
  value: (row: T) => unknown;
}

function csvCell(value: unknown): string {
  const text = value === null || value === undefined ? '' : String(value);
  return /[",\r\n]/u.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

export function stableCsv<T>(rows: T[], columns: CsvColumn<T>[]): string {
  return (
    [
      columns.map((column) => csvCell(column.header)).join(','),
      ...rows.map((row) => columns.map((column) => csvCell(column.value(row))).join(',')),
    ].join('\n') + '\n'
  );
}

function stablePrettyJson(value: unknown): string {
  return JSON.stringify(JSON.parse(canonicalJson(value)), null, 2) + '\n';
}

function safeVersion(version: string): string {
  return version.replaceAll(/[^A-Za-z0-9._-]/gu, '_');
}

function reportDirectoryName(executedAt: string, algorithmVersion: string): string {
  const timestamp = executedAt.replaceAll(/[-:]/gu, '').replace('.000Z', 'Z');
  return `${timestamp}-v${safeVersion(algorithmVersion)}`;
}

function reportReadme(options: DryRunOptions): string {
  return `# Pricing legacy dry-run

This directory contains a deterministic simulation generated by algorithm version
\`${options.algorithmVersion}\` at \`${options.executedAt}\`.

No candidate in these files was inserted, promoted or published. The database reader uses a
repeatable-read, read-only transaction and the reports are local files only.

## Interpretation

- \`summary.json\`: sanitized execution identity, hashes, counts, baseline differences and status.
- \`source-inventory.csv\`: source counts, business-date ranges and logical hashes.
- \`public-price-candidates.csv\`: logical price candidates; conflicts never have an automatic winner.
- \`policy-candidates.csv\`: independent policy suggestions; null monetary results require review.
- \`accumulator-candidates.csv\`: combination suggestions only; none is automatically publishable.
- \`needs-review.csv\`: issue codes and evidence requiring human review.
- \`reconciliation.csv\`: exact-decimal comparison with the legacy customer total.
- \`view-coverage.csv\`: expected compatibility coverage and absence reasons.

## Backfill blockers

Backfill remains blocked while the source baseline changed without approval, conflicts or invalid
values exist, financing lacks a published parameter set, AND/OR semantics are unresolved, or any
candidate classified as \`needs_review\` has not been decided by a human.

The optional insurance percentage is only a simulation premise and never authorizes publication.
`;
}

export async function writeReports(
  outputBaseDirectory: string,
  result: DryRunResult,
  options: DryRunOptions,
): Promise<string> {
  await mkdir(outputBaseDirectory, { recursive: true });
  const outputDirectory = path.resolve(
    outputBaseDirectory,
    reportDirectoryName(options.executedAt, options.algorithmVersion),
  );
  await mkdir(outputDirectory, { recursive: false });

  const files = new Map<string, string>([
    ['summary.json', stablePrettyJson(result.summary)],
    [
      'source-inventory.csv',
      stableCsv(result.sourceInventory, [
        { header: 'source_table', value: (row) => row.sourceTable },
        { header: 'source_count', value: (row) => row.sourceCount },
        { header: 'distinct_products', value: (row) => row.distinctProducts },
        { header: 'min_business_date', value: (row) => row.minBusinessDate },
        { header: 'max_business_date', value: (row) => row.maxBusinessDate },
        { header: 'logical_hash', value: (row) => row.logicalHash },
      ]),
    ],
    [
      'public-price-candidates.csv',
      stableCsv(result.publicPriceCandidates, [
        { header: 'source_ids', value: (row) => row.sourceIds.join('|') },
        { header: 'product_id', value: (row) => row.productId },
        { header: 'starts_on', value: (row) => row.startsOn },
        { header: 'legacy_value', value: (row) => row.legacyValue },
        { header: 'proposed_value', value: (row) => row.proposedValue },
        { header: 'classification', value: (row) => row.classification },
        { header: 'issue_codes', value: (row) => row.issueCodes.join('|') },
        { header: 'deduplication_group', value: (row) => row.deduplicationGroup },
        { header: 'logical_fingerprint', value: (row) => row.logicalFingerprint },
      ]),
    ],
    [
      'public-price-conflicts.csv',
      stableCsv(result.publicPriceConflicts, [
        { header: 'product_id', value: (row) => row.productId },
        { header: 'starts_on', value: (row) => row.startsOn },
        { header: 'source_ids', value: (row) => row.sourceIds.join('|') },
        { header: 'distinct_values', value: (row) => row.distinctValues.join('|') },
        { header: 'issue_code', value: (row) => row.issueCode },
        { header: 'automatic_winner', value: (row) => row.automaticWinner },
      ]),
    ],
    [
      'policy-candidates.csv',
      stableCsv(result.policyCandidates, [
        { header: 'source_id', value: (row) => row.sourceId },
        { header: 'product_id', value: (row) => row.productId },
        { header: 'proposed_policy_type', value: (row) => row.proposedPolicyType },
        { header: 'calculation_method', value: (row) => row.calculationMethod },
        { header: 'input_monetary_value', value: (row) => row.inputMonetaryValue },
        { header: 'proposed_monetary_value', value: (row) => row.proposedMonetaryValue },
        { header: 'starts_on', value: (row) => row.startsOn },
        { header: 'classification', value: (row) => row.classification },
        { header: 'issue_codes', value: (row) => row.issueCodes.join('|') },
        { header: 'evidence_fields', value: (row) => row.evidence },
        { header: 'fingerprint', value: (row) => row.fingerprint },
      ]),
    ],
    [
      'accumulator-candidates.csv',
      stableCsv(result.accumulatorCandidates, [
        { header: 'source_id', value: (row) => row.sourceId },
        {
          header: 'proposed_policy_fingerprints',
          value: (row) => row.proposedPolicyFingerprints.join('|'),
        },
        { header: 'evidence_text', value: (row) => row.evidenceText },
        { header: 'and_or_classification', value: (row) => row.andOrClassification },
        { header: 'issue_codes', value: (row) => row.issueCodes.join('|') },
        { header: 'automatically_publishable', value: (row) => row.automaticallyPublishable },
        { header: 'fingerprint', value: (row) => row.fingerprint },
      ]),
    ],
    [
      'needs-review.csv',
      stableCsv(result.needsReview, [
        { header: 'source_table', value: (row) => row.source_table },
        { header: 'source_id', value: (row) => row.source_id },
        { header: 'entity_type', value: (row) => row.entity_type },
        { header: 'classification', value: (row) => row.classification },
        { header: 'issue_codes', value: (row) => row.issue_codes },
        { header: 'evidence', value: (row) => row.evidence },
        { header: 'fingerprint', value: (row) => row.fingerprint },
      ]),
    ],
    [
      'reconciliation.csv',
      stableCsv(result.reconciliation, [
        { header: 'product_id', value: (row) => row.productId },
        { header: 'offer_month', value: (row) => row.offerMonth },
        { header: 'source_id', value: (row) => row.sourceId },
        { header: 'legacy_public_price', value: (row) => row.legacyPublicPrice },
        { header: 'proposed_public_price', value: (row) => row.proposedPublicPrice },
        { header: 'explicit_benefit_inputs', value: (row) => row.explicitBenefitInputs },
        {
          header: 'safely_calculated_components',
          value: (row) => row.safelyCalculatedComponents,
        },
        {
          header: 'legacy_total_customer_benefit',
          value: (row) => row.legacyTotalCustomerBenefit,
        },
        { header: 'calculated_known_total', value: (row) => row.calculatedKnownTotal },
        { header: 'absolute_difference', value: (row) => row.absoluteDifference },
        { header: 'percentage_difference', value: (row) => row.percentageDifference },
        { header: 'explanation', value: (row) => row.explanation },
        { header: 'status', value: (row) => row.status },
        { header: 'issue_codes', value: (row) => row.issueCodes.join('|') },
      ]),
    ],
    [
      'view-coverage.csv',
      stableCsv(result.viewCoverage, [
        { header: 'product_id', value: (row) => row.productId },
        { header: 'active_product', value: (row) => row.activeProduct },
        { header: 'has_active_specs', value: (row) => row.hasActiveSpecs },
        { header: 'has_legacy_current_price', value: (row) => row.hasLegacyCurrentPrice },
        {
          header: 'has_new_current_price_candidate',
          value: (row) => row.hasNewCurrentPriceCandidate,
        },
        { header: 'eligible_for_v2', value: (row) => row.eligibleForV2 },
        { header: 'absence_reason', value: (row) => row.absenceReason },
      ]),
    ],
    ['README.md', reportReadme(options)],
  ]);

  await Promise.all(
    [...files.entries()].map(([fileName, content]) =>
      writeFile(path.join(outputDirectory, fileName), content, { encoding: 'utf8', flag: 'wx' }),
    ),
  );
  return outputDirectory;
}
